### ISSUE TITLE
Diagnosics require write permission and failed with exception that didn't make sense

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#5206] opened 2018-07-04 10:11 UTC
A customer reports that due to writing diagnostics an IIS hosted endpoint fails:

> Detected running in a website and attempted to use HostingEnvironment.MapPath("~/App_Data/") to derive the logging path

This is confusing, as they use NLog which was already initialized and they didn't understand why this line contained *to derive the logging path*. 

They resolved this by disabling the diagnostics via:

```c#
endpointConfiguration.CustomDiagnosticsWriter(s => Task.CompletedTask)
```

It seems the errors/messages returned when diagnostics data fails to be written can be improved as it is unclear what the cause is.

**Comment by timbussmann** [comment] 2018-07-04 12:35
Sounds like a duplicate of https://github.com/Particular/NServiceBus/issues/5117. This will be improved with https://github.com/Particular/NServiceBus/pull/5189. Note that the PR also changes the behavior to no longer throw an exception when unable to write the diagnostics file. Feel free to add your thoughts on the PR and the related issue.

**Closed by timbussmann** 2018-07-04 12:35 UTC
