### ISSUE TITLE
RabbitMQ Transport Config Doesn't Support TLS / AMQPS Scheme

### ISSUE THREAD

**Issue by oshea00** [Particular/NServiceBus#2687] opened 2015-03-19 17:07 UTC
Should be able to specify cert locations and "scheme=amqps" on the RabbitMQ connection string to the RabbitMQ transport.

**Comment by andreasohlund** [comment] 2015-03-19 17:57
Duplicate of https://github.com/Particular/NServiceBus.RabbitMQ/issues/82

**Closed by andreasohlund** 2015-03-19 17:57 UTC
