### ISSUE TITLE
Add PipelineExecutor upgrade guide and update the obsolete message

### ISSUE THREAD

**Issue by HEskandari** [Particular/NServiceBus#3256] opened 2015-12-18 01:52 UTC
The code I'm working on uses PipelineExecutor, which doesn't compile now because that's made obsolete. 

So far so good, but the error message is this:

You can no longer get access to the pipeline context via DI. Please use a behavior to get access instead. Will be removed in version 7.0.0.

It doesn't help me at all on how to solve the issue.

**Comment by andreasohlund** [comment] 2015-12-18 08:52
How about adding "The context is passed via method injection in Version 6" or something similar?

**Comment by HEskandari** [comment] 2015-12-21 01:45
This message is there all over the place and not just for `PipilneExecutor`. I'd say having a generic text plus a link to the upgrade documents on our docs website would make it more usable.

**Comment by SimonCropp** [comment] 2015-12-21 02:18
no links to doco

**Comment by HEskandari** [comment] 2015-12-21 03:10
@SimonCropp why not?

**Comment by mikeminutillo** [comment] 2015-12-21 04:23
Links to doco essentially freeze the docs for the duration of support (at
least!).

**Comment by timbussmann** [comment] 2016-03-18 16:26
Can we add something like "please consult the upgrade guide for further information" as we seem to do on other obsoletes?

**Comment by timbussmann** [comment] 2016-03-22 15:53
@HEskandari can you give some background about the code which used the PipelineExecutor? Where and why?

**Comment by HEskandari** [comment] 2016-03-22 23:45
@timbussmann I was in a process of updating a sample, I believe. The shown error didn't make it quite clear how should I fix the compilation error. After spending some time, I do believe that the upgrade doc should be able to do the trick. So :+1: on your suggestion.

**Comment by timbussmann** [comment] 2016-03-23 07:25
@HEskandari :+1: I'll assign you to this issue then

**Comment by andreasohlund** [comment] 2016-03-23 12:28
@HEskandari can you also update the title to something more expressive?

**Comment by HEskandari** [comment] 2016-03-24 07:33
The sample I was working to update was the multi-tenant sample that makes use of PiplelineExecutor. As a part of updating the upgrade guide, I did the upgrade on the sample first (can be found [here](https://github.com/Particular/docs.particular.net/pull/1352))

I don't see what's the replacement of PipelineExecutor, but it looks like the components are mostly internalized and customer shouldn't be relying on them anymore ([here's](https://github.com/Particular/docs.particular.net/blob/master/samples/outbox/multi-tenant/Version_5/Receiver/Program.cs#L78) the usage I was facing). If anyone could confirm, I'll finalize the guide/obsolete message.

**Comment by timbussmann** [comment] 2016-03-29 07:03
from the sample it looks like it wants access to the message context though the PipelineExecutor. Looks like that stuff should be replaced by a behavior.

> but it looks like the components are mostly internalized and customer shouldn't be relying on them anymore

confirmed

**Comment by andreasohlund** [comment] 2016-03-30 12:57
Pull is merged, closing this one

**Closed by andreasohlund** 2016-03-30 12:57 UTC
Labels: Project: V6 Launch
