### ISSUE TITLE
Move IWantToRunWhenBusStartsAndStops to the hosts

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3342] opened 2016-01-18 11:06 UTC
Taskforce: @kbaley @colin-higgins @distantcam @boblangley 

**PROBLEM:**
Starting with NServiceBus v6, It is the responsibility of the implementing class to execute its operations in parallel if needed (i.e. for CPU bound work). Failure to do so will prevent the bus from being started and/or disposed. 

The new behavior is documented here:
http://docs.particular.net/nservicebus/upgrades/5to6#iwanttorunwhenbusstartsandstops-execution

Although it is documented, this is a breaking change and we can't rely on documentation alone to make it clear to the users. As the users can still run into issues with the bus not being started due to a blocked action in the class implementing the IWantToRunWhenBusStartsAndStops interface.

**PROPOSED SOLUTION**
Thanks @SimonCropp - Obsolete the existing interface to let the user know as part of the V6 conversion, as opposed to having the user rely on documentation to know this new behavior change. 

Tasks:

- [x] Obsolete `IWantToRunWhenBusStartsAndStops`
- [x] Update documentation & samples (https://github.com/Particular/docs.particular.net/pull/1373)
- [x] Move interface to [NServiceBus.Host](https://github.com/Particular/NServiceBus.Host/issues/60) and [NServiceBus.Host.AzureCloudService](https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/24)
- [x] Move related acceptance tests to host projects
- [x] Refactor existing acceptance tests that rely on IWantToRunWhenBusStartsAndStops for assertions
- [x] Warn users with long running startables
   - [x] NServiceBus.Host: https://github.com/Particular/NServiceBus.Host/pull/72
   - [x] NServiceBus.Host.AzureCloudService: https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/29

**Comment by andreasohlund** [comment] 2016-01-25 06:53
After a long debate with @danielmarbach we came to the following conclusion:

* Obsolete the IWantToRunAtStartAndStop in the core since it's not needed when self hosting
* Move it to the host and clearly state that the behavior now blocks by default so users needs to kick off a new thread if they want to do a "while true"

Daniel, can you confirm?

**Comment by danielmarbach** [comment] 2016-01-25 07:16
@andreasohlund Confirmed. I couldn't come up with a scenario (that doesn't assume message ordering) which requires the capability to send before the endpoints message pump starts.

**Comment by andreasohlund** [comment] 2016-01-25 07:54
So the guidance for self hosted users would be:

```
var config = new BusConfiguration();

var instance = await Endpoint.Start(busConfiguration);

InvokeMyStartStuff(instance);
....

InvokeMyStopStuff(instance);

instance.Stop();
```

Correct?

**Comment by danielmarbach** [comment] 2016-01-26 13:43
Correct.

**Comment by timbussmann** [comment] 2016-01-27 09:57
`IWantToRunAtStartAndStop` supports DI while @andreasohlund sample won't, could this be an issue?

**Comment by danielmarbach** [comment] 2016-01-27 10:06
@timbussmann on the level of BusConfiguration you most certainly have your custom DI container.

**Comment by andreasohlund** [comment] 2016-01-27 11:27
Agree with @danielmarbach , if you want DI just resolve from your container of choise? (there is no way to get access to `IBuilder` in v6 right?)

**Comment by timbussmann** [comment] 2016-01-27 12:09
I'm fine with that, just wanted to mention that for scenarios where users don't provide their custom container. I think we already tried to move that interface to the host once and it failed. I think the issue was the host not having access to the container to actually resolve the `IWantToRunAtStartAndStop` instances or something like that.

**Comment by johnsimons** [comment] 2016-01-29 02:44
Should we drop this for now ? Maybe do it in 6.1 ?

**Comment by timbussmann** [comment] 2016-01-29 08:34
@johnsimons wouldn't that introduce a breaking change in a minor release?

**Comment by andreasohlund** [comment] 2016-01-29 08:58
It would be a breaking change yes. Given the confusion this caused me and @indualagarsamy when trying to upgrade the sqlbridge I'd propose we do it in v6 to avoid causing to much pain for our users

**Comment by indualagarsamy** [comment] 2016-01-29 21:59
I think this is a simple change to do, which will avoid the users a lot of pain during the upgrade process. If this was a mega feature, I'd be all for moving it to 6.1

**Comment by andreasohlund** [comment] 2016-02-04 07:51
I propose that we name the new api:

`IWantToRunWhenHostStartsAndStops` 

considered `IWantToRunWhenEndpointStartAndStops` but since this now is in the host `Host` feels better to me?

**Comment by johnsimons** [comment] 2016-02-04 08:08
How is this going to work with the assembly scanner ?
Can the host still access the scanned types ?

**Comment by timbussmann** [comment] 2016-02-04 10:43
> considered IWantToRunWhenEndpointStartAndStops but since this now is in the host Host feels better to me?

I know we're on the renaming spree but I think `IWantToRunWhenEndpointStartAndStops` still matches exactly what it does. All these `IWantTo[...]` become really confusing, introducing very hard to detect differences won't help at all.

**Comment by danielmarbach** [comment] 2016-02-04 10:56
@timbussmann The benefit of renaming it is that we can obsolete the old one and make a note in the obsoletion message about the behavior breaking change (no longer executed on a background thread)

**Comment by andreasohlund** [comment] 2016-02-04 12:01
>I know we're on the renaming spree but I think IWantToRunWhenEndpointStartAndStops still matches exactly what it does. 

The current one is called `IWantToRunWhenBusStartAndStops`. 

I'm also good with the word endpoint since us supporting multihosting is unlikely

**Comment by timbussmann** [comment] 2016-02-04 12:09
> @timbussmann The benefit of renaming it is that we can obsolete the old one and make a note in the obsoletion message about the behavior breaking change (no longer executed on a background thread)

sounds reasonable :+1: 

My vote goes for IWantToRunWhenEndpointStartAndStops

**Comment by andreasohlund** [comment] 2016-02-04 13:30
>My vote goes for IWantToRunWhenEndpointStartAndStops


@yvesgoeleven are you ok with this for the azure multi host? (or will you go with a IWantToRunWhenHostStartAndStops there? or both?)

**Comment by andreasohlund** [comment] 2016-03-04 09:41
@indualagarsamy do you want to drive this one? (I can help out)

**Comment by indualagarsamy** [comment] 2016-03-08 07:26
@andreasohlund - I'll have a look and ping you if I have any questions.

**Comment by timbussmann** [comment] 2016-03-16 13:14
@indualagarsamy since there wasn't any update on this for a while, would it make sense to create a taskforce to move this issue forward?

**Comment by indualagarsamy** [comment] 2016-03-16 17:56
@timbussmann - I've discussed this issue with @kbaley and will help him get this done done.
We discussed the list of things to be done and that checklist will be updated in the issue description.

**Comment by danielmarbach** [comment] 2016-03-16 19:05
Cool! When we did the grooming today we concluded that this has higher prio
than advanced satellite. The impact here is larger

**Comment by indualagarsamy** [comment] 2016-03-16 19:09
@danielmarbach - makes sense. Are you referring to #3370 ?

**Comment by danielmarbach** [comment] 2016-03-16 19:13
Yep. Sorry stupid email doesn't allow proper linking

**Comment by colin-higgins** [comment] 2016-03-16 19:31
Don't a lot of the acceptance tests rely on `Start` and `Stop` as spies?

**Comment by indualagarsamy** [comment] 2016-03-16 19:40
@colin-higgins - We'll add that to our checklist.

**Comment by kbaley** [comment] 2016-03-16 19:40
Just confirming the work that needs to be done. I'll include this as a checklist in the issue description once it's confirmed:

- Obsolete `IWantToRunWhenBusStartsAndStops`
- Update upgrade guide, [specifically this](http://docs.particular.net/nservicebus/upgrades/5to6#iwanttorunwhenbusstartsandstops-execution)
- Update samples (e.g. http://docs.particular.net/samples/hosting/)
- Move interface to NServiceBus.Host and NServiceBus.Host.AzureCloudService
- Move related acceptance tests to host projects
- Refactor existing acceptance tests that rely on `IWantToRunWhenBusStartsAndStops` for assertions

**Comment by indualagarsamy** [comment] 2016-03-16 19:45
@kbaley - looks good.

**Comment by indualagarsamy** [comment] 2016-03-16 19:46
@kbaley - I'd add relevant issues in the NServiceBus.Host & the NServiceBus.Host.AzureCloudService as well and link it to this one. cc / @SeanFeldman @yvesgoeleven

**Comment by danielmarbach** [comment] 2016-03-16 20:50
@indualagarsamy @kbaley Also don't forget that we talked about renaming the interface and obsoleting the old one. Since this would make it more visible that now blocking operations can occur in there.

**Comment by kbaley** [comment] 2016-03-16 21:12
@danielmarbach Right. Forgot about that. I'll update the checklist.

**Comment by andreasohlund** [comment] 2016-03-16 22:10
@kbaley fyi https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/22, you will need to go on top of that one

**Comment by andreasohlund** [comment] 2016-03-23 08:17
FYI since this touch a fairly public api we decided that this is a blocker for a beta release so this one have high prio

**Comment by andreasohlund** [comment] 2016-03-24 10:38
The NHibernate performance tests are using this feature

https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate.PerformanceTests/Program.cs#L79

I propose we just remove the perf tests from NH since it will be covered by https://github.com/Particular/EndToEnd/issues/3

**Comment by andreasohlund** [comment] 2016-03-29 06:49
Who's working on this taskforce? (@kbaley and @colin-higgins I know that you are working on this can you update the description)

Can we add more people to get this one completed faster? 

Who's working on the azure host?

**Comment by colin-higgins** [comment] 2016-03-29 14:26
The azure host pull request is up and is a copy paste of the windows host changes: https://github.com/Particular/NServiceBus.Host.AzureCloudService/pull/27

**Comment by andreasohlund** [comment] 2016-03-30 06:32
@SimonCropp since you got forces to fix the doco for this one due to the premature merge is there anything items on the POA that are completed?

**Comment by mikeminutillo** [comment] 2016-03-30 06:38
Can the taskforce please link the relevant sub-items from the issue description: 

- https://github.com/Particular/NServiceBus.Host/issues/60
- https://github.com/Particular/NServiceBus.Host.AzureCloudService/issues/24

**Comment by indualagarsamy** [comment] 2016-03-30 18:33
@mikeminutillo - i've updated the issue description with the above 2 links in the checklist (item 4)

**Comment by DavidBoike** [comment] 2016-03-30 20:27
This issue has been identified as a blocker for a limited beta (including only MSMQ/NH) as it affects a very public API. Could someone from the TF please give a status that includes which items in the PoA must be completed before we could send the first email to a potential beta customer?

**Comment by colin-higgins** [comment] 2016-03-30 20:37
This pull request is outstanding for Windows Host, and then needs to be copied to Azure Host:
https://github.com/Particular/NServiceBus.Host/pull/72

Documentation and samples need to be updated and I am unsure of the magnitude.
Anyone with availability to take that on would be welcome.

cc / @kbaley

**Comment by tmasternak** [comment] 2016-03-31 09:12
Can we make sure TF lead is assigned to the issue?

**Comment by bording** [comment] 2016-03-31 18:04
FYI, there is a potential bug described in https://github.com/Particular/NServiceBus.Host/issues/73 that should be considered regarding this.

**Comment by indualagarsamy** [comment] 2016-04-04 00:13
@kbaley @colin-higgins - Can we check this item off from the list? 
`Move interface to NServiceBus.Host and NServiceBus.Host.AzureCloudService` since we have couple of PRs that were merged?

**Comment by distantcam** [comment] 2016-04-04 04:15
I'd like to join this TF to get it done.

**Comment by distantcam** [comment] 2016-04-04 04:21
@bording Is Particular/NServiceBus.Host#73 a blocker for this? Should this taskforce be focused on that issue before this one?

**Comment by indualagarsamy** [comment] 2016-04-04 18:34
@distantcam - The issue you mentioned is an existing problem with the host. While we should fix that, it shouldn't be a blocker for this particular issue. This issue was more focused on, getting these interfaces out of the core and moving it to the hosts. At the moment, all that remains is a WIP PR for doco on these changes. Lets discuss on https://github.com/Particular/NServiceBus.Host/issues/73 to see if it needs to be prioritized.

**Comment by kbaley** [comment] 2016-04-04 21:22
@distantcam The remaining [WIP] PR to work on is: https://github.com/Particular/docs.particular.net/pull/1381. It has the three documents still left to update with a rough outline of what needs to change.

**Closed** 2016-04-06 05:08 UTC
Labels: Project: V6 Launch, State: In Progress, Tag: Breaking Change
