### ISSUE TITLE
Should assembly scanning include other Particular dlls, when specifying a type list to include?

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2572] opened 2014-11-19 18:39 UTC
In the following case:

```c#
NServiceBus.Configure.With(GetAssembliesToIncludeInScan())
.Log4Net()
```
where `GetAssembliesToIncludeInScan` returns an `IEnumerable<Assembly>`, we automatically include NServiceBus core, because it is needed without which the endpoint won't function.

However, does it make sense to also include other Particular assemblies, especially the ServiceControl plugin dlls. Not doing so, forces the user to include the Particular assemblies explicitly.
Shouldn't the plugin dlls be auto included just like the core?

--

Related Desk Case: https://nservicebus.desk.com/agent/case/7811

**Comment by SeanFeldman** [comment] 2015-02-05 20:14
+1 for loading Particular assemblies by default unless user has explicitly configured not to.
Also, could we upon EP start-up show in diagnostics assemblies that were scanned, just like it's done for features?

**Comment by ramonsmits** [comment] 2015-02-05 20:24
Yes, and mark which ones are not scanned (so indirectly excluded).

**Comment by jeffchanwl** [comment] 2015-02-05 21:54
I also agree that Particular assemblies should be included by default unless explicitly excluded.

**Comment by SimonCropp** [comment] 2015-02-05 22:01
so someone else writes an addin extension for SC and follows our model. we would then have an inconsistency in our API that would be very hard for the dev to work out.

The problem here is that "we should always scan Particular dlls" the problem is that we are overusing assembly scanning. It is a very fragile api to use, if we bypass it to "always scan our assemblies" we are effectively saying "yeah that API is too hard for you to use so we wont follow our own API" rather than fixing the root problem. 

The addin API should not rely on assembly scanning and instead be explicitly configured. Then this problem would not exist. Stop trying to hack things to enable the problem to exist.

As for assembly scanning as an API. we should re-evaluate all the things that depend on it and see if they can be done in more intuitive and simple APIs.

**Comment by danielmarbach** [comment] 2015-05-07 12:53
Assembly scanning is revamped as part of https://github.com/Particular/NServiceBus/pull/2670. Closing this one

**Closed by danielmarbach** 2015-05-07 12:53 UTC
Labels: Bug, Needs: Scheduling
