### ISSUE TITLE
Spans and activities on the consumer are not created if the producer does not have OpenTelemetry enabled

### ISSUE THREAD

**Issue by rubencc** [Particular/NServiceBus#6974] opened 2024-03-12 17:57 UTC
#### Description
The activity and span on the consumer are not created if the producer does not have opentelemetry enabled

#### Expected behavior
That spans are generated when receiving a message without taking into account whether the sender also uses opentelemetry or not

#### Actual behavior
When receiving messages from a sender that does not have opentelemetry activated, spans are not generated in nservicebus

**Note:** the traceparentid on received message without opentelemetry is like this (00-839269a4ce6ac99ca9aa75dc6b207531-8531a45b2722fb12-00) when opentelemetry is enable in the producer the traceparentId is ends with "-01"

#### Versions
8.1.6

Please list the version of the relevant packages or applications in which the bug exists.        

### Steps to reproduce

- Enable exporter console with opentelemetry in the consumer.
- Disable opentelemetry in the producer endopoint.
- Send any kind of message from the producer to de consumer.

**Comment by PhilBastian** [comment] 2024-03-13 05:57
Hi @rubencc, are you able to provide us with a code sample that reproduces this issue? We have tried following your reproduction steps but are seeing spans on the receiver.

In our reproduction attempt we had the following code before `endpoint.Start();` in the receiver, but not the sender.
```cs
endpointConfiguration.EnableOpenTelemetry();
var tracerProvider = Sdk.CreateTracerProviderBuilder()
            .AddSource("NServiceBus.Core")
            .AddConsoleExporter()
            .Build();
```

**Comment by mikeminutillo** [comment] 2024-03-13 08:37
@rubencc Under the covers the call to `WithTracing(...)` should be creating a tracer provider. Are you also enabling OpenTelemetry on the endpoint?

```cs
endpointConfiguration.EnableOpenTelemetry();
```

Without that call, NServiceBus will not emit any open telemetry information.

**Comment by rubencc** [comment] 2024-03-13 08:39
Yes, it's enable in the endpoint configuration.

**Comment by mikeminutillo** [comment] 2024-03-13 08:55
Can you share your endpoint configuration and startup code? Are you using the NServiceBus.Extensions.Hosting package?

**Comment by rubencc** [comment] 2024-03-13 11:23
Hi @mikeminutillo @PhilBastian i created a [example repo with some scenarios](https://github.com/rubencc/opentelemetry.scenearios): 

1. Console app producer with opentelemetry.
2. Console app producer without opentelemetry. 
3. Console webapp producer **without opentelemetry.**
4. Console webapp producer with opentelemetry and **without asp instrumentations**. 
5. Console webapp producer with opentelemetry and **with asp instrumentations**. 

If you execute the diferent apps you can see: 

1. Console app producer with opentelemetry  -> The consumer shows the activities. 
2. Console app producer without opentelemetry  -> The consumer shows the activities. 
3. Console webapp producer without opentelemetry  -> The consumer doesn't show any activity.
4. Console webapp producer with opentelemetry and without asp instrumentation -> The consumer doesn't show any activity.
5. Console webapp producer with opentelemetry and with asp instrumentation -> The consumer shows the activities.

My theory is about the traceparentid in message headers:

1. Console app producer with opentelemetry -> traceparentId is setted on publish and **ends with "-01"**.
2. Console app producer without opentelemetry -> traceparentId is not setted on publish. 
3. Console webapp producer without opentelemetry -> traceparentId is setted on publish and  **ends with "-00"**.
4. Console webapp producer with opentelemetry and without asp instrumentation  -> traceparentId is setted on publish and  **ends with "-00"**.
5. Console webapp producer with opentelemetry and with asp instrumentation  -> traceparentId is setted on publish and  **ends with "-01"**.

**Comment by rubencc** [comment] 2024-03-14 08:16
The -00 flag in the traceparent indicates that the message is not sampled. But the consumer has the instrumentation and sampling  enabled.

**Comment by PhilBastian** [comment] 2024-03-15 03:50
Thanks @rubencc for your sample. Using this we were able to replicate the issue that you're encountering.
As you have determined, the -00 flag generated by ASP.NET is what is causing us to not trace downstream messages. We are discussing internally whether this constitutes a bug or expected behaviour, given that upstream activities are classified as parent activities for our tracing purposes.

**Comment by mikeminutillo** [comment] 2024-03-20 08:28
@rubencc We took a look at this and we don't think it is a bug with the NServiceBus implementation.

The default sampler setting in OpenTelemetry looks like this:

```cs
using var traceProvider = Sdk.CreateTracerProviderBuilder()
        .AddSource("NServiceBus.Core")
        .AddConsoleExporter()
        .SetSampler(new ParentBasedSampler(new AlwaysOnSampler())
        .Build();
```

Note the `ParentBasedSampler(AlwaysOnSampler)`.

What this does is sample every `Activity` with no parent or defer the decision about sampling to the parent `Activity` if present. Unfortunately ASP.NET creates an `Activity` which gets picked up by NServiceBus and this `Activity` is not sampled (as you haven't configured OpenTelemetry to sample on the sender). As such, when then message gets to other end, it is not being sampled and the default sampling strategy decides to ignore it.

You can get around this in the receiver by using a non-default sampling strategy like this:

```cs
using var traceProvider = Sdk.CreateTracerProviderBuilder()
        .AddSource("NServiceBus.Core")
        .AddConsoleExporter()
        .SetSampler(
            new ParentBasedSampler(
                rootSampler: new AlwaysOnSampler(),
                remoteParentNotSampled: new AlwaysOnSampler()
            )
        )
        .Build();
```

Adding the `AlwaysOnSampler` for `remoteParentNotSampled` allows OpenTelemetry to override the decision not to sample made by the sender.

You can read more about the built-in samplers in [the OpenTelemetry documentation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#built-in-samplers).

**Comment by mikeminutillo** [comment] 2024-03-20 09:28
And for completeness, [here is the line in ASP.NET that likely creates the activity](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L418).

**Comment by mikeminutillo** [comment] 2024-03-25 00:43
@rubencc As [we do not think this is a bug](https://github.com/Particular/NServiceBus/issues/6974#issuecomment-2009021073) I will be closing this issue. Please let us know if the comment above does not resolve the issue for you and we can re-open it.

**Closed by mikeminutillo** 2024-03-25 00:43 UTC
Labels: Bug

**Comment by rubencc** [comment] 2024-04-03 08:17
Ok. Thanks @mikeminutillo and @PhilBastian!
