### ISSUE TITLE
NServiceBus with ASP.NET Core Services not resolving the correct instance, SignalR HubContext

### ISSUE THREAD

**Issue by kelvinmac** [Particular/NServiceBus#5273] opened 2018-09-22 20:00 UTC
I'm having an issue where if a resolve a IHubContext<T> inside the Handler, I don't seem to be getting the correct instance.

I know because when i invoke a "connected" client, the message doesn't seem to propagate to the end client, no exceptions are thrown either. Is this normal behaviour? It seems the servicecollection being used by NServiceBus is not a reference of the global asp.net servicecollection, which means the IHubContext<T> being resolved is actually a different instance to the actual one being used by asp.net core. What would be a work around for this? 

USING
Asp.net core 2.1 
Latest nugets

Endpoint configuration
```
        var endpointConfiguration = new EndpointConfiguration("my.queue");
        endpointConfiguration.SendFailedMessagesTo("my.error.queue");
        endpointConfiguration.UsePersistence<InMemoryPersistence>();
        endpointConfiguration.UseSerialization<NewtonsoftSerializer>();

        endpointConfiguration.UseContainer<ServicesBuilder>(
            customizations: customizations =>
            {
                customizations.ExistingServices(services);
            });

            endpointConfiguration.EnableInstallers();

            var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
            transport.ConnectionString(connstr);

            var routing = transport.Routing();

            routing.RouteToEndpoint(typeof(Happened).Assembly, "my.other.queue");
            var endpoint = Endpoint.Start(endpointConfiguration).Result;
```

A Handler

```
            public class HappenedHandler : IHandleMessages<Happened>
            {
                    private readonly IHubContext<DataExchangeHub> _hubContext;

                    private readonly IServiceProvider _serviceProvider;
                    private readonly ILogger _logger;

                    public LevelUpdatedHandler(IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                        _logger = _serviceProvider.GetService<ILogger<LevelUpdatedHandler>>();
                        _hubContext = _serviceProvider.GetService<IHubContext<DataExchangeHub>>();
                    }

                    public async Task Handle(LevelUpdated message, IMessageHandlerContext context)
                    {
                            if (DataExchangeHub.ServersConnectedToHub(message.LevelId, _serviceProvider,
                                out var connections))
                            {
                                foreach (var connection in connections)
                                {
                                    try
                                    {
                                        // This event never actually invokes the client and never throws an exception
                                        await _hubContext.Clients.Client(connection.Key).SendAsync("Event_Happened");

                                        _logger.LogInformation(LogEvents.HandlingUpdatedLevelEv,
                                            $"something happened '{connection.Value}'");
                                    }
                                    catch (Exception e)
                                    {
                                        _logger.LogError(LogEvents.HandlingUpdatedLevelEv, e,
                                            $"Couldn't handle a happening '{connection.Value}'");
                                    }
                                }
                            }
                    }
            }
```

**Comment by mauroservienti** [comment] 2018-09-24 12:05
@kelvinmac thanks for raising this.

I noticed a [PR](https://github.com/twenzel/NServiceBus.MSDependencyInjection/pull/2) that seems to be related to the problem you're facing has been recently merged. Can you try and see if the latest version fixes the works as expected?

Since [Microsoft.Extensions.DependencyInjection](https://docs.particular.net/nservicebus/dependency-injection/msdependencyinjection) is an unsupported community package, better to raise an [issue also with them](https://github.com/twenzel/NServiceBus.MSDependencyInjection/issues).

**Comment by mauroservienti** [comment] 2018-09-24 12:10
_As a second though_

To see where the issue is would it be possible for you to try to update your project to use Autofac as a shared DI container? A [sample is available on our doco](https://docs.particular.net/samples/dependency-injection/aspnetcore/#configuring-to-use-shared-di-with-autofac).

**Comment by kelvinmac** [comment] 2018-09-28 13:18
@mauroservienti 
I updated to the latest versions of NServiceBus nugets and upgraded the projects to use Autofac as the service container. This did not see to seem to resolve the issue. To follow up, i'll be raising an issue with Microsoft.

**Comment by mauroservienti** [comment] 2018-09-28 15:00
I can repro the thing, even in a very simple sample sending a message to itself. it seems that when the `IHubContext` is resolved outside the scope of an `HttpRequest` is has no connected clients.

**Comment by mauroservienti** [comment] 2018-09-28 15:43
@kelvinmac if I apply a horrible hack it works 😄 the hack consists in resolving the required `IHubContext<>` as soon as the MVC application starts and expose it as a static property from the `Startup` class.

It doesn't seem to be an NServiceBus related problem, nor connected to the DI container in use.

**Comment by kelvinmac** [comment] 2018-09-30 11:28
I can confirm the hack suggested works, though i'm yet to come across any cons to it. Though it does feel uncomfortable to use. 
Thanks for the suggestion.

**Comment by mauroservienti** [comment] 2018-10-01 07:33
An even better solution could be to use `Lazy<>` to lazily resolve the SignalR Hub. Something like https://gist.github.com/mauroservienti/ee50bb80a9b1eec492102bbbc0924ab5

**Comment by mauroservienti** [comment] 2018-10-01 07:35
@kelvinmac given that it doesn't seem to be a NServiceBus related issue I'm going to close this one. Feel free to reopen if you feel so. Thanks.

**Closed by mauroservienti** 2018-10-01 07:35 UTC
