### ISSUE TITLE
public interface as event with (specific) third party attributes throws exception

### ISSUE THREAD

**Issue by LarsCelie** [Particular/NServiceBus#5398] opened 2019-06-21 10:42 UTC
## Issue
I have a public interface counting as event, with an attribute from `MessagePack`.
When running the Endpoint, an exception is thrown:
```
System.ArgumentException: 'An invalid type was used as a custom attribute constructor argument, field or property.'
```

This only happens for a public interface. a public class works fine.

## Versions

```
    <PackageReference Include="NServiceBus" Version="7.1.9" />
    <PackageReference Include="NServiceBus.MSDependencyInjection" Version="0.1.4" />
    <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="2.2.0" />
    <PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="1.1.2" />
    <PackageReference Include="MessagePack" Version="1.7.3.7" />
```

## Steps to reproduce
Use the following startup code with an IEvent in the same project.
```
        public static async Task Main(string[] args)
        {
            var hostBuilder = new HostBuilder()
                .ConfigureAppConfiguration((hostingConext, configuration) =>
                {
                    configuration.AddEnvironmentVariables();
                })
                .ConfigureServices((hostingContext, services) =>
                {
                    var endpointName = "example-endpoint";
                    var connectionString = "azureServiceBusConnectionString";

                    var endpointConfiguration = new EndpointConfiguration(endpointName);
                    endpointConfiguration.UseContainer<ServicesBuilder>(customizations => customizations.ExistingServices(services));

                    endpointConfiguration
                        .Conventions()
                        .DefiningEventsAs(type =>
                        {
                            return type.Name.EndsWith("Event");
                        });

                    var transportConfig = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
                    transportConfig.ConnectionString(connectionString);

                    Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();
                });

            await hostBuilder.RunConsoleAsync();
        }
```

IEvent.cs:
```
using MessagePack;

namespace NServiceBus.AttributeBug
{
    public interface IEvent
    {
        [Key(0)]
        object Value { get; set; }
    }
}

```

## workaround

In my case, i didn't need this specific event. So I can simply exclude it.
```
endpointConfiguration.AssemblyScanner().ExcludeTypes(typeof(IEvent));
```

**Comment by mikeminutillo** [comment] 2019-06-24 03:45
@LarsCelie Thanks for that. I'm glad to see that you have a workaround. 

We can reproduce the error you are seeing (see #5400). Unfortunately the [CustomAttributeBuilder](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.customattributebuilder.-ctor?view=netframework-4.5.2) in the .NET Standard Library cannot handle nullable properties. 

I believe that the best that we could do is detect the issue and provide a better error message.

**Comment by kevinphelps** [comment] 2020-02-06 21:40
There is an issue with C# 8 Nullable Reference Types also,

**Comment by andreasohlund** [comment] 2020-02-07 07:44
This should be fixed as of `7.2.1` can you test and confirm?

See https://github.com/Particular/NServiceBus/pull/5488

**Comment by kevinphelps** [comment] 2020-02-10 04:07
It's not fixed in version 7.2.1.

**Comment by andreasohlund** [comment] 2020-02-10 07:35
Ah, didn't read properly

>We can reproduce the error you are seeing (see #5400). Unfortunately the CustomAttributeBuilder in the .NET Standard Library cannot handle nullable properties.

That is still an issue, we'll keep this open to make sure we throw a better exception message. Sorry for the confusion

**Comment by bording** [comment] 2020-02-10 21:08
@andreasohlund Looking at this a bit, I'm not sure that throwing a better error message is what we need to do here.

We added a test that we thought reproduced this problem in #5400, and then we made changes in #5488 (which I confirmed were released in 7.2.1) that made the test in #5400 stop throwing the exception, so we thought we had fixed this problem.

It appears that something about the #5400 test didn't fully capture the scenario, because I can see that we're still throwing.

**Comment by kevinphelps** [comment] 2020-02-10 21:23
Any ETA on release?

**Comment by bording** [comment] 2020-02-10 21:29
I believe the fix was intended to be part of 7.2.1, so I suspect we should have a corrected 7.2.2 out soon.

**Comment by kevinphelps** [comment] 2020-02-10 22:06
Thanks!

**Comment by andreasohlund** [comment] 2020-02-11 08:00
@LarsCelie @kevinphelps we have now released v7.2.2 what I have verified fixing this using your repro steps.

I did notice that I couldn't reproduce this using netcore (had to use net472) and also with message pack v2 it didn't reproduce either.

**Comment by kevinphelps** [comment] 2020-02-11 20:40
Thank you. It works for me!

**Comment by bording** [comment] 2020-02-11 20:50
Since we've now confirmed that it's fixed, I'm going to go ahead and close the issue.

**Closed by bording** 2020-02-11 20:50 UTC
