### ISSUE TITLE
When I register a step before a InvokeSaga step if there is no saga it fails.

### ISSUE THREAD

**Issue by pablocastilla** [Particular/NServiceBus#3041] opened 2015-10-27 16:02 UTC
Hi,

I think this should not be the behaviour. If there is no saga this step should be ignored.

What do you think?

Thanks

NSB version: 5.2.3

**Comment by timbussmann** [comment] 2015-10-28 09:12
Hi Pablo,

Could you give us some more details about what you'd like to do and some sample code which reproduces your issue?

**Comment by pablocastilla** [comment] 2015-10-28 10:47
Hi Tim!

Here I have prepare you a simple code.
https://github.com/pablocastilla/InvokeSagaExceptionInNoSagaEndpoint 
The message is sent in the EndpointConfig.cs.

The project has a normal handler, not a saga, with a custom step configured to be inserted before the InvokeSaga.  I think as there is no InvokeSaga step it throws an exception. I propose to ignore  this step if there is no saga, just don't execute it, but don't throw an exception. If you change to, for instance, InvokeHandlers it works.

Ask me if you have any problem or doubt.

**Comment by timbussmann** [comment] 2015-10-28 14:23
Thanks a lot for that sample!

If we don't throw an exception a user may not notice that the behavior he registered isn't executed at all on endpoints which don't use sagas. That could cause severe issues because without an exception, no one is going to notice for a long time in the worst case while with the exception you will notice immediately when starting the endpoint. 

Is there a certain reason you want to register a step explicitly before invoking sagas while not using sagas at all?

**Comment by pablocastilla** [comment] 2015-10-28 14:52
We have a common endpoint configuration for every endpoint, which I think is good. My problem is that now I would need to differentiate between projects (endpoint configs) that contains sagas or not, which can be difficult if you have a lot of projects and want to mix their dlls.

Anyway, I think in this case, not in the others well known steps, not executing the step if you are not invoking a saga is the expected behaviour and not receiving the exception. You choose when to execute it, if you want it to be executed always you can choose InvokeHandlers, but if you want to execute it before calling a saga you want it to be executed ONLY when you call a saga, and never when you call a normal handler.

**Comment by timbussmann** [comment] 2015-10-28 15:30
@pablocastilla I think you can solve your issue without much effort using features. Instead of registering that behavior from the configuration directly, you register it from the feature. Features are capable of defining dependencies which means that your behavior will only be registered if that endpoint has the `Sagas` feature enabled.

your feature could look similar to this:

    public class MyFeature : Feature
    {
        public MyFeature()
        {
            EnableByDefault();
            DependsOn<Sagas>();
        }

        protected override void Setup(FeatureConfigurationContext context)
        {
            context.Pipeline.Register<ConnectionOpenerStep>();
        }
    }

Have a look at the documentation of our features concept [here](http://docs.particular.net/nservicebus/pipeline/features).

**Comment by pablocastilla** [comment] 2015-10-28 15:43
Thanks for the info and for helping!

The problem is that I think this will be executed for every handler, lonely or inside a saga. I need to execute the step only if I am in a saga.

How can I know if I am in a saga with the context variable? Is there a way?

**Comment by timbussmann** [comment] 2015-10-28 17:00
you can check if the message will be handled by a saga using the following code in you behavior:

    context.MessageHandler.Instance is Saga;

please note that this is a low-level API. Have you considered to call whatever logic you want to use in your behavior in the handling of the message directly on the saga instead?

**Comment by pablocastilla** [comment] 2015-10-28 17:08
My problem is structural, I want to open the connection to the saga persistence before the message is handled. I don't know why but sometimes the dtc confirms the msmq part before writting in the saga table (I am under Oracle hell), so I prefer to open the connection and join the distributed transaction before the queues are called. I hope this way it won't fail.

Thanks soooooooooo much for the help Tim.

I will follow your isSaga advice, that way I won't open a connection to the persistence any time I process a message. :)

**Comment by DavidBoike** [comment] 2015-10-28 19:32
@pablocastilla I think if you use `InsertBeforeIfExists(WellKnownStep.InvokeSaga);` instead of `InsertBefore(WellKnownStep.InvokeSaga);` the behavior will act as you expect.

**Comment by timbussmann** [comment] 2015-10-29 11:03
@pablocastilla DTC enlistment should "just work". Be aware that for the same message multiple handlers could be invoked which means that also your behavior will be called multiple times. 

I'm going to close this issue since I think your initial issue has been solved. If you're having DTC issues I highly recommend opening a support ticket so we can have a closer look at this.

**Closed by timbussmann** 2015-10-29 11:03 UTC
