### ISSUE TITLE
AssemblyScan broken Unobtrusive Mode Messages

### ISSUE THREAD

**Issue by valeriob** [Particular/NServiceBus#5124] opened 2018-03-07 14:31 UTC
To reproduce the issue with version 7.0.0-RC1
- Create a project with just messages definitions, and do not reference NServiceBus.Core
- Create a service project that runs nsb and references the previous one
Those types do not get picked up by assembly scanner : 
because it looks like it loads an assembly only if it references NServiceBus.Core

       bool ScanAssembly(Assembly assembly, Dictionary<string, bool> processed)
        {
            if (assembly == null)
                return false;
            if (processed.TryGetValue(assembly.FullName, out var value))
                return value;
            processed[assembly.FullName] = false;

            if (assembly.GetName().Name == CoreAssemblyName)
                processed[assembly.FullName] = true;
            if (ShouldScanDependencies(assembly))
            {
                foreach (var referencedAssemblyName in assembly.GetReferencedAssemblies())
                {
                    var referencedAssembly = GetReferencedAssembly(referencedAssemblyName);
                    var referencesCore = ScanAssembly(referencedAssembly, processed);

                    if (referencesCore)
                    {
                        processed[assembly.FullName] = true;
                        break;
                    }
                }
            }
            return processed[assembly.FullName];
        }

**Comment by bording** [comment] 2018-03-07 16:26
@valeriob We have a sample that demonstrates unobtrusive mode, and it is working properly: https://docs.particular.net/samples/unobtrusive/?version=core_7

What problem are you seeing? Can you provide us with a repro project that demonstrates the problem?

**Comment by valeriob** [comment] 2018-03-07 16:56
Yep i think it's a corner case,
if you check resolved types you will see that the message types are not scanned : 

`        var scannedTypes = endpointConfiguration.GetType().GetField("scannedTypes", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance).GetValue(endpointConfiguration) as List<Type>;
        var myEventType = typeof(Events.MyEvent);
        var doesScannedTypeContains = scannedTypes.Contains(myEventType);`

the side effect is that if we drop a message from production to the dev pc queue to diagnose a problem we do not have headers, so the message type header is not passed and nsb have to look for the right deserialization type on scanned types based on xml tag name, this process fails, and used to work, it's very usefull to debug production issues.

Thanks

**Comment by bording** [comment] 2018-03-07 17:29
@valeriob There was a change in v7 (#4648) so that no unobtrusive messages are included in the scanned types because we load message types dynamically as messages arrive. There were several cases in v6 where unobtrusive messages wouldn't be included in the scanned types, so this was already unreliable.

It looks like this change didn't make it to our upgrade guide, so I'll be sure to update that ASAP.

However, it's still not clear to me what problem this is introducing for you. Were you relying on the scanned types collection in some way? It would be great if you could provide a simple repro project that shows this working in v6 and no longer working in v7. That way we can see exactly what it is you're trying to do, and we'll be able to determine how we can enable the scenario in v7.

**Comment by andreasohlund** [comment] 2018-03-15 08:00
>if we drop a message from production to the dev pc queue to diagnose a problem we do not have headers, so the message type header is not passed

Are you saying that v7 doesn't add the `NServiceBus.EnclosedMessageTypes` header for unobtrusive messages?

**Comment by valeriob** [comment] 2018-03-15 11:12
Actually we are using https://github.com/danielHalan/ServiceBusMQManager to send messages, and it uses nsb 3 or 4, they do not include that header i think

**Comment by andreasohlund** [comment] 2018-03-15 13:46
That sounds weird? (that header has been present since the dawn of time) Could it be that `ServiceBusMQManager` does some kind of raw send?

**Comment by valeriob** [comment] 2018-03-15 13:51
It's possible, i dumped the raw msmq message and it has no headers but the CorrId.
Anyway, it was an usefull tool to quickly diagnose problems in production, see the content of the message in the error queue, copy, paste it into a new command and drop it in a local dev machine, run the app, diagnose the problem, deploy, replay the message :D a very fast workflow

**Comment by andreasohlund** [comment] 2018-03-15 14:01
Agreed, so in essence you are saying that v7 won't be able to process a message that is missing the `NServiceBus.EnclosedMessageTypes` if the endpoint is using unobtrusive messages? (but v6 could)

**Comment by valeriob** [comment] 2018-03-15 14:19
Yes i think so.

**Comment by andreasohlund** [comment] 2018-03-15 14:20
Ok, let me see if I can reproduce this

**Comment by andreasohlund** [comment] 2018-03-15 15:44
What version of v6 did you see this working on?

**Comment by andreasohlund** [comment] 2018-03-15 15:54
One more thing, does the endpoint have a handler for the message that you're trying to process?

**Comment by valeriob** [comment] 2018-03-15 16:20
I'm not sure about the version because i used version 6 for few time (probably 6.0.2 or 6.4.0), and yes, i have an endpoint to process that message.

**Comment by andreasohlund** [comment] 2018-03-16 08:25
I can confirm that [inferring message type from the XML root node](https://github.com/Particular/docs.particular.net/pull/3667) is broken in v7, The workaround is to add the `NServiceBus.EnclosedMessageTypes` header. I will discuss this with the rest of the team and get back to you.

It seems off that https://github.com/danielHalan/ServiceBusMQManager strips the headers when sending though, @danielHalan thoughts?

**Comment by andreasohlund** [comment] 2018-03-16 09:10
@valeriob I've raised a new issue to track the fix for this https://github.com/Particular/NServiceBus/issues/5129

**Comment by andreasohlund** [comment] 2018-03-19 13:20
Fix is tracked by https://github.com/Particular/NServiceBus/issues/5129, closing this

**Closed by andreasohlund** 2018-03-19 13:20 UTC
