### ISSUE TITLE
MSMQ requires error queue configuration for send-only endpoints

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus#4769] opened 2017-05-31 22:29 UTC
## Who's affected
Anyone using the MSMQ transport with send-only endpoints on NServiceBus 6.3.

## Symptoms
After upgrading to 6.3,  users need to configure a error queue unnecessarily.

## Original bug report
This is a change in behavior and has broken the Azure dynamic host, which launches the endpoint as a sendonly endpoint.

**Comment by boblangley** [comment] 2017-05-31 22:30
This line should include a check to see if the endpoint is not configured as a SendOnly endpoint: https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs#L35

**Comment by SeanFeldman** [comment] 2017-05-31 23:08
I've raised a PR again MSMQ transport: https://github.com/Particular/NServiceBus.Transport.Msmq/pull/25

**Comment by andreasohlund** [comment] 2017-06-01 04:53
Would we classify this as a patch?

**Comment by SeanFeldman** [comment] 2017-06-01 04:55
I'd say so. Qualifies at least a [Minor Patch criteria](https://github.com/Particular/PlatformDevelopment/blob/master/guidelines/triage.md#patch-criteria) as azure multi host would require to take the host offline, add an error queue configuration and redeploy. That's quite a workaround 😃

**Comment by andreasohlund** [comment] 2017-06-01 06:56
How can the azure multi host be affected by a msmq bug?

**Comment by yvesgoeleven** [comment] 2017-06-01 09:28
@andreasohlund as discussed on slack, it's probably because msmq is on by default as the host doesn't have a need for a transport

**Comment by bording** [comment] 2017-06-01 17:12
Reopening since we still need to consider a 6.3.x patch.

**Comment by SimonCropp** [comment] 2017-06-07 00:44
wouldnt this always fail at startup? in which case it could never get to production? and if so not a back port

**Comment by bording** [comment] 2017-06-07 01:04
@SimonCropp It's not a backport. It's a fix to a regression introduced in 6.3.0

**Comment by SimonCropp** [comment] 2017-06-07 01:06
@bording ok thanks for the clarification

**Comment by bording** [comment] 2017-06-07 20:38
Fixed by #4784

**Closed by bording** 2017-06-07 20:38 UTC
Labels: Bug
