### ISSUE TITLE
Provide API to configure custom Conversation IDs

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4683] opened 2017-05-09 15:50 UTC
By default, conversation ids are generated by NSB internally but there are some use cases where users want to manually specify a conversation id in order to "attach"/"link" a new message sent from a `IMessageSession` to an existing conversation.

The current approach to do this is by manually setting the proper Header value. This only works when sending messages from a `IMessageSession` as NSB will throw an exception in case you're trying to overwrite an incoming conversation id.

In case the scenario of manually configuring a conversation ID we should provide a better API. One tricky aspect is, that this API is currently not intended to be used from message handlers (as they already have an incoming conversation id)

**Comment by weralabaj** [comment] 2017-09-29 11:05
The current behavior is 

> A custom conversation id can only be set when a new message flow is started (messages sent from IMessageSession). When the header is set in a message handler it would overwrite an existing conversation id and throw instead.

as defined in this issue https://github.com/Particular/NServiceBus/pull/4666.

I'd like to challenge that. I don't see why we should give the priority to the Conversation Id automatically assigned by the framework as opposed to giving priority to the value explicitly assigned by the user. I think that if somebody bothers to manually assign some value to that header, then we can assume they know what they're doing and have a good reason for doing so.

An example of where I hit this challenge is when I have an integration-like scenario, where I can't modify all services to use NSB everywhere, but instead services have pollers that check status in db and generate NSB messages. The process is a flow that I know and understand, but from NSB and SI visualization perspective, the flow is fragmented, couple of messages here and there are correlated, but one flow comes in 5 pieces. I'd like to explicitly assign the "natural" conversation id that I have (i.e. in this case - order id), but can't do so, as some of the messages in the flow already have that header value set by NSB.

Of course, I could use some custom header to correlate my flows, instead of Conversation Id header, but then I won't benefit from SI visualizations.

Outstanding questions:
- Is Correlation Id used anywhere else, or just for SI visualizations?
   - If only for SI visualizations, then as a user, I'd expect to be able to modify that header as I see fit => I think we should modify that behavior.
   - If for other reasons too, then seems like we're potentially violating SRP (?)

/cc: @Particular/nservicebus-maintainers

**Comment by timbussmann** [comment] 2017-10-02 07:12
> An example of where I hit this challenge is when I have an integration-like scenario, where I can't modify all services to use NSB everywhere, but instead services have pollers that check status in db and generate NSB messages. 

that scenario makes sense but I wonder: how do you know the correct correlation id on these endpoints to set on the message?

**Comment by andreasohlund** [comment] 2018-08-20 11:38
Duplicate of https://github.com/Particular/NServiceBus/issues/4683

**Closed by andreasohlund** 2018-08-20 11:38 UTC
