### ISSUE TITLE
Non writable saga properties are not deserialized properly

### ISSUE THREAD

**Issue by dikoga** [Particular/NServiceBus#5103] opened 2018-01-10 16:23 UTC
Hi all,

I ran into an issue while testing the basic Saga samples available in the docs. Instead, download the source file an ran it, I created everything myself.

The Saga Data was not being loaded no matter what persistence mode (tested with InMemory, Learning, and SQL) it is being used even though it is being persisted correctly. If more than one message with the same id is sent, only one is kept persisted (it doesn't duplicate) and up-to-date (last one).

There is no error in the console as well saying the saga was not found for example.

I use all the time VS to create my classes and this is how my saga data looks like:

public class LeadSagaData : ContainSagaData
{
    public string LeadId { get; internal set; }
    public DateTime Timestamp { get; internal set; }
    public string Test { get; internal set; }
}

While talking to @ramonsmits, he noticed the internal access modifier for the set. Setting the access modifier to public fixes the issues and works perfectly!

Creating this issue because IMO it should either require a public setter or give an error in the console.  Right?

Thanks!

**Comment by dikoga** [comment] 2018-01-10 16:24
By the way, @ramonsmits asked to open it in the main repo, because it happens with more than one persister.

**Comment by andreasohlund** [comment] 2018-01-11 07:13
@Particular/nservicebus-maintainers seems reasonable to me to require saga data properties to be writable?

**Comment by timbussmann** [comment] 2018-01-11 08:28
yeah seems reasonable to me to add some verification that properties (or only the correlation property?) needs to be writeable.

**Comment by andreasohlund** [comment] 2018-01-12 13:14
@dikoga I verified this on the learning persister and the saga correlation work but the hydrated data is incorrect. Is that what you are seeing as well? (If I interpret your statement "it doesn't duplicate", it seems so)

Given that the correlation property is the only one the NServiceBus "owns" we will make sure that the property is writable and throw if not.

We will not check the other properties since they they can technically be "computed properties" that the user creates for convenience and we don't want to block that use case.

Does this make sense?

**Comment by andreasohlund** [comment] 2018-01-22 08:08
@dikoga I propose that we change the title of the issue to "Non writable saga properties are not deserialized properly" or similar since that actual saga correlation seems to work based on my testing?

**Comment by dikoga** [comment] 2018-01-22 16:53
Hi all, sorry for the delay...

Yes, it makes senses all the responses!!!

I went ahead and changed the title.

Thanks!!!

**Comment by andreasohlund** [comment] 2018-01-25 13:00
@dikoga sorry for the back and forth, talked to the core maintainers yesterday and we're not seeing this as a bug but more as an opportunity to improve the way we make users aware of non-writable properties to make sure that they where not made non-writable by mistake. 

Examples could be throwing if the correlation id is non writable and perhaps a Roslyn analyzer to warn in general if a saga has non writables.

I propose to close this issue and I will raise a new issue to track the above, does that make sense to you?

**Comment by dikoga** [comment] 2018-01-25 16:00
Well, not only issues that raise an exception are bugs. Right?

If you agree with me, I'd say this is a bug because the saga is not working as expected. As I understand, the writable correlation id is a requirement that is not being taken care of.

**Comment by andreasohlund** [comment] 2018-01-26 07:56
>I'd say this is a bug because the saga is not working as expected. As I understand, the writable correlation id is a requirement that is not being taken care of.

Based on my testing the saga was actually working, correlation worked as expected, that's why only one instance was created in the "data store". What didn't work was populating the read only properties but we propose to consider that "by design" since they where not writable? 

Again we will look at doing a better job at making users aware of this but as far as we can tell the behavior of the infrastructure was correct?

**Comment by dikoga** [comment] 2018-01-26 12:30
Andreas, I stated this since the beginning:

The Saga Data was not being loaded no matter what persistence mode (tested with InMemory, Learning, and SQL) it is being used even though it is being persisted correctly.

And this is still an issue. 
So, As long as you guys fix it or require or actually show as an error, sounds perfectly good. It just doesn’t sound to me a bad design thing, I would say that set it to internal could be consider a good design for some cases instead.

Koga, Diego
----------------------------

**Comment by andreasohlund** [comment] 2018-01-26 13:02
>The Saga Data was not being loaded no matter what persistence mode (tested with InMemory, Learning, and SQL) it is being used even though it is being persisted correctly.

Is seems like we're close enough to agreeing. Data was stored and loaded but not just accessible to the saga handlers since the property couldn't be written to. If you have a few writable properties as well they would work as expected. I will raise a "Make users aware of no writable saga properties to make sure they where not made read only by mistake" issue 👍 

Thanks for the input, we'll keep you in the loop!

**Comment by andreasohlund** [comment] 2018-02-02 07:51
Replaced by https://github.com/Particular/NServiceBus/issues/5115

**Closed by andreasohlund** 2018-02-02 07:51 UTC
