### ISSUE TITLE
Multiple instances of IProvideConfiguration for the same configuration section

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#3649] opened 2016-03-30 19:07 UTC
Core: v5

The issue https://github.com/Particular/NServiceBus.Azure/issues/278 has surfaced another issue in the core. When multiple instances of `IProvideConfiguration` for the same configuration section are found, only the first one is taken into consideration and others are ignored.

Should there be a different behaviour to let users know that there might be a potential issue ([example](https://github.com/Particular/NServiceBus.Azure/issues/278))?

**Comment by SeanFeldman** [comment] 2016-03-30 19:08
@Particular/nservicebus-maintainers thoughts?

**Comment by timbussmann** [comment] 2016-03-31 07:44
@SeanFeldman Since we're aiming to obsolete the config sections, I think this will also remove `IProvideConfiguration` if I see that correctly. Given the usage of Code First Configuration APIs, would the issue still be relevant (e.g. calling the same configuration multiple times)?

**Comment by SeanFeldman** [comment] 2016-03-31 22:11
This was more of a concern for core v5/NSB.ASB v6. In the next version of the transport `IProvideConfiguration` is not used. Since there is a workaround, we can mark this (and [associated transport GH issue](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/166)) as `Won't fix`.

**Comment by timbussmann** [comment] 2016-04-01 11:28
@SeanFeldman is this something we should add to the docs before closing this issue?

**Comment by SeanFeldman** [comment] 2016-04-03 18:35
Good idea @timbussmann 
I can add a note to the [doco here](http://docs.particular.net/nservicebus/hosting/custom-configuration-providers#overriding-app-config-section) if there are no other suggestions.

**Comment by SeanFeldman** [comment] 2016-04-04 22:57
doco PR https://github.com/Particular/docs.particular.net/pull/1383 created.
Closing this issue.

**Comment by SeanFeldman** [comment] 2016-04-05 02:05
Documentation change rejected, re-opening this issue.

**Comment by timbussmann** [comment] 2016-04-05 09:24
@indualagarsamy @SimonCropp since you were against documenting this behavior because "it's a bug", why do you consider this as a bug? What would the expected behavior be when using multiple instances for the same configuration? I'd say everything that does into the direction of "merging configuration settings" is a feature and not a bug.

**Comment by SimonCropp** [comment] 2016-04-05 09:28
It should throw an exception

**Comment by indualagarsamy** [comment] 2016-04-08 16:39
@timbussmann - I was thinking the exact same thing what @SimonCropp suggested. 
For example, if we have 2 classes that implement, `IConfigureThisEndpoint` in the host, there will be an exception.

**Comment by timbussmann** [comment] 2016-10-12 07:38
closing the discussion, we raised a bug here: #4214

**Closed by timbussmann** 2016-10-12 07:38 UTC
Labels: Discussion
