### ISSUE TITLE
Stop Subscriptions versioning based on assembly version

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1394] opened 2013-08-06 09:32 UTC
### Customer communication

We should tell users that we're changing [how subscription versioning is working](http://docs.particular.net/nservicebus/messaging/publish-subscribe/configuration#versioning-subscriptions) (or how it's not always, to be accurate) to make it consistent across all of our transports by standardizing how it's done.

### Impact assessment

**Existing customers**: customers using transport that did take assembly version into consideration will be impacted. [Affected persisters](https://github.com/Particular/NServiceBus/issues/2778#issuecomment-121707388) are:
- ASP
- NHibernate 
- MSMQ
- [InMemory](https://github.com/Particular/NServiceBus/issues/2778)
- RavenDB

**New customers**: no impact

## Original

As defined here http://www.particular.net/articles/publish-subscribe-configuration

> In NServiceBus V3.0 and onwards subscriptions for types with the same Major version are considered compliant. This means that a subscription for MyEvent 1.1.0 will be considered valid for MyEvent 1.X.Y as well.

However some users of NServiceBus dont control their versioning scheme. For example some are forced into a YYYY.MM.DD.Build version number.

So for these people it would be helpful to be able to disable the version incompat check. 

this is a simpler alternative to #1035

**Comment by SimonCropp** [comment] 2015-02-04 09:02
@andreasohlund so i waded into this code and got sucked down the rabbit hole.  want to pair on this ?

**Comment by johnsimons** [comment] 2015-02-04 09:12
Where u getting stuck @simoncropp ?

**Comment by danielmarbach** [comment] 2016-02-12 09:42
The plan is to remove the versioning completely, description updated.

**Comment by bkhanal** [comment] 2016-05-02 19:35
Did this feature make it in V5? We have a nuget repo that builds the assembly version and the subscriber version gets out of date with the publisher dll's. (Publisher is referenced internally in the project) and nuget package is build through TC. Ideally, we can move contracts to its own repo and make it work, but if its possible with some configuration I would like to swtich this feature off. 

Any updates on this feature?

**Comment by andreasohlund** [comment] 2016-05-03 07:35
@bkhanal sorry, this feature didn't make it into v6, what subscription storage are you using? (perhaps we can find a workaround for you)

**Comment by bkhanal** [comment] 2016-05-03 16:06
@andreasohlund, we will probably put nugget to sync with major version to get this working for now. We are using SQL subscription storage.

**Comment by timbussmann** [comment] 2016-09-09 09:29
To me, it sounds like the following statement captures the use case behind this feature request:

> However some users of NServiceBus dont control their versioning scheme. For example some are forced into a YYYY.MM.DD.Build version number. So for these people it would be helpful to be able to disable the version incompat check.

As discussed with @danielmarbach we think the current guideline is to force users to use semver versioning when using multiple assembly versions and close this issue. We could raise a new issue for the quoted use case as a new feature request if someone thinks this adds great value? Thoughts? /cc @Particular/nservicebus-maintainers @SimonCropp

**Comment by andreasohlund** [comment] 2016-09-09 09:37
Users not aware of this will get silently unsubscribed when they release a new version, practically this would mean message loss?

If we agree on that I'd say this is something we need to fix

**Comment by timbussmann** [comment] 2016-09-09 12:41
from what I read, the changed behavior is, that subscriptions now are compatible to older versions as long  they are on the same major? So the message loss scenario would exist already before? Maybe I'm just missing something from the issues description.

**Comment by jbogard** [comment] 2016-09-09 14:30
So what we do is turn assembly versioning off for message assemblies, making it 0.0.0.0. If it's a breaking change to a message, we make a new message, and decide ourselves when/how to turn the previous version off.

I'm not entirely sure SemVer applies to messages in any case.

**Comment by andreasohlund** [comment] 2016-09-13 10:36
>from what I read, the changed behavior is, that subscriptions now are compatible to older versions as long they are on the same major

Not sure when we added this but this behavior (major must match) has been there since at least v3

https://github.com/Particular/NServiceBus/blob/support-3.3/src/nhibernate/Subscriptions/NServiceBus.Unicast.Subscriptions.NHibernate/SubscriptionStorage.cs#L72

https://github.com/Particular/NServiceBus/blob/support-3.3/src/unicast/NServiceBus.Unicast.Subscriptions/MessageType.cs#L96

>So the message loss scenario would exist already before?

Correct this has "always" been there. But still this is message loss so we should fix it. 

@timbussmann does this make sense? ( if yes we should put the bug label back on)

**Comment by timbussmann** [comment] 2016-09-13 11:55
I'm a bit on the fence about labeling it as a bug, since it seems to work as documented ;) It seems to be a flawed design, so changing that sounds more like a feature to me. But I agree that the message loss scenario is bad and should be changed, if it helps to label it as bug I don't have any objections (but since it's labeled for v7, I don't see the benefit in that).

**Comment by brunobertechini** [comment] 2016-09-24 16:25
I just put a comment on another issue: #2778 . Found that before this one :) Sorry.

And Im quoting it here:

My problem is the same but the origin is caused by a developing design time:

We have different solutions per each microservice.

Microservice BLUE has its contracts and its solution is being built using GitVersion (which means my source code does not contain AssemblyVersionInfo thus -> v0.0.0.0 when running inside Visual Studio).

Microservice RED has referenced the Nuget generated package by BLUEs CI build, different version.

Im using Azure Storage Queue and this is causing me trouble to debug/develop in Visual Studio since my BLUE microservice can't publish messages anymore because the sucscription is made against a different asembly version.

NServiceBus 5.2.16. Is this treated differently in NSB 6 ? Should I move on since this is a brand-new project (green field) ?

What other alternatives do I have besides change my Build/Deploy/CI to consistent versioning. Even this is kind of hard because Azure Storate Queue subscriptions need the FULL version not the major only as stated by documentation

Thoughts?

Bruno

**Comment by brunobertechini** [comment] 2016-09-24 16:26
Should I use one repo specific for Message assemblies and versioning it consistently througout all my microservices?

This is a little bit of overhead in design time but if I dont have any other solution I will stick with it.

What about NSB6 ? Was this fixed/changed ? Since this is a green field project I can use NSB6.

Bruno

**Comment by timbussmann** [comment] 2016-09-26 08:05
@brunobertechini the current behavior hasn't been changed in v6, it should behave the same as in v5. If azure storage persistence doesn't respect the described versioning behavior, this should be considered a bug then (/cc @Particular/azure-storage-persistence-maintainers ).

> Should I use one repo specific for Message assemblies and versioning it consistently througout all my microservices?

Extracting message contracts into dedicated assemblies with a more fixed versioning seems like the safest approach in your scenario.

**Comment by timbussmann** [comment] 2016-09-28 13:41
docs PR raised by andreas here: https://github.com/Particular/docs.particular.net/pull/1960

**Comment by andreasohlund** [comment] 2016-09-29 13:00
This has been patched in 6.0.0-RC3. Patches for v5 is coming up as well see https://github.com/Particular/NServiceBus/pull/4177

**Comment by brunobertechini** [comment] 2016-09-29 15:46
Thanks a lot. Im currently using 6.0.0-RC2.

Waiting for RC3 :)

Bruno

**Comment by brunobertechini** [comment] 2016-09-29 15:49
Sorry, My bad...Just saw RC3 is already available :)

Bruno

**Comment by andreasohlund** [comment] 2016-09-29 19:25
>Does it have same patch for Azure Storage Queues/SQL(NHibernate) Persistence ?

They are coming in the very near future. What persister are U currently using?

**Comment by brunobertechini** [comment] 2016-10-01 00:33
Currently using Nhibernate

**Comment by andreasohlund** [comment] 2016-10-01 06:37
I think the core fix actually fixed NHibernate as well since NH uses the equality operator `MessageType`  provided by the core , @Particular/nhibernate-persistence-maintainers can you confirm?

In short: I think Core RC3 + latest NHibernate RC would do the trick

**Comment by MarcinHoppe** [comment] 2016-10-03 06:42
@andreasohlund You are right about NHibernate, it should work fine with Core RC3 when it comes to this particular issue.

**Comment by andreasohlund** [comment] 2016-10-05 14:44
[5.2.17 was released today](https://github.com/Particular/NServiceBus/releases/tag/5.2.17 ) and that fixes this for:

* NHibernate (since NH uses the core `MessageType` class)
* MSMQ
* InMemory

Still waiting for patches to ASP and RavenDB. Will report back here once out

**Comment by Scooletz** [comment] 2016-10-06 11:43
`NServiceBus.Azure 6.2.6` is on nuget.

**Comment by Scooletz** [comment] 2016-10-06 12:20
Azure Storage Persistence package `NServiceBus.Persistence.AzureStorage 1.0.0-rc0003` solving this issue is on nuget.

**Comment by andreasohlund** [comment] 2016-10-10 13:34
Reminder of the work for RavenDB is tracked here:

https://github.com/Particular/NServiceBus.RavenDB/issues/286


Reminder of work for ASP is tracked here:

https://github.com/Particular/NServiceBus.Persistence.AzureStorage/pull/104

Closing this one

**Closed by andreasohlund** 2016-10-10 13:34 UTC
Labels: Bug
