### ISSUE TITLE
Deprecate HandleCurrentMessageLater

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4110] opened 2016-09-01 10:43 UTC
Since we now have both the ability to defer messages and also a more powerfull api for retry policies

See #1705 for full context

**Comment by timbussmann** [comment] 2016-09-05 07:08
:+1:

**Comment by indualagarsamy** [comment] 2016-10-20 20:52
The current obsolete should point the user to Defer / Delayed retries and not to IMessageHandlerContext : IMessageProcessingContext

https://github.com/Particular/NServiceBus/blob/d462080b0efa6609f0f92d4e192d760142ac47c2/src/NServiceBus.Core/obsoletes.cs#L2165-L2168

**Comment by timbussmann** [comment] 2017-09-28 09:25
this should go into v7 unless we discover that this breaking change may break important use cases without providing usable workarounds. This decision has been RFC'ed to all particular engineers. Note that the docs already state that this API will be removed in v7 for quite a while: https://docs.particular.net/nservicebus/messaging/delayed-delivery?version=core_7#delaying-messages-using-handlecurrentmessagelater

**Comment by danielmarbach** [comment] 2017-09-28 09:38
Although I don't exactly follow the why it has to be done now and can't be delayed to next major I'm 👍 for the change since the API is really confusing

**Comment by timbussmann** [comment] 2017-09-28 09:41
@danielmarbach we figured out that this was intended to be removed in v7 but felt beneath the cracks again.  You're correct that this is not a must have but we agreed that this is a seldom used API which lots of code underneath which we'd like to get rid of if possible. We had the impression this wouldn't introduce much migration effort, but that's why we raised the RFC.

**Comment by timbussmann** [comment] 2017-09-29 15:18
RFC ended with no objections. This API is going to be deprecated in v7 then.

**Comment by timbussmann** [comment] 2017-10-03 11:42
closing this as fixed by #4991 (docs PR is merged as well).

**Closed by timbussmann** 2017-10-03 11:42 UTC
Labels: Breaking change
