### ISSUE TITLE
Add startup check to detect handlers using IEndpointInstance and IMessageSession

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3779] opened 2016-05-26 09:53 UTC
To prevent users from wrongly using IEndpointInstance and IMessageSession on their handlers we should check on startup and throw an exception if any handler has a ctor/property dependency in said types. The exception should tell them to use the handler context instead.

**Comment by boblangley** [comment] 2016-05-26 12:47
@Particular/tf-v6-launch-plat-dev The task force met and agreed this is important for V6 launch.

**Comment by indualagarsamy** [comment] 2016-05-26 18:03
@andreasohlund - how is this issue different from the one I raised?
https://github.com/Particular/NServiceBus/issues/3749

**Comment by andreasohlund** [comment] 2016-05-26 18:33
That felt more like a discussion and I see this as one of the potential actions?

**Comment by indualagarsamy** [comment] 2016-05-26 18:42
@andreasohlund - The original issue has more context. You can add this as the Proposed Solution to that issue. Without that, there is no proper context.

**Comment by andreasohlund** [comment] 2016-05-26 18:45
Good point, I've added a link in the description of #3749

**Comment by indualagarsamy** [comment] 2016-05-26 19:06
@andreasohlund - why not add this issue description as the proposed solution in #3749? Do you see other potential solutions to #3749 besides this one, where you could in the future close this one as not feasible? Not sure why we need this issue, if we think that this is the way to go in order to solve #3749. This issue seems like a duplicate.

**Comment by ppittle** [comment] 2016-05-26 23:14
@andreasohlund, throwing a run-time exception might not be the optimal solution in this case.  Checking at run-time will incur a (albeit small) performance penalty.  But more importantly it defers providing uses with feed-back until run-time.

For cases like this, it would be nice to give a compilation error.  With [Roslyn Code Analyzers](https://msdn.microsoft.com/magazine/dn879356) you should be able to write a rule that captures this scenario and provides users faster feedback.

Might not work in all scenarios (ie old versions of VS / .net framework), but thought I'd throw it out there.

**Comment by timbussmann** [comment] 2016-05-27 07:09
@ppittle we also discussed Roslyn Analyzers and we think they would be a great tool to avoid Runtime exceptions. It's all about effort/value and this issue aims at "finding most mistakes with the least possible effort" while a Roslyn Anaylzer will mostly add more "comfort" by providing compile time errors. A Roslyn Analyzer should be able to find more "invalid" usages of `IMessageSession` but it also can't provide a 100% detection rate. The good thing is that we can always provide a Roslyn Analyzer at a later stage while still providing some built-in mechanisms to avoid most-common mistakes.

**Comment by andreasohlund** [comment] 2016-05-27 07:13
> Checking at run-time will incur a (albeit small) performance penalty

Agreed, but this will only happen once at startup so I think this is something that would be insignificant since we already to a fair amount of reflection already.

**Comment by andreasohlund** [comment] 2016-05-27 07:16
@indualagarsamy I created this since this is the actionable item that was decided on the call on Wednesday. I'd say we keep the other as the parent issue until we agreed on the full plan of attack (async local, roslyn analyzer, guidance etc). 

This way we can get this into the next beta.

Does this make any sense?

**Comment by indualagarsamy** [comment] 2016-06-01 19:23
Discussed this with @SimonCropp and @SeanFeldman who also think that this issue is a duplicate of https://github.com/Particular/NServiceBus/issues/3749. Closing this issue and will move the relevant comments over to https://github.com/Particular/NServiceBus/issues/3749

**Closed by indualagarsamy** 2016-06-01 19:23 UTC
Labels: Project: V6 Launch
