### ISSUE TITLE
init.ps1 freezing with VS2015

### ISSUE THREAD

**Issue by xmakina** [Particular/NServiceBus#4235] opened 2016-10-20 14:17 UTC
Hello,

We recently started upgrading our team to VS2015 and seem to have hit a problem with NServiceBus. If we install NServiceBus through NuGet, it includes the file NServiceBus.5.*\tools\init.ps1. This file seems to bring visual studio to a halt, something which has been document on the NuGet repo here https://github.com/NuGet/Home/issues/2175. We are having the same success as https://github.com/NuGet/Home/issues/2175#issuecomment-202776570 if we delete the init.ps1

Is this file essential? Is there any way to mitigate against the VS2015 bug?

Thanks

**Comment by danielmarbach** [comment] 2016-10-21 06:44
@gbiellem would you be able to help us out here?

**Comment by gbiellem** [comment] 2016-10-24 00:30
@xmakina 

Can you provide the output from the following PowerShell commands run from with the VS package manager console:

*   `$PSVersionTable` 
*   `Get-module -All`
*   `Get-ExecutionPolicy -List`

Also is there any console output after `Executing script file .......NServiceBus.5.*\tools\init.ps1....`

Apologies for all questions but ideally i'd like to repro so I can test some possible workarounds.

**Comment by andreasohlund** [comment] 2016-11-01 08:02
@xmakina do you still have this issue?

**Comment by xmakina** [comment] 2016-11-01 09:53
![image](https://cloud.githubusercontent.com/assets/1357791/19885876/f5a91d48-a018-11e6-83eb-b87a6546ba3f.png)

@gbiellem As requested. When I ran the final init.ps1 command there was no output to the console.

@andreasohlund sorry for the delay

**Comment by gbiellem** [comment] 2016-11-02 01:23
Thanks @xmakina  

> When I ran the final init.ps1 command there was no output to the console.

Unfortunately running the init.ps1 that way isn't the same as a what Nuget is doing.  It passes in four params which are checked within the script. Without those params it'll bypass most of the code.

@danielmarbach @andreasohlund At this stage I've not been able to repo a hang however I did notice one thing that is off with the `init.ps1`.   The test to see if the module is already loaded is broken.  The if statement looks to see if `Get-Module NServiceBus.PowerShell` returns something but that is the wrong module name  It should be testing for `NServiceBus.PowerShell.Development`. 
The result is the module is being loaded multiple times - @xmakina's output above shows this

**Comment by danielmarbach** [comment] 2016-11-02 07:26
@gbiellem would you be able to update this? Ok if I assign this issue to you?

**Comment by gbiellem** [comment] 2016-11-02 07:34
No problem @danielmarbach, I was planning on raising a PR for that and anything else I find while trying to repro this.

**Comment by andreasohlund** [comment] 2016-11-02 08:45
Note that init.ps1 will be gone in 6.1 https://github.com/Particular/NServiceBus/pull/4262/files

**Comment by gbiellem** [comment] 2016-11-02 11:05
@andreasohlund so does this mean there is no point continuing on this since it's going to be removed?  Also what happens to the development PS module? I'm not arguing to keep it just wanted to be across what the plan is here

**Comment by andreasohlund** [comment] 2016-11-02 11:12
>so does this mean there is no point continuing on this since it's going to be removed? 

I'd say we can skip this. cc @indualagarsamy 

>Also what happens to the development PS module?

Pretty sure it was deprecated but can't find any notes about this in any upgrade guide?

**Comment by xmakina** [comment] 2016-11-02 11:13
@gbiellem @andreasohlund Good to know, but we have no plans (or the resources) to upgrade to 6 and this is an issue for us at the moment. If I'm remembering right, the move from 5 to 6 is quite substantial

**Comment by bording** [comment] 2016-11-02 16:21
@xmakina What version of Visual Studio 2015 are you running, have you installed Update 3 yet?

Looking at the NuGet version, it looks like you're not running 3.5 RTM yet, which is 3.5.0.1996. Can you try the latest and see if that makes any difference?

When you're running into this problem, how are you installing the package? Are you using the Manage NuGet Packages UI, or are you using the Package Manager Console?

Can you try installing the package from the Package Manager Console, and show us the output from the window when you do that?

**Comment by gbiellem** [comment] 2016-11-08 03:25
@xmakina

Before you do the test @bording outlined can you also turn on PowerShell tracing.  This should give us an idea where it's hanging.   To turn on tracing in the  Package manager Console run the following:
`Set-PSDebug -Trace 2`

You can turn it off again using `Set-PSDebug -Trace 0` or just close Visual Studio as it's not a persistent setting

**Comment by xmakina** [comment] 2016-11-09 10:17
@bording 

I am using VS2015 Pro With Update 3 and NuGet 3.5.0.1996 (although it only shows 3.5.0 on the page)
![vs version](https://cloud.githubusercontent.com/assets/1357791/20135020/967e97aa-a665-11e6-8cec-5a0237c4f8dc.jpg)

When I ran into this problem it locks Visual Studio when loading the solution (see screen print below), note this is when opening the solution, I couldn’t get as far as compiling. I thought it might be doing something resource heavy so I left if overnight, next day it was exactly the same, so had to kill VS on task manager. I’ve done this on many occasions, whilst trying to diagnose the problem.
![vs folders](https://cloud.githubusercontent.com/assets/1357791/20135042/ad63cb66-a665-11e6-8a54-9b9d549b6907.jpg)

When I deleted the init.ps1 files from the NuGet packages in the solution loads and compiles perfectly.

Once I have loaded and compiled correctly, I can put the init.ps1 files back and it still works, so it’s tricky to reproduce once you have it working.

@gbiellem 
Unfortunately, the package manager logging doesn’t come up with anything because everything in VS locks up when this occurs – ie no logs output prior to locking.

**Comment by andreasohlund** [comment] 2016-11-09 10:24
Perhaps try to start with a blank init.ps1 and add the lines back one by one until it hangs?

**Comment by timbussmann** [comment] 2016-11-17 10:12
so we assume that this issue should be fixed by the changes proposed in https://github.com/Particular/NServiceBus/pull/4280. Is there a way we can verify this before upgrading to 6.1? As far as I understand, it should be possible to take the script from the the PR and replace the currently deployed one and then check whether that works? @gbiellem

**Comment by gbiellem** [comment] 2016-11-17 10:43
@timbussmann we can't assume it's fixed by the script since we haven't been able to reproduce it - At best we've gone with a hunch here and pushed most of it into a background job. 

> As far as I understand, it should be possible to take the script from the the PR and replace the currently deployed one and then check whether that works

👍 Yep the init script has nothing in it which is version specific

**Comment by timbussmann** [comment] 2016-11-17 12:15
@gbiellem but maybe @xmakina would be able to pick up the file and see whether it solves the described problems?

**Comment by timbussmann** [comment] 2016-11-22 08:34
as we can't reproduce the originally raised issue, we just have to assume that our changes made in #4280 will solve this problem. #4280 will be part of 6.1, if the problem continues to exist, please reopen the issue @xmakina . If you want to test ahead of the release, we provide 6.1 unstable packages on our myget feed here: https://www.myget.org/feed/particular/package/nuget/NServiceBus

Thanks for raising this issue! 👍

**Closed by timbussmann** 2016-11-22 08:34 UTC
