### ISSUE TITLE
MSMQ configuration allows snapshot isolation to be selected

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4237] opened 2016-10-20 17:47 UTC
Configuration MSMQ to use snapshot isolation level allows the endpoint to start but results in a transaction cannot be promoted exception when messages are received *and* accessing a DTC resource like RavenDB or MSSQL.

```
endpointConfiguration
    .UseTransport<MsmqTransport>();
    .Transactions(TransportTransactionMode.TransactionScope)
    .TransactionScopeOptions(isolationLevel:IsolationLevel.Snapshot);
```

I propose to only allow to start the endpoint if a supported transaction isolation level is specified.

Exception message:

> NServiceBus.ReceiveWithNativeTransaction|MSMQ receive operation failedTransactions with IsolationLevel Snapshot cannot be promoted.

**Comment by timbussmann** [comment] 2016-10-21 14:51
is it safe to assume that MSMQ never supports Snapshop isolation level? Are there other unsupported levels?

If we're trying to catch invalid configurations, we should also consider throwing an exception when configuring `TransactionScopeOptions` without using `Transactions(TransportTransactionMode.TransactionScope)`?

**Comment by ramonsmits** [comment] 2016-10-21 20:00
@bording I updated the description. I also forgot to mention that you will need to do DB IO so that the transaction will get promoted.

**Comment by bording** [comment] 2016-10-21 21:27
@ramonsmits Ah, so the problem isn't actually the Snapshot isolation level itself, it's that you can't use it and DTC together.

In that case, maybe we could check if DTC is enabled, and then prevent the usage of Snapshot?

**Comment by andreasohlund** [comment] 2016-10-22 08:52
I've tested the others and `Snapshot` is the only one that fails.

```
        IsolationLevel.Chaos == OK
        IsolationLevel.Snapshot == FAIL
        IsolationLevel.ReadCommitted == OK
        IsolationLevel.ReadUncommitted == OK
        IsolationLevel.RepeatableRead == OK
        IsolationLevel.Serializable == OK
        IsolationLevel.Unspecified == OK 
```

**Comment by andreasohlund** [comment] 2016-10-22 08:54
In the above test I just used an empty handler since msmq promotes to DTC right away:

http://stackoverflow.com/questions/12462321/why-is-this-simple-msmq-transaction-escalated-to-dtc

**Comment by ramonsmits** [comment] 2016-10-22 10:28
@bording Isn't reason to use the transaction scope here is because of DTC?

**Comment by andreasohlund** [comment] 2016-10-25 18:29
Msmq will always escalate to dtc regardless if another resource manager is involved:

http://stackoverflow.com/questions/12462321/why-is-this-simple-msmq-transaction-escalated-to-dtc

**Comment by bording** [comment] 2016-10-25 21:15
In that case, it should be fairly easy to add a startup check that makes sure that TransactionScope and Snapshot aren't used at the same time.

A runtime failure at startup seems preferable over a runtime failure the first time a message is received.

**Comment by timbussmann** [comment] 2016-10-26 07:32
I raised an issue for the backlog here: #4247 so I'm going to close this discussion.

**Closed by timbussmann** 2016-10-26 07:32 UTC
Labels: Discussion
