### ISSUE TITLE
Setting logging context to null in ScenarioRunner causes NRE

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4319] opened 2016-11-23 15:34 UTC
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs#L31

This code seems to cause issues in ASB tests in case they try to log something after the context has been set to null.

**Comment by danielmarbach** [comment] 2016-11-23 21:19
@SeanFeldman and I were investigating a bit more today. We have a hunch something is off with the ASB shutdown sequence but we are not entirely sure yet. We are still fishing in the dark. Here are some of the investigation results:

## NServiceBus Acceptance Tests

Assumption: ASB has a proper shutdown sequence

As @timbussmann pointed out we are currently setting the logger to null after `PerformTestRun`. This should not matter when the transport is properly shutting down because the acceptance test framework ensures the following

1. The appender is set **before** `PerformTestRun`
1.  `PerformTestRun` calls into `PerformScenarios` which
 1. Starts all endpoints
 1. Executes all `When`
 1. Idles until done condition or timeout is reached
 1. Finally all endpoints are stopped (even when done is not reached and the test is timed out)
1. If all endpoints are shutdown it is OK to set the appender to null since nothing should access the context logger anymore

The conclusion was that we want to leave the code in the acceptance testing framework as is because it might highlight other problems we have.

## ASB

We first assumed the problem occurs because inside the `OnExceptionReceived `triggered by the SDK we trigger critical error which then triggers shutdown of the endpoint. With multiple receivers by default it is likely that the shutdown is triggered multiple times. We discussed the following:

1. Stopping of endpoints is reentrancy safe, it uses a volatile bool and a semaphore slim with one slot. Side note: Should we change that to (I don't want to say the current impl is wrong, just a side note)

```
volatile int disposeSignaled;

async Task Stop() {
       if (Interlocked.Exchange(ref disposeSignaled, 1) != 0)
        {
            return;
        }
}
```

similar to what fody janitor does?
1. We discussed whether the event handler could leak because the event handler executes the critical error which then shuts down the endpoints and then ASB deregisters all handlers while the SDK is still executing the handler. All exceptions happening inside that handler will bubble up to the caller and eventually lead to trigger the failfast of the Azure SDK. We found a bug in ASB that we never actually trigger the CB as well a bug in how we synchronously execute the critical error action inside the event handler. We will raise more issues in ASB.

While typing the above information I found a bug in the acceptance test framework. Will raise an issue and cross link here

**Comment by danielmarbach** [comment] 2016-11-24 16:32
Raised #4331 and #4332 as a consequence of the investigation.

**Comment by danielmarbach** [comment] 2016-11-24 16:34
@SeanFeldman and I concluded that we still want the context appender to be set to null by core since it can highlight other issues. We investigated a lot and all paths we followed lead to discover other potential issues in core and ASB which turned out to be not related to this issue. I double checked it with @bording 

We decided to not invest more time right now and wait for the NUnit runner update. Closing this as won't fix since setting the appender to null is not the solution to the problem

**Closed by danielmarbach** 2016-11-24 16:34 UTC

**Comment by bording** [comment] 2016-11-24 17:11
> We decided to not invest more time right now and wait for the NUnit runner update. Closing this as won't fix since setting the appender to null is not the solution to the problem

What NUnit runner update are you referring to? I believe we're already running 3.5.0 on the build server, and I'm not aware of any other pending update.

**Comment by danielmarbach** [comment] 2016-11-30 15:11
Update, we found the root cause for this issue. https://github.com/Particular/NServiceBus.AzureServiceBus/issues/433

@tmasternak @Scooletz and I sent in a[ PR to address the issue](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/434).
