### ISSUE TITLE
Autosubscribe invokes Subscribe for each handler, not each message subscribed

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3687] opened 2016-04-18 09:15 UTC
### Symptoms

In Version 5 the Autosubscribe feature invokes `Bus.Subscribe` for each handler that handles an event. If there is more than one handler for a given event, the subscribe is invoked multiple times. When these subscribe messages are processed concurrently by the publisher, one some of them are going to fail with concurrency exception and will be retried. Although it should be not visible for the end users (who have FLR and/or SLR enabled), it seems like a bug to me.

### Who's affected

All users on V5

**Comment by timbussmann** [comment] 2016-04-18 12:36
seems to be unnecessary indeed, but is there any damage caused by this? The only thing I could imagine would be a subscription message in the error queue in case retries are disabled?

**Comment by SzymonPobiega** [comment] 2016-04-18 13:02
@timbussmann yes. Plus an `error` in the log file. Not a critical for sure.

**Comment by johnsimons** [comment] 2016-04-18 20:51
I am pretty sure this only affect users that are on RavenDB persistence?

**Comment by SzymonPobiega** [comment] 2016-04-19 06:25
@johnsimons why? NHibernate subscription storage does first check if the entry exists but when both messages are handled in the same time, one of them fails. I've verified this on NHibernate. To make it 100% bullet-proof we would have to use upgrade locks I think.

**Comment by timbussmann** [comment] 2016-04-20 08:06
@SzymonPobiega is this already fixed in v6?

**Comment by SzymonPobiega** [comment] 2016-04-20 12:12
@timbussmann yes.

**Comment by timbussmann** [comment] 2016-04-20 13:10
Since the impact is very low and it's fixed in v6, this sounds like a `Won't fix` to me? @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment] 2016-04-20 13:23
I don't see this as a big deal. I rather get rid of message driven pub sub in the next release than fixing this.

**Comment by andreasohlund** [comment] 2016-04-20 14:57
I'm good with "won't fix", ok to close @szymonpobiega ?

**Closed** 2016-04-20 17:34 UTC
Labels: Type: Bug, Withdrawn: Won't Fix
