### ISSUE TITLE
Do we want to support MaximumMessageThroughputPerSecond in v6?

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus#3359] opened 2016-01-26 14:29 UTC
It looks that we dropped `MaximumMessageThroughputPerSecond`. Do we want to support it? Is it a 'must-have' for v6?

/cc: @Particular/tf-async-core

**Comment by andreasohlund** [comment] 2016-01-26 16:30
Duplicate of https://github.com/Particular/NServiceBus/issues/2859 cc @timbussmann

**Closed by andreasohlund** 2016-01-26 16:30 UTC
Labels: Tag: Core v6, Type: Discussion
