### ISSUE TITLE
Cant mix storages

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4830] opened 2017-07-10 00:26 UTC
This repro uses in memory for sagas and nhibernate for everything else

https://github.com/SimonCropp/scratch/tree/master/MixedPeristence

```
endpointConfiguration.UsePersistence<NHibernatePersistence>();
endpointConfiguration.UsePersistence<InMemoryPersistence,StorageType.Sagas>();
```

When run it blows up with
```
System.InvalidCastException occurred
  HResult=0x80004002
  Message=Unable to cast object of type 'NServiceBus.Persistence.NHibernate.NHibernateLazyNativeTransactionSynchronizedStorageSession' to type 'NServiceBus.InMemorySynchronizedStorageSession'.
  Source=NServiceBus.Core
  StackTrace:
   at NServiceBus.InMemorySagaPersister.Save(IContainSagaData sagaData, SagaCorrelationProperty correlationProperty, SynchronizedStorageSession session, ContextBag context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Persistence\InMemory\SagaPersister\InMemorySagaPersister.cs:line 77
```

But the same will happen (with a diff type cast combination) when mixing other persistence.

Seems that the synchronized storage session is designed to only support on instance in the container. so i dont understand how it should/could work when mixed?

**Comment by SimonCropp** [comment] 2017-07-10 00:27
cc @danielmarbach after some research into your mixing of servicefabric and sql persistences

**Comment by SimonCropp** [comment] 2017-07-10 00:37
some more context: should review/smoke test these combos based on the outcome of this issue https://docs.particular.net/persistence/order

**Comment by SimonCropp** [comment] 2017-07-10 00:38
ping @SzymonPobiega since i seem to remember you having a fairly good contextual knowledge of this scenario

**Comment by SzymonPobiega** [comment] 2017-07-10 05:55
This failure should probably be prevented by the core checking if sagas and outbox are assigned different persistences. I think that `StorageType.Sagas` and `StorageType.Outbox` are separate because some storages support one but not the other (e.g. Azure).

The problem is not only with mixing persistence of different types. It would also be a problem if one had a different config than the other (e.g. different `Configuration` object in NHibernate).

While the type mismatch can be addressed in the core, the configuration cannot so I would vote for dealing with this on the persistence level:
 * Throw is saga and outbox have different persistence types
 * Throw is saga and outbox have conflicting configuration

**Comment by timbussmann** [comment] 2017-07-12 15:26
given this seems to be a larger effort with many edge cases to be considered. Should this be raised in pdev?

**Comment by timbussmann** [comment] 2017-08-03 15:21
@SimonCropp could you raise an issue in pdev for this?

**Comment by timbussmann** [comment] 2017-08-31 15:17
I'm going to close this issue as nobody followed up on this. I'll not raise the in pdev myself as I don't feel like I have enough context for an appropriate issue description. So please re-raise this issue in pdev if you think something should be done about this.

**Comment by timbussmann** [comment] 2017-09-01 06:36
After talking to @andreasohlund we decided to reopen and @andreasohlund will investigate a bit further on the details of the described bug.

**Comment by SzymonPobiega** [comment] 2017-09-01 06:39
I see more as a design problem, not a 🐛 . FYI it is not fixed in SQL persistence: we'll check if the outbox or sagas are enabled and make sure that both use SQL persistence. Other persistence concerns are independent.

**Comment by andreasohlund** [comment] 2017-09-01 06:39
Looking at our doco this should be supported

https://docs.particular.net/persistence/order#example-3

my hunch is that this isn't a core bug but instead related to the fact that currently outbox + sagas must use the same storage.

@Particular/sqlpersistence-maintainers I have a faint memory that you now check this?

@Particular/nhibernate-persistence-maintainers @Particular/azure-maintainers (ASP)  thoughts?

**Comment by andreasohlund** [comment] 2017-09-01 06:44
Looking at our doco we do imply that

>To take advantage of the same local database transaction to store all data and get a similar experience to using DTC, the business data and Outbox deduplication data must be stored in the same database.

https://docs.particular.net/nservicebus/outbox/

So how about we add a better exception in the core?

`if SagaStorageType != OutboxStorageType throw "You can mix storages for bla bla bla"`

**Comment by SzymonPobiega** [comment] 2017-09-01 06:47
@andreasohlund yeah, that check in the core would be sufficient in my opinion. Until we decouple these two this is a must.

**Comment by andreasohlund** [comment] 2017-09-01 07:01
@Particular/nservicebus-maintainers is this important enough for us to ship in v7?

**Comment by timbussmann** [comment] 2017-09-01 07:44
@andreasohlund doesn't seem like it would require a breaking change? So I'd say this would be good enough for a minor?

**Comment by andreasohlund** [comment] 2017-09-11 07:13
Fair enough, I've added this to the Future milestone

**Closed** 2018-08-15 12:53 UTC
Labels: Bug
