### ISSUE TITLE
Validate if the scanned types/assemblies contain the selected persistence or transport

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3729] opened 2016-05-04 11:41 UTC
When using custom assembly scanning you should get an error when the configuration refers to a transport or persistence that is not in the configured set of types or assemblies.

Such a configuration would be conflicting as a type is used in the configuration from an assembly that is not in the assemblies supplied to scan.

This prevents issues at runtime like :

>NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver - Failed to fetch timeouts from the timeout storage
>System.NullReferenceException: Object reference not set to an instance of an object.
at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.Poll(Object obj) in

**Comment by Scooletz** [comment] 2016-05-04 11:45
@ramonsmits Would it be the reason for the error reported in here: https://groups.google.com/forum/#!topic/particularsoftware/NYcRK5R1dZQ ?

**Comment by ramonsmits** [comment] 2016-05-04 11:52
@Scooletz I would say yes, I had another customer that added a custom EntityFramework based persistence (https://github.com/benjaminramey/GoodlyFere.NServiceBus.EntityFramework) and did not include that assembly in the assembly whitelist.

**Comment by SeanFeldman** [comment] 2016-05-04 20:42
@Scooletz The issue in the GG post was not related to the assembly scanning. Assembly was picked up ok. It was a binding redirect that was failing and swallowed by the host.

@ramonsmits with core v6 whitelisting is not an option. So unless assemblies are explicitly excluded, this won't happen.

**Comment by timbussmann** [comment] 2016-05-06 08:50
Can you elaborate the reason why the transport/persistence needs to be included in the assembly scanning? (since @SeanFeldman stated that the described exception isn't really related?)

**Comment by ramonsmits** [comment] 2016-05-10 10:01
@timbussmann The comment of @SeanFeldman was based on the comment of @Scooletz and me. Not on the issue description.

Please read the issue description and what is unclear about it.

**Comment by timbussmann** [comment] 2016-05-17 06:38
what I meant is: From an user perspective it's weird that you have to include the transport/persistence assemblies in the assembly scanning. Since you're declaring the transport on the code config, you need to have a reference at build time already, so there is no reason for this assembly not to be loaded?

**Comment by timbussmann** [comment] 2016-06-01 16:37
@ramonsmits is this only an issue on v5 or also on v6? Can describe how to reproduce the issue (or provide a simple repro?). In case of a runtime exception I'd say this would classify as a bug.

**Comment by ramonsmits** [comment] 2016-06-03 15:55
@timbussmann This is V5, don't know if V6 has a similar issue.

How to reproduce

- create project
- select persistence in the API
- exclude that assembly from the scanned assemblies

You should now get this error.

**Comment by timbussmann** [comment] 2016-06-07 09:37
tested it v6 and the endpoint starts to fail if you use a persistence and manually exclude that dll like here: `busConfig.ExcludeAssemblies("NServiceBus.RavenDB");`. Not sure whether we need to change something here. It's not that surprising that this doesn't work out well, especially with the exclude approach in v6 (and it's not critical enough to change the v5 behavior). I would consider this a feature, but even then I'd vote to close this. @Particular/nservicebus-maintainers what do you think?

**Comment by bording** [comment] 2016-06-07 17:15
I think this reinforces why the move to an exclude-only approach in v6 is a good idea. 

While this is less ideal with the v5 whitelisting of assemblies, I agree with @timbussmann that this doesn't feel critical enough to be worth going back and making a change at this point.

**Comment by ramonsmits** [comment] 2016-06-08 19:27
@timbussmann Start to fail is better then the NRE while the instance is running. If you bump your head against this you really don't have any idea what the cause is.

As @SimonCropp mentioned somewhere, we should never throw a NRE.

**Comment by SimonCropp** [comment] 2016-06-08 22:12
@ramonsmits can u reproduce this in v6?

**Comment by timbussmann** [comment] 2016-06-10 14:33
@SimonCropp as described above, I could reproduce an exception when excluding a persistence assembly. The excption occured at startup and was not a NRE (I think some binding issues), but as mentioned above, for v6 I wonder whether we really need to handle this scenario where users explicitly exclude an assembly which they obviously(?) need.

as for v5, I think this is not critical. I vote to close this issue, objections?

**Closed** 2016-06-14 15:43 UTC
Labels: Type: Discussion
