### ISSUE TITLE
Better error message for overlapping endpoint mappings

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1939] opened 2014-02-01 04:46 UTC
so this

```
    <MessageEndpointMappings >
      <add Assembly="Common" Endpoint="endpoint1" />
      <add Assembly="Common" Endpoint="endpoint2" />
```

results in this

```
System.Configuration.ConfigurationErrorsException occurred
  HResult=-2146232062
  Message=The entry 'Common' has already been added. (C:\Code\ProductionTests\src\WireCompatTest\Current\bin\Debug\Current.dll.config line 12)
  Source=System.Configuration
  BareMessage=The entry 'Common' has already been added.
  Filename=C:\Code\ProductionTests\src\WireCompatTest\Current\bin\Debug\Current.dll.config
  Line=12
  StackTrace:
       at System.Configuration.ConfigurationElementCollection.BaseAdd(ConfigurationElement element, Boolean throwIfExists, Boolean ignoreLocks)
  InnerException: 
```

Now @andreasohlund says we "explicitly dont support this".

If this is a scenario we explicitly dont support we should throw an explicit error message explaining why.

**Comment by DevinSRose** [comment] 2015-03-24 18:04
+1

**Comment by danielmarbach** [comment] 2016-09-09 09:53
Assigned to @timbussmann He will verify the current behavior in v6 and take actions if needed.

**Comment by timbussmann** [comment] 2016-09-12 07:23
Current v6 version still throws the same unhelpful exception message.

**Comment by timbussmann** [comment] 2016-09-12 09:40
The exception is thrown because of the `throwIfExists` parameter set to true here: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageEndpointMappingCollection.cs#L118

If we set that to false, it the later would just overwrite the first entry. I think this would be the better solution since we already have an overwrite logic when registering subclasses. What do you think @Particular/nservicebus-maintainers @SimonCropp ?

**Comment by timbussmann** [comment] 2016-09-15 14:46
Slightly changed my mind on my previous that statement. Since allowing overwrites could lead to unexpected behavior due to configuration mistakes, we really should just improve the exception message. At this point we are already thinking about removing message endpoint mappings altogether, so changing behavior is probably not something we want to do.

**Comment by timbussmann** [comment] 2016-09-29 13:04
a better exception message will be thrown with 6.1

**Closed by timbussmann** 2016-09-29 13:04 UTC
