### ISSUE TITLE
AssemblyScanner Referencing Bug prior to v7

### ISSUE THREAD

**Issue by coopertran** [Particular/NServiceBus#5201] opened 2018-06-25 15:40 UTC
Found a bug in the AssemblyScanner type in NServiceBus.Core (6.4.4) when used in conjunction with NServiceBus.Host (7.0.2)

The scenario is as follows:
There are three assemblies - A, B, and C.

Assembly C references NServiceBus.Core and defines an abstract class that implements IConfigureThisEndpoint.

Assembly B references assembly C and does NOT reference NServiceBus.Core

Assembly A references assembly B and does NOT reference NServiceBus.Core

So the references look like A -> B -> C -> NServiceBus.Core

when the EndpointTypeDeterminer.ScanAssembliesForEndpoints() calls AssemblyScanner.GetScannableAssemblies() assembly C is returned only when it is scanned BEFORE assembly B. Currently based off of name ordering. This is because the first time assembly B is passed to the AssemblyScanner.ReferencesNServiceBus method it returns true, but caches false. Then when assembly C is scanned the wrong cached value for assembly B is returned. This causes NServiceBus.Host not to start because it can't find the endpoint configuration

**Comment by ramonsmits** [comment] 2018-06-26 07:01
@coopertran Thanks for reporting. Does the explicit configuration work for you as a workaround?

```xml
<configuration>
  <appSettings>
    <add key="EndpointConfigurationType"
         value="YourNamespace.YourTypeName, YourAssembly"/>
  </appSettings>
</configuration>
```
Source: https://docs.particular.net/nservicebus/hosting/nservicebus-host/#endpoint-configuration-assembly-scanning

**Comment by timbussmann** [comment] 2018-07-04 13:02
I was able to confirm this bug by changing the assembly name of assembly A to Z (to change the ordering) in this test which should cover this scenario: https://github.com/Particular/NServiceBus/blob/support-6.4/src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs#L161 and the test reproduces the behavior described by @coopertran.

Thanks for the detailed analytics @coopertran , you are absolutely right with the described behavior. Please let us know whether the workaround suggested by @ramonsmits works for you?

This bug seems to be fixed in v7 which contains an updated implementation of the AssemblyScanner.

**Comment by coopertran** [comment] 2018-07-05 17:16
Thanks @timbussmann and @ramonsmits. The work around does work for me. 
Thank you

**Comment by ramonsmits** [comment] 2018-07-09 15:49
Closing this as the solution is to be explicit in what type to load via configuration this doesn't require to be fixed in an older version as the current major doesn't have this bug.

**Closed by ramonsmits** 2018-07-09 15:49 UTC
Labels: Bug
