### ISSUE TITLE
Bus.Defer sets the OriginatingEndpoint to the local endpoint so there is no ability to reply

### ISSUE THREAD

**Issue by jdrat2000** [Particular/NServiceBus#2710] opened 2015-04-10 13:18 UTC
In a server handler of a full duplex implementation,  if Bus.Defer is used to delay processing on the server, Bus.Reply will no longer work because the OriginatingEndpoint header is being changed to the local endpoint name.   If you use Bus.Reply the message is dropped back into the local queue.   This causes an exception because there is no local handler for the reply message.   

See support case 10199.

This behavior is not expect and the documentation is unclear.   What is the proper use of the Defer capability in a handler?  I haven't tagged this as a bug but perhaps it could be considered one. 

When used for error and retry alternatives to exist.  Second Level Retry is an option but will impact all handlers in the endpoint.   A Saga can be created but has the side effects of requiring additional persistence and performance considerations.

**Comment by andreasohlund** [comment] 2015-04-14 15:30
This seems like a bug to me?

**Comment by johnsimons** [comment] 2015-04-19 23:57
If we are to change this behavior, how do we handle backwards compatibility?

**Comment by jdrat2000** [comment] 2015-04-20 00:39
@johnsimons Good question.  Can you give me an example of how you've seen it used John where the current behavior is expected?   I can think of a scenario within a subscriber... something that wouldn't use the Reply.    I'm not sure in the current case why they would use reply and expect it to return right back to the current queue.

**Comment by johnsimons** [comment] 2015-04-20 00:55
@jdrat2000 I don't have an example, but that is not to say that we do not currently have users that are using this current behavior.

**Comment by andreasohlund** [comment] 2015-04-20 08:16
>If we are to change this behavior, how do we handle backwards compatibility?

This is tricky but I say that since this is plain wrong we treat it as a bug and correct the wrong behavior?

**Comment by johnsimons** [comment] 2015-04-24 00:07
@andreasohlund which version do we patch ? The next major ?

**Comment by andreasohlund** [comment] 2015-04-24 06:44
Thinking next major since this one would be found in development?

**Comment by johnsimons** [comment] 2015-04-28 00:28
Thanks @andreasohlund

**Comment by johnsimons** [comment] 2015-05-04 06:11
How do we fix this @andreasohlund  ?

**Comment by timbussmann** [comment] 2016-08-18 11:02
@andreasohlund since there was no progress on this and `Bus.Defer` does no longer exist in v6, should we consider closing this as `Won't fix`? With v6 you should be able to keep the replyto address manually by using `sendOptions.RouteReplyTo();` with the previously read replyTo header when using it with `sendOptions.RouteToThisEndpoint();`.

**Comment by andreasohlund** [comment] 2016-08-18 12:35
Sounds fair enough, do we need to update any doco?

**Comment by timbussmann** [comment] 2016-08-18 13:15
we could add a note to the v5 doco I guess.

http://docs.particular.net/nservicebus/messaging/delayed-delivery#delaying-message-dispatching-versions-5-and-below-defer-message-handling states:

> Semantically bus.Defer(...) is equivalent to calling bus.SendLocal(...) after time condition is met

so we could either make a note directly there, or add a note to the SendLocal documentation here: http://docs.particular.net/nservicebus/messaging/send-a-message#sending-to-self that this will replace the replytoaddress.

Adding it directly to the v5 defer docs seems to be closer to the issue?

**Comment by andreasohlund** [comment] 2016-08-18 13:31
:+1: to add this to the defer doco seems best to me

**Comment by timbussmann** [comment] 2016-08-18 13:54
raised PR here: https://github.com/Particular/docs.particular.net/pull/1791

**Comment by andreasohlund** [comment] 2016-08-19 10:07
Starting to thing it might be easier to just fix the bug instead, I'll do a quick spike

**Comment by andreasohlund** [comment] 2016-08-19 12:20
Turned into a bigger discussion, please see https://github.com/Particular/NServiceBus/issues/4074

**Comment by andreasohlund** [comment] 2017-10-02 13:10
@jdrat2000 as we have discovered recently reusing message headers and [specifically message ids can cause message loss](https://github.com/Particular/NServiceBus/issues/4993). With this in mind I think if the same message should be processed the only safe option is to use recoverability. Given that you can now tailor the recoverability behavior for each individual message we should use that as our recommendation.

Closing this as won't fix

**Comment by boblangley** [comment] 2021-01-15 21:24
@andreasohlund In your last comment, you stated

> Closing this as won't fix

But the issue is still open. Can we close it?

**Closed** 2021-01-16 07:17 UTC
Labels: Bug
