### ISSUE TITLE
scheduled task stops firing when one instance of the task failed to be processed

### ISSUE THREAD

**Issue by jjanuszkiewicz** [Particular/NServiceBus#5591] opened 2020-02-24 15:11 UTC
We've encountered the following situation in a production system, which might be a bug or a case of too vague documentation.

We have a service which uses NSB with Outbox (with NHibernate persistence). The service also uses NSB Scheduler to set up a task running every 30s.
We had a network problem which caused DB connection timeouts, after which the scheduled task stopped firing.
Upon investigation, we found out that:

- There was a series of timeouts on INSERTs to the OutboxRecord table.
- After these errors, there was an ERROR logged: `ERROR NServiceBus.Faults.Forwarder.FaultManager - Message with '[GUID]' id has failed FLR and will be moved to the configured error queue.`
 - The scheduled task stopped firing from that moment.
 - The error queue contained a single `ScheduledTask` message

Looking further in NSB code, it looks like the scheduler works by re-scheduling the next occurrence of the task when handling the current one. Therefore if something fails before the handler for the task is executed (e.g. outbox persistence fails a large enough number of times), the ScheduledTask message is moved to the error queue and no further occurrences will ever be scheduled (until endpoint restart).

I've re-read the [Scheduler documentation](https://docs.particular.net/nservicebus/scheduling) and there is a note informing that:

 > Scheduling a task depends on delayed delivery. If the delayed delivery operation fails, the Scheduler will be interrupted and a ScheduledTask message will be forwarded to the error queue.

However we never anticipated that by "interrupted" it is meant that it will stop firing at all. The docs suggest that the current occurrence will be moved to the error queue, but not that this effectively cancels further ones.

We've experienced this on NSB 5.2, but the code in master looks very similar.

Is there anything you can do to make the Scheduler more resistant to errors like this? With network being generally unreliable, enabling the Outbox with any non-localhost, non-inmemory persistence effectively renders the Scheduler unusable for any important tasks.

My rationale for why this is a major problem:
 - For "normal" incoming messages a temporary network failure only means that messages received in a given timeframe are moved to errors and normal processing of further messages is possible when the failure condition stops.
 - For scheduled tasks, a long enough temporary network failure means that the task stops firing and doesn't resume when the failure condition stops. Also there isn't an clear error message in the logs that can be acted upon intelligently.

**Comment by tmasternak** [comment] 2020-02-27 08:14
Hi @jjanuszkiewicz,

> However we never anticipated that by "interrupted" it is meant that it will stop firing at all. The docs suggest that the current occurrence will be moved to the error queue, but not that this effectively cancels further ones.

I agree that this might be not clear enough. The way Scheduler works is by representing each task as a deferred message. When that message is received the task is executed and a new message is generated so that the task executes in the future. When no new message gets created no task is executed. 

In other words, if the incoming message gets moved to the input queue, there is nothing to trigger the scheduled task.  

Could you have a look at [this change](https://github.com/Particular/docs.particular.net/pull/4726/files) to the documentation? Does it make it clearer what's the behavior?

**Comment by jjanuszkiewicz** [comment] 2020-03-02 07:46
Hi @tmasternak, this change does make it clearer, but I don't think this is enough. An even more explicit note (e.g. in the Outbox documentation) would be very helpful as well. As far as any critical business functionality is concerned, I think that the combination of Outbox with persistence + Scheduler should be explicitly discouraged.

Please compare this: we were running NSB with Scheduler in a few endpoints for the last ~6 years with MSMQ and DTC (no Outbox) and there was *not a single problem* with it, whatsoever. When we moved from MSMQ to RabbitMQ, and by consequence started using Outbox instead of DTC, we are hitting this problem *every week* on production. Logging to the PROD cluster over the weekend to move the scheduled tasks to be retried is not sustainable. I'm writing all this to explain why I consider this to be a critical design problem, therefore using a combination of these NSB features should be discouraged.

I'd also like to ask you to consider an implementation change to at least issue a warning on endpoint startup when a combination of Outbox and Scheduler is used (unless in-memory persistence is selected for Outbox). You already do similar things, e.g. there is a warning that MSDTC is running when Outbox is enabled, also some other warnings are there helping prevent common pitfalls (e.g. warning that a plain message is being published instead of a event message), so I think this would fit what NSB already does.

An implementation change to Scheduler, so that it avoids this problem completely, would be the perfect solution, but I guess this is not an option (?)

We will need to stop using Scheduler and use Quartz.NET in our project because of this issue, but doco changes and possibly the startup warnings could help others not fall into this problem in the future.

**Comment by tmasternak** [comment] 2020-03-02 09:57
@jjanuszkiewicz you are correct that by moving from MSMQ+no-Outbox to RabbitMQ+Outbox the likelihood of getting `ScheduledTask` moved to the error queue and causing the task from not being re-scheduled is higher.  

This is caused by the fact that in RabbitMQ+Outbox scenario processing `ScheduledTask` involves both transport and the database. This, in turn, opens up a scenario in which transport is available but the persister database is down.

However, the exact behavior depends on the recoverability configuration. `ScheduledTask` will be moved to the error queue only when immediate and delayed retries fail. 

The overall, idea of the doc notice is that in scenarios when exact timing and/or full reliability is needed a dedicated scheduling technology is recommended. Here is [a new version](https://github.com/Particular/docs.particular.net/pull/4736) of the doco. Please have a look.

**Comment by ramonsmits** [comment] 2020-03-11 13:01
@jjanuszkiewicz What is your recovery configuration? Do you allow for enough immediate and delayed retries? 

You are implying that outbox is causing storage issues that are not occuring when MSDTC is used. Could you please provide more information on the database errors that you are getting as that seems be the actual problem. Failing reoccuring tasks is just the symptom. Please provide exception types, messages and stack traces if possible.

**Comment by ramonsmits** [comment] 2020-07-09 21:08
@jjanuszkiewicz The scheduler is an artifact from the past. Its inception is the early versions of NServiceBus. In the docs it we do give advise in a big yellow warning box

- https://docs.particular.net/nservicebus/scheduling/

That said, we should consider to mark the scheduler as obsolete in 7.x and removing it in 8.x

**Comment by ramonsmits** [comment] 2020-07-09 21:23
@jjanuszkiewicz By the way, [we already have a PR to emphasize not to use the scheduler](https://github.com/Particular/docs.particular.net/pull/4736) but it still hasn't been merged yet.

Thanks for the feedback!

**Closed** 2020-07-09 21:24 UTC
