### ISSUE TITLE
InMemoryPersistence does not respect subscription versioning rules

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2778] opened 2015-07-13 11:33 UTC
## Who's affected

Everyone using `InMemoryPersistence` to store subscriptions. As [stated here](http://docs.particular.net/nservicebus/messaging/publish-subscribe/configuration#versioning-subscriptions) only Major version should be taken into account when looking for subscriptions.

## Symptoms

If the publisher endpoint:

* is configured using `InMemoryPersistence` to store subscriptions
* is using a message type whose version (Minor, Revision or Build) is not the same as the subscription;

The publish operation does not publish the message and no error is generated.

## Triage

The `InMemoryPersistence` storage engine utilizes a `ConcurrentDictionary` where the key is of type `MessageType`. `MessageType` correctly handled equality compare using the type and the `Major` version only, but does not use the same logic in the `GetHashCode` function where all the `Version` is used to generate the `MessageType` hash code, that is used by the `ConcurrentDictionary` to look for keys.

## Steps to reproduce

A repro is available in the Google Group discussion: https://groups.google.com/d/msgid/particularsoftware/8de6bb7b-9592-4d71-9841-bce638fea96f%40googlegroups.com?utm_medium=email&utm_source=footer

## Workaround

none other than change/replace the subscription storage

**Comment by yvesgoeleven** [comment] 2015-07-15 18:36
There seems to be quite some inconsistencies here

- nhiberate is full version dependent as it uses version directly: https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/Subscriptions/SubscriptionPersister.cs#L35
- azure storage is also full version dependent as it uses MessageType.ToString() https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageType.cs#L81
- azure servicebus is version independent as it uses Type.FullName https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Creation/Resources/ServicebusSubscriptionFilterBuilder.cs#L9
- msmq seems to be full version dependent: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs#L148

Raven works as documented https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Subscriptions/Subscription.cs#L25, I guess that was our default when the documentation was written?

**Comment by danielmarbach** [comment] 2015-07-15 18:39
@yvesgoeleven Your statement about Msmq should point to that: 

[`MessageDrivenPubSub`](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageType.cs#L91)

So MSMQ behaves correctly

**Comment by danielmarbach** [comment] 2015-07-15 18:40
This shows a design flaw. Why should every transports implement this again and again? This should be handled and provided by the core or the routing capability ;)

**Comment by yvesgoeleven** [comment] 2015-07-15 18:41
@danielmarbach I couldn't find the code where that equals is being invoked

**Comment by danielmarbach** [comment] 2015-07-15 18:46
I think we need to document the current behavior for each transport and persistence and then raise a requirement how we want to proceed. Thoughts?

**Comment by yvesgoeleven** [comment] 2015-07-15 18:49
This is going to be hard especially since that data is persisted in existing implementations already, you can't just change it, you need a data migration

**Comment by mauroservienti** [comment] 2015-07-15 19:01
This needs to be fixed. Inconsistencies when changing transport are a PITA for the end user.
I agree with Daniel that this is a core concern and that a requirements needs to be raised, migration will be part of the PoA or a connected requirement.

**Comment by SeanFeldman** [comment] 2015-07-15 19:16
@mauroservienti fixing this might break things for existing one just like @yvesgoeleven outlined.
It also seems that customers don't really use that anyway, so why not to embrace versioning based on namespace?

**Comment by SeanFeldman** [comment] 2015-08-20 20:06
As @danielmarbach pointed out, it's a design flaw and it causes customers issue. 
Example: https://groups.google.com/forum/#!topic/particularsoftware/n-U_Z0RRM1s

@Particular/nservicebus should we give this a higher priority to be included in v6 since that's the only time we can introduce breaking changes?

**Comment by andreasohlund** [comment] 2015-12-18 08:54
Adding to this it seems like we're wrongly looking at the "4:th" digit as well

https://github.com/Particular/docs.particular.net/pull/977#issuecomment-165161928

**Comment by brunobertechini** [comment] 2016-09-24 16:02
+1 here in 2016 :)

My problem is the same but the origin is caused by a developing design time:

We have different solutions per each microservice.

Microservice BLUE has its contracts and its solution is being built using GitVersion (which means my source code does not contain AssemblyVersionInfo thus -> v0.0.0.0 when running inside Visual Studio).

Microservice RED has referenced the Nuget generated package by BLUEs CI build, different version.

Im using Azure Storage Queue and this is causing me trouble to debug/develop in Visual Studio since my BLUE microservice can't publish messages anymore because the sucscription is made against a different asembly version.

NServiceBus 5.2.16. Is this treated differently in NSB 6 ? Should I move on since this is a brand-new project (green field) ?

What other alternatives do I have besides change my Build/Deploy/CI to consistent versioning. Even this is kind of hard because Azure Storate Queue subscriptions need the FULL version not the major only as stated by documentation

Thoughts?

Bruno

**Comment by brunobertechini** [comment] 2016-09-24 16:04
One thing I can say is : We should forget about other microservices when developing the BLUE one (as per my previous comment). 

And always update non-production ready codes with latest nuget packages.

Or am I missing something here ?

Should I use a single Assembly for ALL microservices contracts (commands/events) ?

Bruno

**Comment by danielmarbach** [comment] 2016-09-26 09:26
@timbussmann answered [here](https://github.com/Particular/NServiceBus/issues/1394#issuecomment-249504779)

**Comment by andreasohlund** [comment] 2016-09-30 20:33
As of v6 and soon 5.2.17 all storages will ignore the version, closing this as `Invalid`

**Closed by andreasohlund** 2016-09-30 20:33 UTC
Labels: Type: Bug
