### ISSUE TITLE
MSMQ: When running QueuePermissions for the "Everyone" group, it doesn't check the actual rights for the user

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#4526] opened 2017-03-02 06:05 UTC
It doesn't matter if the queue has "Everyone" as allowed user group. What matters is the individual queue operation permissions. However, we always display the following message, even if the "Send Messages" permission for Everyone is turned off.

```
2017-03-02 05:52:59.148 WARN  NServiceBus.QueuePermissions Queue [private$\Samples.FullDuplex.Server1.Timeouts] is running with [Everyone] and/or [NT AUTHORITY\ANONYMOUS LOGON] permissions. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-03-02 05:52:59.159 WARN  NServiceBus.QueuePermissions Queue [private$\Samples.FullDuplex.Server1.TimeoutsDispatcher] is running with [Everyone] and/or [NT AUTHORITY\ANONYMOUS LOGON] permissions. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-03-02 05:52:59.180 WARN  NServiceBus.QueuePermissions Queue [private$\Samples.FullDuplex.Server1.Retries] is running with [Everyone] and/or [NT AUTHORITY\ANONYMOUS LOGON] permissions. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-03-02 05:52:59.193 WARN  NServiceBus.QueuePermissions Queue [private$\Samples.FullDuplex.Server1] is running with [Everyone] and/or [NT AUTHORITY\ANONYMOUS LOGON] permissions. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
```

**Comment by andreasohlund** [comment] 2017-03-02 07:11
Agreed, but is there any reason why `Everyone` should have any permissions on the queue? (Ie perhaps the current "broader" check is good enough?)

**Comment by indualagarsamy** [comment] 2017-03-02 22:05
So what if Everyone has access to the queue, but just the "Get Properties"... but not the "Send Messages"  permission? Is a warning even useful in that case? The warning just becomes noise?

**Comment by andreasohlund** [comment] 2017-03-03 06:09
>So what if Everyone has access to the queue, but just the "Get Properties"... but not the "Send Messages" permission? Is a warning even useful in that case? The warning just becomes noise?

I can't see any good reason why you would want everyone to have any permissions on a queue in a production environment? ( @gbiellem thoughts?)

**Comment by gbiellem** [comment] 2017-03-03 07:30
@andreasohlund if you care about security then I can't think of a case for having Everyone.

The only thing that would come close is if I wanted to set a Deny rule rather than an Allow rule .e.g Expliciting denying Everyone a certain permission.    In this case the deny rule would also pop the warning which seems a little weird.  In a prod environment that's an unlikely scenario though . You'd more likely use a group instead.

**Comment by andreasohlund** [comment] 2017-03-15 08:36
@indualagarsamy given https://github.com/Particular/NServiceBus/issues/4526#issuecomment-283885794 would you say that we can close this as "by design" ?

**Comment by indualagarsamy** [comment] 2017-04-04 15:41
Had a chat with @andreasohlund and agreed that we can make a change to make this code better. 
As pointed out by @gbiellem a better solution would to be WARN if the "Everyone" group has any of the permissions in the "Allow" role than the "Deny" role. This should get rid of the false warnings.

**Closed** 2017-04-12 11:15 UTC
