### ISSUE TITLE
Callback for last retry of message.

### ISSUE THREAD

**Issue by carl-berg** [Particular/NServiceBus#2853] opened 2015-09-03 15:50 UTC
Is there any way of intercepting when the last retry has been made for a message in NServicebus v4? I have a scenario where i want to publish a failure-message if processing of the message failed (in order to notify the user of the processing turnout). There seems to be some way to handle this in v5, but not in v4, is that correct?

**Comment by danielmarbach** [comment] 2016-03-16 09:23
@carl-berg Sorry we dropped the ball on that one! The only way to do it is to implement a [custom fault manager](https://github.com/Particular/docs.particular.net/issues/1281), the problem is that you loose second level retries and you have to deal with with sending messages to the error queue yourself. The better approach is to use [custom notifications with ServiceControl](http://docs.particular.net/servicecontrol/contracts#custom-notification-and-alerting-using-servicecontrol-events-alerting-on-failedmessages-event)

I'm closing this issue.

**Closed by danielmarbach** 2016-03-16 09:23 UTC
Labels: Type: Discussion
