### ISSUE TITLE
Unsubscribe is not validate by acceptance tests

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#4254] opened 2016-10-27 06:33 UTC
Have ran into this issue while handling a [bug with ASB v7](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/392). While we re-implemented the transport from a scratch, we've completely failed (taking the responsibility for that) to implement subscription removal. 
ATTs verify subscriptions work, but there's is nothing in place to ensure that once an endpoint has unsubscribed, messages are not re-delivered. 

@Particular/nservicebus-maintainers is this something that ATTs should test? Should that be a standard test for any downstream transport project?

**Comment by timbussmann** [comment] 2016-10-27 06:45
I think that makes sense to test. The potential difficulty with such a test is that "non-delivery" is hard to test. I think the test setup would have to look something like this:

* Setup 1 Publisher, 2 Subscribers
* After both subscribers subscribed, publish an event
* After both subscribers received the message, unsubscribe subscriber 1
* After unsubscription, publish 1-2 events
* Verify subscriber 2 still receives the events while subscriber 1 shouldn't

would that have catch your bug @SeanFeldman ?

**Comment by SeanFeldman** [comment] 2016-10-28 04:15
@timbussmann 👍

**Comment by andreasohlund** [comment] 2016-10-28 07:59
Is this suitable to test using the transport tests and exercise the ISubscriptionManager?

**Comment by bording** [comment] 2016-10-28 16:17
> Is this suitable to test using the transport tests and exercise the ISubscriptionManager?

Using the just the transport tests, I'm not sure how you'd be able to verify that the subscription has actually been removed.

**Comment by SeanFeldman** [comment] 2016-10-28 18:02
Now that I think about, suggestion made in https://github.com/Particular/NServiceBus/issues/4254#issuecomment-256560092 won't work. Here's why:

When `ISubscriptionManager` is requested to unsubscribe from an event, the transport is going to perform what's needed to be done. To verify that the transport has completed it's work, originally subscribing endpoint should be stopped and restarted, to ensure events are not received. Just unsubscribing is not always going to suffice. 

This is exactly what happened with ASB. A running endpoint could unsubscribe and stop receiving events. The moment it would restart, events be delivered again. I'm not sure sure how ATTs would help here, but the fact that we lost a functionality (not even had a bug) and couldn't catch it with automated tests, makes me somewhat uncomfortable.

**Comment by bording** [comment] 2016-10-28 18:14
> This is exactly what happened with ASB. A running endpoint could unsubscribe and stop receiving events. The moment it would restart, events be delivered again.

This is because you were stopping the event receivers, but not permanently removing the subscription, right? So, next time the endpoint started, it would see the subscription and restart the event receivers.

**Comment by SeanFeldman** [comment] 2016-10-28 18:16
@bording correct. The thorough test would require to validate that not only receivers stopped, but also that the topology was updated.

**Comment by bording** [comment] 2016-10-28 18:43
Is there anything in the acceptance test framework that wouldn't be able to handle having two `Scenario.Define` calls in a single test? That way you could unsubscribe, shut down the endpoints, and then a second call to Define to start them back up.

**Comment by timbussmann** [comment] 2016-10-31 08:34
> This is exactly what happened with ASB. A running endpoint could unsubscribe and stop receiving events. The moment it would restart, events be delivered again. 

that seems to be quite a unexpected behavior? Is that implemented intentionally? In that case I think we would have a dedicated test for ASB since no other transport requires restarts?

> Is there anything in the acceptance test framework that wouldn't be able to handle having two Scenario.Define calls in a single test?

that should work I think.

**Comment by andreasohlund** [comment] 2016-10-31 14:29
👍 for a dedicated test for the ASB case where a restart is needed. That said don't we need at least one transport test that checks that unsubscribe works?

**Comment by bording** [comment] 2016-10-31 15:25
ASB doesn't require a restart, that was a bug of their implementation. The restart would have been required in the "unsubscribe" test to detect the bug. Otherwise, ASB would pass any test written around this scenario despite the bug.

**Comment by SeanFeldman** [comment] 2016-11-01 04:57
> In that case I think we would have a dedicated test for ASB since no other transport requires restarts?

As @bording said, ASB had an implementation issue. Unsubscribe would work during the test, but not get persisted. How reliable ATTs are if I can't rely on it to ensure unsubscribe functionality is actually working 😉

**Comment by andreasohlund** [comment] 2016-12-02 07:34
Given that #4289 is merged is there anything left todo here?

**Comment by danielmarbach** [comment] 2016-12-02 15:45
The acceptance tests are around and merged. I'm closing this.

**Closed by danielmarbach** 2016-12-02 15:45 UTC
