### ISSUE TITLE
License verifier throws unnecessarily on startup

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4701] opened 2017-05-12 12:58 UTC
With the latest license changes in 6.3 we throw one ex 

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/App_Packages/Particular.Licensing/LicenseVerifier.cs#L31

for each license location that we check.

I propose that we fix this as part of 6.3 to avoid noise for when debugging with "break on unhandled exceptions"

@bording this is was introduced when you cleaned up the licensing code?

**Comment by timbussmann** [comment] 2017-05-12 13:47
btw. this is mostly coming from checking all the registry sources where we "validate" the values even when we see that no registry key is around.

**Comment by bording** [comment] 2017-05-15 20:15
The `LicenseVerifier` code didn't change as part of the source package update, so as @timbussmann said, this code path is being called more often now that we're checking all possible license locations on startup instead of stopping after the first one found.

Looking what the code is doing, I don't really see how we can change it since parsing the license might need to throw.

**Comment by andreasohlund** [comment] 2017-05-16 08:49
>Looking what the code is doing, I don't really see how we can change it since parsing the license might need to throw.

But we shouldn't even check if the string is null or empty?

**Comment by timbussmann** [comment] 2017-05-16 08:58
> But we shouldn't even check if the string is null or empty?

we should check if there is a key in the registry with an empty value, but we should not check if the key doesn't even exists which is what we currently do.

**Comment by dasjestyr** [comment] 2017-08-10 19:21
So I'm getting this right now on startup even though I'm providing a license file path in the endpoint config. Not sure if this is related but it's preventing the host from starting.

**Comment by bording** [comment] 2017-08-10 19:31
@dasjestyr License related problems shouldn't prevent an endpoint from starting. Can you provide more details as to what problem you're having?

**Comment by dasjestyr** [comment] 2017-08-10 20:34
On startup, NServiceBus.Core.dll throws an exception "Empty license string" but I'm providing it to the configuration like this: `endpointConfiguration.LicensePath(licensePath);` It used to work fine but started with this issue recently. The file is present at the path and it is not empty.

**Comment by bording** [comment] 2017-08-10 20:59
@dasjestyr Are you saying that your endpoint is crashing with an unhandled exception because of this? Or are you debugging and pausing on first-chance exceptions?

The place where that exception could be thrown is inside a try-catch statement which writes a "Failed to initialize the license" log entry. It shouldn't be unhandled.

> It used to work fine but started with this issue recently. The file is present at the path and it is not empty.

What changed between when it was working and now? Did you update any packages? Can you provide the full list of packages you are referencing?

**Comment by dasjestyr** [comment] 2017-08-10 21:22
I'm looking down the stream of exceptions that occur on startup and I'm feeling like this might be a deeper issue. I'm going to open a different issue as not to pollute this thread.

**Comment by wallism** [comment] 2018-07-18 03:23
I was getting the "Empty license string" error after no code changes and it had been working fine for ages.
The cause was, I had turned off the "Enable just my code" debug setting in VS. Turning it back on again fixed the issue for me.

**Comment by timbussmann** [comment] 2018-07-19 09:08
@wallism there were some changes to the internal licensing code which have caused this. As described in previous comments, this exception is nothing to worry about, as it's catched internally as well. This is currently in our backlog and an annoyance we might be able to "fix" in future versions but as of now, e recommend to not break on all exceptions but or to turn on "enable just my code" as you described.

**Comment by timbussmann** [comment] 2018-07-20 06:17
sounds good to me. Closing this then. If you see this being an issue in v7, please comment.

**Closed by timbussmann** 2018-07-20 06:17 UTC
