### ISSUE TITLE
Should the core try to handle "stalled" handlers in some way?

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#3423] opened 2016-02-05 11:59 UTC
We just had this case, https://github.com/Particular/NServiceBus.RabbitMQ/issues/125#issuecomment-180300809, where the user had a bug in his handler code causing the handler to never complete. This gave the impression that the endpoint wasn't processing messages. Rabbit in this case doesn't have any limits for how long a message can be "unacked". 

Even if there was such a timeout or this would happen on the sqltransport I think the end result would be the same. Message times out and rolls back to the queue but since the handler is still stuck there is no threads that can pick it up. v6 changes this to some extent since we no longer deal with threads, instead we have a "max concurrency" (defaults to 100 for msmq) so I think we would end up with the same behavior with a 100 stuck handlers.

Should the core try to detect and warn/handle/etc this situation in order to help users?

**Comment by andreasohlund** [comment] 2016-02-05 12:00
@Particular/nservicebus-maintainers @Particular/transport-maintainers what do you al think? (also validate that my assement is correct since I haven't tested this on other transports other than rabbit v3)

**Comment by yvesgoeleven** [comment] 2016-02-05 12:06
In azure's transports the message will roll back after 30 seconds, another thread (if any) will then pick that one up, eventually leading to either all stuck threads, or all messages deadlettered (in case of ASB)

Detecting is one thing, but you can't do anything about it as you cannot deterministically instruct a thread to stop or abort (if it is stuck it may not abort).

Secondly, what is too long? In azure I would personally say 30 seconds (however I'm also certain that our users would disagree with me as I have a common demand to extend the leases on messages in order to support longer operations)

**Comment by Scooletz** [comment] 2016-02-05 12:14
The abort actually may never happen, as a part of aborting `finally` blocks are executed, see: [abort](https://msdn.microsoft.com/en-us/library/ty8d3wta.aspx).

@yvesgoeleven you can have a timer being reset for every 'spin' of a given worker. If the timer isn't reset you `Abort` the worker thread. Wouldn't that be a solution?

**Comment by SzymonPobiega** [comment] 2016-02-05 12:59
The problem is now how to kill these handlers. If there is a case of a stalled handler the cause is most likely a serious bug in users code and the only solution is to fix the bug and redeploy. Killing stalled threads won't give us anything apart from probably somehow masking the root cause. 

I think that we should have a feature that would trigger a critical action if all threads are blocked for a given (configurable) period of time. This would give users a clue that something is off and a clear message "go look for blocking code in your handler".

**Comment by Scooletz** [comment] 2016-02-05 13:12
@SzymonPobiega Kill + trigger a critical action then maybe? 
Why do we put msgs to the error queue? Doesn't it partially support scenario when there's a bug in the code? How one can determine that 'running forever' is worse than NullReferenceException being thrown all the time? I think we can't and hence providing this ability of cancellation is another dimension of handling bugs.

**Comment by SzymonPobiega** [comment] 2016-02-05 13:18
@Scooletz critical action can be defined as killing (e.g. in NSB.Host) so I think that should cover it.

**Comment by Scooletz** [comment] 2016-02-05 13:26
@SzymonPobiega That kills the purpose of killing threads ;-) still leaving the need of measuring every single pipeline execution.

**Comment by timbussmann** [comment] 2016-02-05 15:14
> Should the core try to detect and warn/handle/etc this situation in order to help users?

So where would be the border of how much we help users identify issues with their code (e.g. memory leaks? ;) )

I think warning (e.g. logs) would probably already help. Raising critical errors would be very annoying during debugging.

**Comment by SzymonPobiega** [comment] 2016-02-05 18:38
Yeah, I didn't think about the debugging aspect. You conviced me @timbussmann

**Comment by mauroservienti** [comment] 2016-02-05 20:08
Aren't handlers by default run in a transaction scope? If so isn't the tx timeout already doing the job for us?

**Comment by andreasohlund** [comment] 2016-02-05 21:39
v6 no longer wraps in a scope, that only happens if the transports supports it, and not all users run the transports that do support it in that mode.

Also not sure that it would actually free up the thread ( yes message will go back the the input queue but that might not be enough, see the description of this issue)

**Comment by andreasohlund** [comment] 2016-02-05 21:43
>Yeah, I didn't think about the debugging aspect

:+1:

So:

```
if(!Debugger.IsAttached)
{
    Log.Warn("All your handlers have been stuck for the last X minute")
}

```

see like the only potential thing we could do?


Or could we do, "since the message receive op timed out lets kill the pipeline task" in some way?

**Comment by danielmarbach** [comment] 2016-02-05 21:49
@andreasohlund You can't "kill" a task like you shouldn't abort threads.
The proper way is to cancel operations. But if the user doesn't bother to
use the CancellationToken there is nothing we can do

**Comment by mauroservienti** [comment] 2016-02-06 06:23
Got it thanks

**Comment by danielmarbach** [comment] 2016-10-18 07:33
Closing this in favour of https://github.com/Particular/NServiceBus/issues/3785 since it has actionable items in the issue

**Closed by danielmarbach** 2016-10-18 07:33 UTC
Labels: Discussion
