### ISSUE TITLE
Deduplication does not prevent concurrent invocation of handlers for duplicate messages

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4086] opened 2016-08-24 09:39 UTC
The deduplication behavior logic currently is:
- Check if outbox record exists
- Invoke handlers
- Create outbox record

This is perfectly fine for error recovery where the same physical message is processed more than once. The handlers will only be successfully invoked once. This is because error recovery will always result in sequential processing of the same physical message.

However, if there are multiple physical copies/clones of the same message and these are processed concurrently then this behavior does not prevent successful execution of the handlers more than once. 
### Sender(s)

Send multiple message that share the same message ID.

This can happen when the sender is running in a non-transactional environment.
- Scaled out timeout manager dispatching the same timeout more than once
- Using the outbox, when delivering the transport operations more than once
- When sender sets the message id for logically the same message
- Atleast-once transports during fail-over
### Receiver

Allows for concurrent processing either because it has multiple instances running or it has increased the maximum concurrency.
## Problem

Outbox only results in transactional exact-once at the commit phase. When multiple physical copies of the same logical message are processed all copies are potentially processed in parallel.

A customer might not expect this behavior. We currently do not have deduplication logic that prevents concurrent invocation.
### A. Create dedupe feature

Instead of changing the current behavior of the outbox a new dedupe feature can be added. This also has the pro that it can be used in environments that use DTC and also have a participating transactional transport but where for example an integration can result in having logical duplicates entering the system.
### B. Change outbox dedupe behavior

Instead of doing a SELECT we can do an INSERT at the following line and that will result in the ability to dedupe physical copies in case the persistence inserts data with the correct isolation level.
- https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Outbox/OutboxDeduplicationBehavior.cs#L30

If the message fails the persistence transaction will be rolled back and the inserted record will be gone so any retries on that message instance will work.

**Comment by CrispyDrone** [comment] 2020-11-28 16:43
Is there any progress on this feature?

I've been reading [the outbox with sql persistence documentation](https://docs.particular.net/persistence/sql/outbox) and enabling pessimistic concurrency can help when you handlers are transactional, but not when they simply invoke a web service for example. 

However, I believe that this can be avoided by putting the web service invocation behind another message where the original message handler will create a "unique record" in the database that would result in a first wins behavior (and failure for all others). The message handler that wins creates this record, and sends a message. Upon retrying the failed message handler it would simply do nothing. Then the message handler for this new message could invoke the web service in a guaranteed-only-once fashion?

**Comment by tmasternak** [comment] 2022-03-14 22:36
@SzymonPobiega this is solved by pessimistic outbox right?

**Comment by SzymonPobiega** [comment] 2022-03-15 07:18
Yeah. Given that the issue is focused on SQL I think we can close it as done in https://github.com/Particular/NServiceBus.Persistence.Sql/releases/tag/6.0.0 via https://github.com/Particular/NServiceBus.Persistence.Sql/issues/37. @ramonsmits feel free to re-open if you disagree.

**Closed by SzymonPobiega** 2022-03-15 07:18 UTC
