### ISSUE TITLE
Notifications.Errors.MessageSentToErrorQueue no longer contains exception headers

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4018] opened 2016-08-05 04:04 UTC
repro by running this tests https://github.com/Particular/docs.particular.net/blob/master/Snippets/Core/Core_6/Headers/Writers/HeaderWriterError.cs

old headers

```
$.diagnostics.hostdisplayname = MACHINENAME
$.diagnostics.hostid = 8cf0a8f78f9cd1885699777c83eb631e
$.diagnostics.originating.hostid = 8cf0a8f78f9cd1885699777c83eb631e
CorrId = 3e4570f0-50f0-44bf-a519-a5eb011ad429\0
NServiceBus.ContentType = text/xml
NServiceBus.ConversationId = 0596086c-cead-4bd3-9ea3-a5eb011ad42a
NServiceBus.CorrelationId = 3e4570f0-50f0-44bf-a519-a5eb011ad429
NServiceBus.EnclosedMessageTypes = Core6.Headers.Writers.MyNamespace.MessageToSend, MyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
NServiceBus.ExceptionInfo.ExceptionType = System.Exception
NServiceBus.ExceptionInfo.HelpLink = 
NServiceBus.ExceptionInfo.Message = The exception message from the handler.
NServiceBus.ExceptionInfo.Source = Core6
NServiceBus.ExceptionInfo.StackTrace = System.Exception: The exception message from the handler.
      at Core6.Headers.Writers.HeaderWriterError.MessageHandler.Handle(MessageToSend message, IMessageHandlerContext context)
      at NServiceBus.InvokeHandlerTerminator.<Terminate>d__0.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.MutateIncomingMessageBehavior.<Invoke>d__0.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.SubscriptionReceiverBehavior.<Invoke>d__1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.MutateIncomingTransportMessageBehavior.<Invoke>d__0.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.UnitOfWorkBehavior.<Invoke>d__0.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at NServiceBus.UnitOfWorkBehavior.<Invoke>d__0.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.FirstLevelRetriesBehavior.<Invoke>d__1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at NServiceBus.FirstLevelRetriesBehavior.<Invoke>d__1.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      at NServiceBus.MoveFaultsToErrorQueueBehavior.<Invoke>d__1.MoveNext()
NServiceBus.FailedQ = HeaderWriterErrorV6@MACHINENAME
NServiceBus.FLRetries = 1
NServiceBus.MessageId = 3e4570f0-50f0-44bf-a519-a5eb011ad429
NServiceBus.MessageIntent = Send
NServiceBus.OriginatingEndpoint = HeaderWriterErrorV6
NServiceBus.OriginatingMachine = MACHINENAME
NServiceBus.ProcessingEndpoint = HeaderWriterErrorV6
NServiceBus.ProcessingMachine = MACHINENAME
NServiceBus.ReplyToAddress = HeaderWriterErrorV6@MACHINENAME
NServiceBus.TimeOfFailure = 2016-04-17 07:09:44:921763 Z
NServiceBus.TimeSent = 2016-04-17 07:09:44:882880 Z
NServiceBus.Version = 6.0.0
```

current headers

```
$.diagnostics.originating.hostid = 8cf0a8f78f9cd1885699777c83eb631e
CorrId = c3a20b4d-eb77-4b4a-88de-a65900e6aeca\0
NServiceBus.ContentType = text/xml
NServiceBus.ConversationId = 5f056f14-28f6-43ff-adde-a65900e6aee3
NServiceBus.CorrelationId = c3a20b4d-eb77-4b4a-88de-a65900e6aeca
NServiceBus.EnclosedMessageTypes = Core6.Headers.Writers.MyNamespace.MessageToSend, MyAssembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
NServiceBus.MessageId = c3a20b4d-eb77-4b4a-88de-a65900e6aeca
NServiceBus.MessageIntent = Send
NServiceBus.OriginatingEndpoint = HeaderWriterErrorV6
NServiceBus.OriginatingMachine = MACHINENAME
NServiceBus.ReplyToAddress = HeaderWriterErrorV6@MACHINENAME
NServiceBus.TimeSent = 2016-08-05 03:59:53:506881 Z
NServiceBus.Version = 6.0.0
```

**Comment by danielmarbach** [comment] 2016-08-05 05:58
Know what the problem is. We raise it in the wrong place. Will fix today

**Comment by danielmarbach** [comment] 2016-08-05 15:35
Did some investigation @SimonCropp 

I think we need to move the responsibility of raising events into the corresponding executors. Currently the responsibility is handled by the RecoverabilityExecutor but only the MoveToErrorExecutor actually has the knowledge about header customizations and exception headers. I'll send in a PR on Monday or so

**Comment by SimonCropp** [comment] 2016-08-05 21:36
Thanms

**Comment by andreasohlund** [comment] 2016-08-08 12:47
After talking to @danielmarbach @timbussmann and @SimonCropp we decided that the current behavior is correct since the event contains the `IncomingMessage` so it makes no sense to expose the headers that we're going to send out on the message going the error queue. 

Since most relevant info can already be found on the `Exception` details on the event we decided to leave this as is. Should users ask for the "metadata" that we'll be attached to the event in the future we can easily add that as a new `Dictionary<string,string> Metadata` property on the event.

### Plan of attack

* Add this info to the upgrade guide
* Modify the callstack cleaning sample to pull the callstack from the exception details instead of the headers

**Comment by andreasohlund** [comment] 2016-09-21 12:50
Sample is already changed to reflect this change. Opened a docs PR to clarify that exception details is now available as a first class citizen https://github.com/Particular/docs.particular.net/pull/1933.

Closing this as won't fix

**Closed by andreasohlund** 2016-09-21 12:50 UTC
