### ISSUE TITLE
NServiceBus Portal Page incorrectly opens

### ISSUE THREAD

**Issue by MarkHillIngram** [Particular/NServiceBus#2634] opened 2015-01-26 23:21 UTC
I think this is related to the following issue https://github.com/Particular/NServiceBus/issues/1953

essentially in some unknown situation, the solution being opened prompts the behavior to show the portal page despite things already being installed.  It does not always do this but once it is doing it on a project it simply will not stop doing it on that project.

see: https://groups.google.com/forum/#!topic/particularsoftware/ZoPyKRB-iRA

**Comment by johnsimons** [comment] 2015-01-26 23:26
Hi @MarkHillIngram 

Yes, we have been chasing this issue for a while and most time we are not able to reproduce :disappointed: 

Are you able to reproduce this issue consistently? Can you share a small repro ?

**Comment by MarkHillIngram** [comment] 2015-01-26 23:31
unfortunately the one solution I notice it on consistently is large and this may be a factor?  When I create a new project it does not seem to occur, but at some point in the future it will start happening and then I cannot seem to fix it

**Comment by johnsimons** [comment] 2015-01-26 23:32
Can you check if the solution contains multiple versions of NServiceBus
nugets ?
And what versions ?

**Comment by MarkHillIngram** [comment] 2015-01-26 23:38
no they all have the same version (4.2)

**Comment by johnsimons** [comment] 2015-02-03 02:05
@MarkHillIngram what happens if you update to latest 4.x ?

**Comment by johnsimons** [comment] 2015-02-10 04:42
@MarkHillIngram I'm closing this issue as I'm unable to replicate it.
If you able to send us a consistent reproduction, I'll reopen it.

**Closed by johnsimons** 2015-02-10 04:42 UTC
Labels: Bug, Needs: Reproduction

**Comment by MarkHillIngram** [comment] 2015-03-03 15:43
sorry I was out of the office....I don't think I can update that project to the latest right now but I will give that a try sometime this week or early next and see what happens

**Comment by johnsimons** [comment] 2015-03-04 01:53
No worries @MarkHillIngram, thank you for giving it a go, really appreciate.
