### ISSUE TITLE
Current UoW of IBuilder is not floated when configuring funcs

### ISSUE THREAD

**Issue by WilliamBZA** [Particular/NServiceBus#4744] opened 2017-05-24 13:46 UTC
The [CommonObjectBuilder.ConfigureComponent](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/ObjectBuilder/Common/CommonObjectBuilder.cs#L74) method that accepts a `Func<IBuilder, T>` always uses the same `IBuilder` instance as the parameter to the func. This effectively means that if a container represents unit of work scopes by the reference to which container instance is being used to build the object (e.g. Autofac), the object being built by the `Func` would always be tied to the root unit of work.

An example of a container which manages the unit of work scope without referencing the current container is SimpleInjector.

See a repro [here](https://github.com/Particular/NServiceBus/pull/4743).

There are a few fixes to this problem.

1. Change the signature of the `Build` methods to accept a floated current container for the current unit of work and pass the correct instance into the Build method
2. Store the current container in `AsyncLocal` (😞)
3. Allow access to the `ContextBag` from the `CommonObjectBuilder` class so that the func that is provided to the underlying container can change to use the current `childBuilder` in the `ContextBag` instead of using `this`
4. Document that this method signature does not respect unit of work scoping

**Comment by WilliamBZA** [comment] 2017-05-24 13:48
If I fake the correct scoping by storing a reference to the latest childScope created within the CommonObjectBuilder class, making sure that scope is never disposed, and changing the repro to send messages far enough apart that the scopes aren't overwritten, then the repro acceptance test passes.

**Comment by andreasohlund** [comment] 2017-06-19 07:03
@timbussmann I know you've done some research , should the breaking changes proposed be considered for v7?

**Comment by timbussmann** [comment] 2017-06-26 06:53
@andreasohlund I think this is something which needs to be fixed (maybe even needs to be considered as backport).

@WilliamBZA any updates on this? based on your comment on the repo:
> I'll close this once I've completed that and submit a proper PR to fix.

**Comment by WilliamBZA** [comment] 2017-06-26 07:15
Not yet @timbussmann, it is currently number 2 on my todolist to kick off again once I have capacity again. I am fairly confident your proposed API is the correct move, it's only that autofac ugliness that I want to try work around, but if needs be that can also be a minor or patch release in the future.

**Comment by timbussmann** [comment] 2017-06-26 07:20
thanks for the info @WilliamBZA. I'll assign the issue to you for now as you stated your intentions to address this. Please let us know if you need some help.

**Comment by WilliamBZA** [comment] 2017-07-05 18:07
The `container-madness` branch has a valid fix. I'll neaten it up and submit a PR.

**Comment by timbussmann** [comment] 2017-07-10 07:57
Verified using the test from #4827 that LightInject is not affected by this. According to @WilliamBZA no other supported container besides autofac is. To fix autofac, we need a breaking API change, there doesn't seem to be a way around that. The alternative is to not fix it and document this and recommend users to use autofacs native API instead (that should work fine, I assume @WilliamBZA ?).

**Comment by timbussmann** [comment] 2017-07-10 08:47
Although the acceptance test provided by @WilliamBZA passes with lightinject, I had a feeling that something is off regardless and it's not related to autofac itself, so I wrote this test which fails on the commented assertions. I think this is a repro of the scenario you're describing @WilliamBZA ?

        [Test]
        public void Configure_with_builder_factory()
        {
            var builder = new CommonObjectBuilder(new LightInjectObjectBuilder());

            builder.ConfigureComponent<UowScopeDependency>(DependencyLifecycle.InstancePerUnitOfWork);
            builder.ConfigureComponent(b => new InstancePerCallWithUowDependency(b.Build<UowScopeDependency>()), DependencyLifecycle.InstancePerCall);

            var rootScopeInstance1 = builder.Build<InstancePerCallWithUowDependency>();
            var rootScopeInstance2 = builder.Build<InstancePerCallWithUowDependency>();

            InstancePerCallWithUowDependency childBuilder1Instance1;
            InstancePerCallWithUowDependency childBuilder1Instance2;
            using (var childBuilder1 = builder.CreateChildBuilder())
            {
                childBuilder1Instance1 = childBuilder1.Build<InstancePerCallWithUowDependency>();
                childBuilder1Instance2 = childBuilder1.Build<InstancePerCallWithUowDependency>();
            }

            InstancePerCallWithUowDependency childBuilder2Instance1;
            InstancePerCallWithUowDependency childBuilder2Instance2;
            using (var childBuilder2 = builder.CreateChildBuilder())
            {
                childBuilder2Instance1 = childBuilder2.Build<InstancePerCallWithUowDependency>();
                childBuilder2Instance2 = childBuilder2.Build<InstancePerCallWithUowDependency>();
            }

            // check instance per call instances
            Assert.AreNotSame(rootScopeInstance1, rootScopeInstance2);
            Assert.AreNotSame(childBuilder1Instance1, childBuilder1Instance2);
            Assert.AreNotSame(childBuilder2Instance1, childBuilder2Instance2);

            Assert.AreNotSame(rootScopeInstance1, childBuilder1Instance1);
            Assert.AreNotSame(rootScopeInstance1, childBuilder2Instance1);

            Assert.AreNotSame(childBuilder1Instance2, childBuilder2Instance2);

            // check dependency references
            Assert.AreSame(rootScopeInstance1.dependency, rootScopeInstance2.dependency);
            Assert.AreSame(childBuilder1Instance1.dependency, childBuilder1Instance2.dependency);
            Assert.AreSame(childBuilder2Instance1.dependency, childBuilder2Instance2.dependency);

            Assert.AreNotSame(rootScopeInstance1.dependency, childBuilder2Instance1.dependency); // fails: are same
            Assert.AreNotSame(rootScopeInstance1.dependency, childBuilder2Instance1.dependency); // fails: are same
            Assert.AreNotSame(childBuilder1Instance1.dependency, childBuilder2Instance1.dependency); // fails: are same

            // check instantiation count
            Assert.AreEqual(6, InstancePerCallWithUowDependency.InstanceCounter);
            Assert.AreEqual(3, UowScopeDependency.InstanceCounter); // fails: 1
        }

        class InstancePerCallWithUowDependency
        {
            // ReSharper disable once NotAccessedField.Local
            public readonly UowScopeDependency dependency;

            public static int InstanceCounter;

            public InstancePerCallWithUowDependency(UowScopeDependency dependency)
            {
                this.dependency = dependency;
                Interlocked.Increment(ref InstanceCounter);
            }
        }

        class UowScopeDependency
        {
            public static int InstanceCounter;

            public UowScopeDependency()
            {
                Interlocked.Increment(ref InstanceCounter);
            }
        }

**Comment by WilliamBZA** [comment] 2017-07-11 10:39
@timbussmann that test seems better, but assumes that the test project has access to the `CommonObjectBuilder` et al, which only the NServiceBus.Core project will have. None of the other container solutions will be able to run that test 😢

**Comment by timbussmann** [comment] 2017-07-11 11:00
@WilliamBZA yeah I know but I think I'll be able to somehow reproduce the captured root context issue on a shareable test, will investigate once we're clear how to proceed on core.

also something which would be fixed with my spike #4832 💃

**Comment by timbussmann** [comment] 2020-09-28 09:22
it looks like the test described in https://github.com/Particular/NServiceBus/issues/4744#issuecomment-314044308 passes after switching to the new DI seam with NServiceBus v8. Closing this issue.

**Closed by timbussmann** 2020-09-28 09:22 UTC
Labels: Bug
