### ISSUE TITLE
IAmStartedByMessage should require a mapping

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2442] opened 2014-10-06 08:29 UTC
Validate that all sagas that has a IAmStartedByMessage<TMessage> also has a mapping for the TMessage

**Comment by andreasohlund** [comment] 2015-10-19 19:55
Reading through this issue and especially my own comment, https://github.com/Particular/NServiceBus/issues/2442#issuecomment-59034989, I think we're over complicating this.

Forgetting to map messages that start a saga is IMO the no.1 misstake by new users, ok perhaps no.2 after [forgetting to assign the correlated property](#313). With this in mind I think we should keep it simple by requiring all messages that can start a saga have one of the following:
1. A property mapping
2. A customer finder
3. A "ack" that the user don't need a mapping at all and a new saga will always be created.

The above would make the users aware of the misstake to forget a mapping and also make the code more explicit for the ones that are fine with a new saga instance beeing created all the time.

This would IMO have a `Medium` impact with a `Small` effort.

Api could be:

```
void ConfigureHowToFindSaga(SagaPropertyMapper<MySaga> mapper)
{
                    mapper.CreateNewSagaInstanceForEach<StartSagaMessage>();
}

```

Thoughts?

**Comment by johnsimons** [comment] 2015-10-20 00:09
@andreasohlund just wondering, inorder for a saga to start it needs to have at least one starting message is this right ?
If it is, then why not make the saga contract more explicit, and define that contract as part of the ctor of the saga class ? This way users cannot forget it.

**Comment by andreasohlund** [comment] 2015-10-20 07:25
>inorder for a saga to start it needs to have at least one starting message is this right ?

That is correct

>If it is, then why not make the saga contract more explicit, and define that contract as part of the ctor of the saga class ? 

Not following, can you show how the code would look like?

**Comment by johnsimons** [comment] 2015-10-20 21:58
@andreasohlund something like:
```c#
class MySaga : Saga<MyData> ....
{
    void MySaga() : base(typeof(StartSagaMessage1), typeof(StartSagaMessage2), ...)
    {

    }
}
```

We can polish it more

**Comment by andreasohlund** [comment] 2015-10-21 06:59
I think we're overthinking this, why not just check that the saga implements at least on `IAmStartedByMessages` ?

**Comment by andreasohlund** [comment] 2015-10-21 07:01
So the following should be validated:

1. A saga should have at least one `IAmStartedByMessges`
2. Each `IAmStartedBy` should have a mapping (see https://github.com/Particular/NServiceBus/issues/2442#issuecomment-149328113)
3. The saga should have a handler for each mapped message

**Comment by johnsimons** [comment] 2015-10-21 07:05
The issue I see is that we have an API that is only validated at runtime vs compile time.
If we can design an API that drives the user into the path of success as part of writing the code, that to me is a lot better.

By the way, if a saga has to implement at least one `IAmStartedByMessages`, then why not make that part of the `Saga` class?

**Comment by andreasohlund** [comment] 2015-10-21 07:12
>The issue I see is that we have an API that is only validated at runtime vs compile time.

Can't we use Roslyn to check that each class inheriting from Saga<T> also implements at least one `IAmStartedByMessages` ? (cc @hmemcpy @SimonCropp )

**Comment by johnsimons** [comment] 2015-10-21 07:14
@andreasohlund I am sure we can but don't u think it would be better to make our API safe by design ?

**Comment by hmemcpy** [comment] 2015-10-21 07:15
@andreasohlund hmm, I don't see why not, should be possible. But 2015+ only (to actually display the warning)

**Comment by andreasohlund** [comment] 2015-10-21 07:19
> API safe by design

Yes definitely

But we also have to consider the cost as well, having the users repeat them selfves is also a problem

```
class MySaga : Saga<MyData>,IAmStartedBy<StartSagaMessage1>,IAmStartedBy<StartSagaMessage2>
{
    void MySaga() : base(typeof(StartSagaMessage1), typeof(StartSagaMessage2), ...)
    {

    }
   ConfigureHowToFindSaga(mapper)
         mapper.ConfigureMapping<StartSagaMessage1>()...
}
```

This api is noisy and forces the user to repeat himself IMO?

You can also get out of sync since the ctor approach can only check that you have at least one? What should we do if the user forgets the last typeof(StartSagaMessage2) ?

**Comment by johnsimons** [comment] 2015-10-21 07:21
@andreasohlund I didn't say that was the final proposal, we can iterate on that and make it beautiful.
How about we get together and have a go at it ?

**Comment by andreasohlund** [comment] 2015-10-21 07:27
>How about we get together and have a go at it ?

:+1:

**Comment by hmemcpy** [comment] 2015-10-21 07:29
For ReSharper users, we can do a trick that forces them to implement (at least) one interface of `IAmStartedBy`:

![image](https://cloud.githubusercontent.com/assets/601206/10630339/a37ac160-77de-11e5-85a2-c5666d5b8994.png)

**Comment by andreasohlund** [comment] 2016-06-28 16:36
@DavidBoike this is done right?

**Comment by DavidBoike** [comment] 2016-06-28 16:37
Yep closing

**Closed by DavidBoike** 2016-06-28 16:37 UTC
Labels: Type: Feature
