### ISSUE TITLE
V5: StackoverflowException when using DefineCriticalErrorAction 

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3542] opened 2016-03-02 13:58 UTC
Setting a custom critical error handler will result in a `StackoverflowException` when the circuitbreaker trips.

http://docs.particular.net/nservicebus/hosting/critical-errors#a-possible-custom-implementation

    BusConfiguration busConfiguration = new BusConfiguration();
    busConfiguration.DefineCriticalErrorAction(OnCriticalError);

## Expected behavior

The callback should result in the ability to recover from a circuit breaker activation. Recover as in, dispose all occupied resources by the instance and possibly swap the bus instance with a fresh newly created instance.

## How to reproduce

1. Open [pubsub sample](http://docs.particular.net/samples/pubsub/)
2. Add empty `DefineCriticalErrorAction(..)`
3. Start endpoint
4. Stop or kill the MSMQ service

Now you get the  `StackoverflowException` and the process dies.

## References

- https://groups.google.com/forum/#!topic/particularsoftware/VgXe9wHM0o4

**Comment by timbussmann** [comment] 2016-03-02 17:20
was unable to reproduce the StackoverflowException by the steps you provided. CPU usage went quite high (due to insane polling by MSMQ I suspect?) but no SOE. How long did it take for the Exception to occur?

> Recover as in, dispose all occupied resources by the instance and possibly swap the bus instance with a fresh newly created instance.

I don't think CriticalErrorAction is intended for such use cases. I think it is mainly a hook to provide your own notifications and cleanup rather than keeping the bus alive. A critical error usually means a non-recoverable error which requires a restart of the bus.

**Comment by ramonsmits** [comment] 2016-03-02 17:41
After I saw a 5 exceptions of the MSMQ transport if took max. 3 seconds to get the SOE. I'll re-run it and make sure.

> A critical error usually means a non-recoverable error which requires a restart of the bus.

Restarting the bus is exactly what I mean with recovering. Disposing all resources and creating a whole new bus instance with `Bus.Create(BusConfiguration)`.

**Comment by danielmarbach** [comment] 2016-03-02 18:18
Are you reusing the same bus configuration?

On Wednesday, March 2, 2016, Ramon Smits <notifications@github.com> wrote:

> After I saw a 5 exceptions of the MSMQ transport if took max. 3 seconds to
> get the SOE. I'll re-run it and make sure.
>
> A critical error usually means a non-recoverable error which requires a
> restart of the bus.
>
> Restarting the bus is exactly what I mean with recovering. Disposing all
> resources and creating a whole new bus instance with
> Bus.Create(BusConfiguration).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3542#issuecomment-191344584>
> .
>


-- 
*Don't miss the Async/Await Webinar Series*
*• Learn more <http://go.particular.net/l/27442/2016-02-15/681bjl> →*

**Comment by ramonsmits** [comment] 2016-03-02 18:56
@danielmarbach I'm not re-using anything I can't build any logic for recovery as just adding an empty callback results in a SOE :-). To still answer that, no, as the bus configuration is not reusable too.

**Comment by andreasohlund** [comment] 2016-03-03 10:39
Empty critical error action seem like an invalid use case to me since that would keep the transport spinning (churning CPU like @timbussmann said).

Arguably we could flip the transports into some kind of "fault" mode that are less aggressive in the future?

This has been discussed here: https://github.com/Particular/PlatformDevelopment/issues/267

**Comment by danielmarbach** [comment] 2016-03-11 12:48
@ramonsmits can you verify if the same problem exists in v6?

**Comment by danielmarbach** [comment] 2016-03-11 12:50
Closing this as 'Won't fix' since I agree with @timbussmann and @andreasohlund 

> Empty critical error action seem like an invalid use case to me since that would keep the transport spinning (churning CPU like @timbussmann said).

**Closed by danielmarbach** 2016-03-11 12:50 UTC
Labels: Type: Bug, Withdrawn: Won't Fix

**Comment by ramonsmits** [comment] 2016-03-11 16:16
This is strange @danielmarbach, so what should a end user do to prevent the SOE? Doing anything in it still results in a SOE?

I mention *empty* to identify that the critical handler is not mistakenly invoking itself that would result in a SOE.

**Comment by ramonsmits** [comment] 2016-03-16 09:04
@andreasohlund @timbussmann So how to fix this SOE?

**Comment by timbussmann** [comment] 2016-03-16 09:10
@ramonsmits stopping the bus or implementing a custom circuit breaker mechanism.

**Comment by andreasohlund** [comment] 2016-03-16 09:10
We agreed that an empty critical error action is not a valid use case. If user do that they will get 100% cpu on MSMQ (not sure how other transports behave). @ramonsmits you got a SOE ex which arguably might be better since that kills the endpoint. I don't see how we can detect the users doing a no-op in there so I don't think we can do more?

I'd say this is not important enough to fix, let's not spend any more time on this?
