### ISSUE TITLE
SLR and Saga Database Triggered Handlers?

### ISSUE THREAD

**Issue by acgentry** [Particular/NServiceBus#3161] opened 2015-12-02 23:06 UTC
Context: SLR Enabled, Saga Processing Failure, Two Machines Pointing to Same Saga Repository Versions: NServiceBus 5.2.10, NServiceBus.RabbitMQ 2.1.2, NServiceBus.NHibernate 6.2.5

I searched the documentation and I find no reference to this "feature" so my assumption is that there is a bug in how Sagas are persisted and processed/triggered outside of messages/events.  

The situation is that if I am developing on my local machine using local private RabbitMQ, but pointing to a shared database for Saga Persistence, if the SLR completes its retries locally, my second machine (in this case a dev server running a windows service) suddenly starts to pickup the saga and begins processing.  I am unable to reliably recreate the situation, but if I dont share the database no issues arise.  

I should be able to develop locally and use local queues, with the messages being the only trigger for Sagas, but it seems this is not the case.

**Comment by acgentry** [comment] 2015-12-02 23:32
I believe the root cause is in how the TimeoutEntity table is being leveraged, almost as if its ignoring the Destination suffix (i.e. MyQueue@LocalMachine vs. MyQueue@ServerMachine) in the tracking, each service racing to get the message after the timeout and the second server grabbing it.

**Comment by danielmarbach** [comment] 2016-03-16 09:41
@acgentry What you describe is by design. The two endpoints sharing the database become competing consumer since the represent the same logical endpoint. You'd need two distinct saga persistence databases to not see this effect.

I'm closing this one.

**Closed by danielmarbach** 2016-03-16 09:41 UTC
