### ISSUE TITLE
NullReference Exception on Startup When Using DataBus with Existing StructureMap Child Container

### ISSUE THREAD

**Issue by dennismsmith** [Particular/NServiceBus#4968] opened 2017-09-22 12:37 UTC
When starting an endpoint, a NullReferenceException occurs if the following conditions are met:

1.  Using StructureMapBuilder with an existing container that happens to be a StructureMap child container (as distinguished from an NServiceBus child container which is a StructureMap nested container)
2. Using the DataBus feature

I have been able to reproduce this with NServiceBus 6 both with the generic host and when self-hosted.

NServiceBus 6.4.0
NServiceBus.Host 7.0.2
NServiceBus.StructureMap 6.0.0
StructureMap 4.5.2

I had previously successfully used child containers with Unity, but have recently switched to StructureMap and started encountering this error.

A minimal repro of this problem can be found at:  https://github.com/dennismsmith/NServiceBusStructureMapDataBusError

Note that the order of initializing the DataBus and the container doesn't matter; the error occurs in both cases.  If you switch the container to not be a child container, NServiceBus will start correctly, but that breaks some other use cases in my application.

The stack trace is as follows:

`2017-09-22 08:31:29.380 FATAL NServiceBus.GenericHost Exception when starting endpoint.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Features.DataBus.IDataBusInitializer.OnStart(IMessageSession session) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\DataBus\DataBus.cs:line 54
   at NServiceBus.Features.FeatureStartupTaskController.Start(IBuilder builder, IMessageSession messageSession) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureStartupTaskController.cs:line 21
   at NServiceBus.Features.FeatureActivator.<StartFeatures>d__5.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<StartFeatures>d__2.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.GenericHost.<Start>d__1.MoveNext() in C:\BuildAgent\work\fc89e968acb99302\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 49
Exception thrown: 'System.NullReferenceException' in NServiceBus.Host.exe
Exception thrown: 'System.NullReferenceException' in mscorlib.dll
2017-09-22 08:31:29.397 FATAL NServiceBus.Hosting.Windows.WindowsHost Start failure
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.Features.DataBus.IDataBusInitializer.OnStart(IMessageSession session) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\DataBus\DataBus.cs:line 54
   at NServiceBus.Features.FeatureStartupTaskController.Start(IBuilder builder, IMessageSession messageSession) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureStartupTaskController.cs:line 21
   at NServiceBus.Features.FeatureActivator.<StartFeatures>d__5.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<StartFeatures>d__2.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.GenericHost.<Start>d__1.MoveNext() in C:\BuildAgent\work\fc89e968acb99302\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Hosting.Windows.WindowsHost.Start() in C:\BuildAgent\work\fc89e968acb99302\src\NServiceBus.Hosting.Windows\WindowsHost.cs:line 32
The program '[29140] NServiceBus.Host.exe' has exited with code -1 (0xffffffff).
`

**Comment by timbussmann** [comment] 2017-09-22 13:15
hey @dennismsmith 
Thanks a lot for the repro sample 👍 It indeed seems to be related to the child container. The IDataBus implementation registered by the `DataBusFileBased` feature doesn't seem to be resolved correctly.
@Particular/container-maintainers can you chime in?

**Comment by boblangley** [comment] 2017-09-23 00:57
@timbussmann Correct. The DataBus property is not being injected.

@dennismsmith StructureMap does not support using setter injection policies defined in a child container: https://github.com/structuremap/structuremap/issues/596#issuecomment-317722797. NServiceBus still uses setter injection to populate dependencies, which requires the NServiceBus.StructureMap to [create those policies](https://github.com/Particular/NServiceBus.StructureMap/blob/develop/src/NServiceBus.StructureMap/ConfigurationExpressionExtensions.cs#L11) for each type registered in the container it is using.

**Comment by timbussmann** [comment] 2017-09-25 11:25
@boblangley if we change https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DataBus/DataBus.cs#L48 to use ctor injection, this would solve this specific exception. While this still means that we don't support property injection in that case (because that's a structuremap issue), it should allow to use a child container as mentioned by @dennismsmith ?

**Comment by boblangley** [comment] 2017-09-25 13:39
@timbussmann Should we check downstreams to see if any rely on setter injection and fix those as well?

**Comment by timbussmann** [comment] 2017-09-26 06:50
@boblangley that would make sense imho (could also be that there is still more setter injection used in core).

**Comment by timbussmann** [comment] 2017-09-27 10:02
I verified that with the changes in #4973 the endpoint should start correctly.

**Comment by timbussmann** [comment] 2017-09-28 11:21
v7 will no longer use property injection to initialize the databus and therefore this issue shouldn't occur anymore. With v6 there currently seems to be no way to work around this while using the databus, but given that @boblangley mentioned that there are issues with property injection and child containers, it seems like this would remain an officially unsupported scenario. thoughts @boblangley ?

@dennismsmith can you share some more details why you want to use a child container for nservicebus? Can you avoid the child container and pass the main container as the existing container instance instead?

**Comment by dennismsmith** [comment] 2017-09-28 14:23
@timbussmann: The reason that we are using child containers is that we are self-hosting multiple endpoints in the same process.  We register all of our general application configuration in the parent container, and then create a child container for each endpoint.  When we started self-hosting multiple endpoints in the same process in NServiceBus 5 using Unity, we found the the endpoints would insert conflicting mappings into the container.  I don't remember the exact details of what the conflicts we saw were since we made those changes several years ago.

**Comment by mauroservienti** [comment] 2017-09-28 15:57
Another possible approach is to switch to a container, such as Castle.Windsor, that supports child containers and constructor injection and property injection on the same resolved conponent

**Comment by timbussmann** [comment] 2017-10-04 15:45
@dennismsmith were you able to find an acceptable workaround until v7 is released?

**Comment by dennismsmith** [comment] 2017-10-05 13:37
@timbussmann - I'm just in the process of testing it now, but it looks like switching to having a completely separate container for each endpoint appears to have worked.

**Comment by timbussmann** [comment] 2017-10-05 14:23
@dennismsmith that's good to hear 👍 I'll close this issue but please comment in case you encounter some problems with that approach. We're sorry about the extra effort you had to take to get your solution working with structuremap. Your initial attempt will work in v7 in case you strongly prefer to use child containers again.

**Closed by timbussmann** 2017-10-05 14:23 UTC
Labels: Bug

**Comment by imperugo** [comment] 2018-11-19 17:00
I don't know if it is related or not, but I've the same issue using MsDepedency Injection 

https://docs.particular.net/nservicebus/dependency-injection/msdependencyinjection

Switching to autofac it works

**Comment by timbussmann** [comment] 2018-11-19 19:50
@imperugo do you have some sample code which reproduces the issue you're seeing?

**Comment by imperugo** [comment] 2018-11-21 15:07
@timbussmann more ore less I can write something, but give me few days. I'm in a middle of something bigger than me
