### ISSUE TITLE
Configure a default Error Queue

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#3647] opened 2016-03-30 14:41 UTC
Currently, users have to configure an error queue in order for an endpoint to startup correctly. If no error queue is configured, NServiceBus throws an exception on start.

This has a huge impact on the first time experience since they will almost certainly run into this exception as there is currently no way to ensure the existence of that configuration value at compile time. Also, for most first time users, configuring an error queue is most probably to complex and uninteresting when just playing around with NSB.

I think we should configure a default error queue name (to define, "error"?) instead of forcing users to create one.

**Comment by SimonCropp** [comment] 2016-03-30 19:55
-1  defaulting queue names means people are not made aware of a decision they should make very early on

**Comment by andreasohlund** [comment] 2016-03-30 21:12
We can have the Development transport default it to "error" as a middle ground?

**Comment by SimonCropp** [comment] 2016-03-30 21:12
ahh the mythical  "Development transport"

**Comment by andreasohlund** [comment] 2016-03-30 21:14
it's just one failing test away from me removing the [WIP] :)

**Comment by timbussmann** [comment] 2016-03-31 08:00
> -1 defaulting queue names means people are not made aware of a decision they should make very early on

@SimonCropp According to our vision/strategy, First Time Experience is one of the most important aspects. I'm not sure if I agree that users should mind about the location of their error queue very early on? It's a configuration value, means you can basically change it any time, why is it required early on?

**Comment by andreasohlund** [comment] 2016-03-31 08:01
The development storage could default to "error" making it just work for first time users.

We could also let each transport default since for all transports other than MSMQ "error" is just fine

**Comment by tmasternak** [comment] 2016-04-04 12:43
First time users experience is not a main goal of the V6 release. This can be tackled as part of that initiative when we start it.

/cc: @boblangley @danielmarbach

**Comment by SimonCropp** [comment] 2016-04-21 06:25
i would prefer @colin-higgins endpoint generation site to be the thing that removes the friction of the first time user experience. that and the bootstrapping nuget. not compromising API (used in the long term) on the alter of initial user experience (only valuable in the short term)

**Comment by danielmarbach** [comment] 2016-10-26 08:52
@SimonCropp What would be the drawback of having a default error queue name set to 'error' queue? I tried to reflect about your statement https://github.com/Particular/NServiceBus/issues/3647#issuecomment-203607192 and figured it matters only when we assume a centralized error queue. Unfortunately when I skimmed through the doco page I could not find clear guidance why you'd want to have a centralized error queue. Under that light setting a default error queue would not be harmful, right?

For all non-store and forward transports a default error queue name with "error" would be a good fit more a large portion of our user base.

**Comment by timbussmann** [comment] 2016-10-26 08:52
> -1 defaulting queue names means people are not made aware of a decision they should make very early on

@SimonCropp I'm not really sure how "aware" me make users by forcing them to configure a string. There is no further information about a "decision they should make" by that API.

regarding @andreasohlund idea about the dev transport: That essentially means, error queue configuration would become a transport responsibility. This could make sense since broker based transports require less "decisions" to make (just the name of the queue in almost all cases) compared to msmq.

**Comment by SeanFeldman** [comment] 2016-10-26 16:52
I might be off, so please correct me if I'm wrong.
When dealing with system queues (that's what we ended up calling them with @andreasohlund), it [was assumed](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/335#issuecomment-248388786) that in the next major/s we'll not create any of those. Those queues should be created by the users. Is that something that should be considered for this discussion?

**Comment by timbussmann** [comment] 2016-10-27 06:28
@SeanFeldman I think for that there are more changes required until we completely skip queue creation (e.g. the "development transport").

**Comment by dbelcham** [comment] 2016-11-24 15:19
Talking to @timbussmann and we came up with the following thoughts/ideas:

The current experience for a new (or any) user when creating a new endpoint is one that sees them think that they have done what is necessary to create an operating endpoint only to have it error on them during the first run. There is no feedback prior to endpoint startup that outlines what may be missing. The API by itself doesn't provide any context about why an error queue is required to have an operational endpoint. When a user is trying to start their first endpoint with NServiceBus understanding the reasons _why_ an error queue is required is not necessarily their primary concern. They will have it as a concern at some point, but not during the first attempt to run their endpoint. Because of this, having a default error queue value configured would make that part of the experience have less friction from an operational standpoint and a conceptual one.

* the only scenario where a default error queue name would not be a reasonable choice is when using MSMQ + centralized error queue + Service Control
* all other transports could use a default error queue name without issues
* it seems to make sense that the transport would define any default error queue name. Nobody knows better what could be valid (i.e. valid naming conventions, characters, ect) for a transport than the transport itself
* if default queue naming is delegated to the transport, MSMQ could decide that it doesn't want to use a default value and instead require explicit error queue names to be provided during endpoint configuration

Does anyone else see any downsides from using a default error queue in the manner explained above?

ping @Particular/nservicebus-maintainers @SimonCropp @SeanFeldman

**Comment by SeanFeldman** [comment] 2016-11-24 17:48
A new developer is going through an exploratory development. If they learn early on that an error queue is required and the _reason_ why it's required, then we've accomplished 2 things
1. Taught developer about error queue API
1. Seeded the idea of failing messages and potential need to address those

Current exception message looks like the following (with a minor spelling issue, [PR created](https://github.com/Particular/NServiceBus/pull/4334)):

> Faults forwarding requires an error queue to be specified.
> Take on of the following actions:
> - set the error queue at configuration time using 'EndpointConfiguration.SendFailedMessagesTo()'
> - add a 'MessageForwardingInCaseOfFaultConfig' section to the app.config
> - configure a global error queue in the registry using the powershell command: Set-NServiceBusLocalMachineSettings -ErrorQueue {address of error queue}"

While I agree that it's inconvenient to run into an exception for a missing API call to define an error queue, I do think (with perhaps an improved error message) this is the right approach.

**Comment by dbelcham** [comment] 2017-02-01 19:24
@Particular/nservicebus-maintainers do we want to move on this in anyway or has the discussion run it's course and no action will be taken?

**Comment by danielmarbach** [comment] 2017-02-01 20:07
I'm torn to be honest. From one perspective I don't like the F5, boom exception approach but on the other hand it serves an educational purpose like @SeanFeldman described. I'd say let's close it for now, not important enough

**Comment by SeanFeldman** [comment] 2017-02-01 21:26
Before the issue is closed, wanted to bring [Evaluate MSBuild integrated installers](https://github.com/Particular/PlatformDevelopment/issues/1100) issue raised by @SimonCropp.

I have a weird feeling of a déjà vu. We tend to change our minds on core things (pun intended) more often than we should. We talk about "system queues" when it's important to [drive a discussion towards a standardized design](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/335#issuecomment-248388786), just to say "it's not important enough" later.

**Comment by andreasohlund** [comment] 2017-02-02 07:32
> I don't like the F5, boom exception approach but on the other hand it serves an educational purpose 

Not convinced that the educational value is high enough to warrant this friction, for all transports other than MSMQ `error` is just fine for production use. For msmq you would have to change yes but it would not be message loss. 

If we had the development transport we would have it default to `error` I guess?

How about we have each transport set a default if possible and only throw if there is none? (Ie we would only throw for msmq)

**Comment by timbussmann** [comment] 2017-02-02 08:48
I'm still +1 on using a default error queue.

> Not convinced that the educational value is high enough to warrant this friction

this. The current API is a huge pita. It's easy to forget for existing users, it's unclear what it is for for new users and at that point, I don't think it's the right time to educate them about the error queue. Starting with a new library and first thing is getting an exception is such a bad experience.

> for all transports other than MSMQ error is just fine for production use. 

why isn't error not fine for msmq? I think the only case is when using SC, because you need to point at the shared error queue, but that's a different fish to fry and not something which needs to be the cores responsibility (and imho not even the transport's). This is an issue for better SC integration in general.

**Comment by danielmarbach** [comment] 2017-02-02 10:15
@andreasohlund why does every transport need to set it? Just because of MSMQ? 

Then I'd prefer to use it set by default in the core and MSMQ can add a log warn or something similar if it detects it was not explicitly set.

**Comment by andreasohlund** [comment] 2017-02-02 13:44
That sounds a good and achieves the same goal

**Comment by andreasohlund** [comment] 2017-03-29 13:29
Just adding that we should at least add a backdoor to allow the upcoming development transport to specify a default error and audit queue, no need to burden the users with this. A wellknown settings key would be good enough

**Comment by andreasohlund** [comment] 2017-04-25 08:36
After recent discussion we've decided to go ahead and make the core default to `error` but have MSMQ require an explicit value to be set,

This means that all other transport will no longer need the error queue to be configured.

See https://github.com/Particular/NServiceBus/pull/4636/files for more details

Is anyone opposed to this move please chime in

**Comment by andreasohlund** [comment] 2017-04-25 08:36
Assigned to `6.3.0`

**Comment by SeanFeldman** [comment] 2017-04-25 15:36
So as of `6.3.0` samples should stop using `endpointConfiguration.SendFailedMessagesTo(errorQueueName);`

**Comment by timbussmann** [comment] 2017-04-25 15:50
only if they are not running with MSMQ. But I wonder whether we want to remove them explicitly from the samples, the argument was that we still want to raise a much awareness of the error queue as possible and as the user can't forget to add it, it's fine to keep them on the existing samples I think. But no strong opinion.

**Comment by andreasohlund** [comment] 2017-04-25 17:38
My plan was to remove them, for all transports other than msmq the config
is just noise?

Less code in samples that at not relevant to the sample it self == good
thing IMO

**Closed** 2017-04-27 21:26 UTC
