### ISSUE TITLE
No publisher address could be found for message type

### ISSUE THREAD

**Issue by dasjestyr** [Particular/NServiceBus#4420] opened 2017-01-09 21:43 UTC
"No publisher address could be found for message type DAS.Infrastructure.Messaging.Event.Notifications.NotificationSentEvent. Ensure the configured publisher endpoint has at least one known instance."

This error is thrown on startup. In this case, the publisher is a SendOnly endpoint. If I add it to the UnicastBusConfig, then it fails because it can't find the queue. The SendOnly endpoint doesn't appear to be creating a queue.

I'm using the 6.1.1 nuget package with SqlServer transport and NHibernate persistence. 

Any ideas? I saw this was a problem in a previous issue but was supposedly solved in a 6.0.* branch.

**Comment by danielmarbach** [comment] 2017-01-09 22:13
Hi

A send-only endpoint doesn't have a local queue. Since you have a SqlServer
transport you are using message driven pubsub. In message driven pubsub if
an endpoint has a handler for an event it sends a subscription message to
the publisher endpoint. Since your endpoint doesn't have a local queue
there is no way NServiceBus can send out a subscription message to the
publisher (store-and-forward) to indicate it wants messages delivered
(since the receiving queue is not available). That's why this scenario is
not supported.

Hope that helps

Jeremy Stafford <notifications@github.com> schrieb am Mo. 9. Jan. 2017 um
21:43:

**Comment by dasjestyr** [comment] 2017-01-09 22:32
So I should just configure this endpoint as a regular endpoint then?

**Comment by danielmarbach** [comment] 2017-01-09 22:46
Yeah that's what I'd do. If you don't have requirements which require
send-only I think it makes sense to switch to a regular endpoint

Jeremy Stafford <notifications@github.com> schrieb am Mo. 9. Jan. 2017 um
22:32:

**Comment by dasjestyr** [comment] 2017-01-09 23:01
Swell. So no it's throwing that "Could not enumerate all types for..." exception. I guess this isn't related to this issue, but it has been suggested in the past that I exclude scanned types to get around this, but that is unacceptable since I'd have to exclude about 100 assemblies in this solution (legacy application) and AssembliesToScan() is being taken out. Is there another way to fix this?

**Comment by MarcinHoppe** [comment] 2017-01-09 23:55
@dasjestyr @danielmarbach One other option to consider is to have a separate endpoint (a regular one) to manage subscription requests and have the send only endpoints use the same NHibernate-based persistent subscription storage as this regular endpoint.

Please take a look at this documentation section here that describes such a setup:

https://docs.particular.net/nservicebus/hosting/publishing-from-web-applications#storage-driven-transport-topology

**Comment by danielmarbach** [comment] 2017-01-10 09:10
@dasjestyr sorry to hear that is now throwing the "could not enumerate all types" exception. In Version 6 of NServiceBus we moved from the inclusion model to the exclusion model. The exception you got should show you the assemblies that cannot be scanned and you can exclude them from scanning like described on the following documentation page. 

https://docs.particular.net/nservicebus/hosting/assembly-scanning#exclude-a-list-approach-exclude-specific-assemblies-by-name

**Comment by danielmarbach** [comment] 2017-01-10 11:48
Can you also make sure that you have the publisher correctly registered either in the message endpoint mapping or by using the code first API as described here https://docs.particular.net/nservicebus/messaging/routing#event-routing-message-driven

**Comment by dasjestyr** [comment] 2017-01-10 16:49
I had intended to pull the culprit assemblies out of the exception messages, but they're only displaying one at a time, so I have to keep restarting, failing, and grabbing the exception for every assembly that poses a problem. Luckily, it wasn't every assembly causing a problem, but I'd consider logging that as an issue/annoyance.

In the meanwhile, I got it running and receiving messages. Now I'm having a different exception:

`NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from transport message 724abde6-cac2-4fc6-ac40-a6f7010bcd0c ---> System.Exception: Could not find metadata for 'Newtonsoft.Json.Linq.JObject'.\u000d\u000aEnsure the following:\u000d\u000a1. 'Newtonsoft.Json.Linq.JObject' is included in initial scanning. \u000d\u000a2. 'Newtonsoft.Json.Linq.JObject' implements either 'IMessage', 'IEvent' or 'ICommand' or alternatively, if you don't want to implement an interface, you can use 'Unobtrusive Mode'`

I've had this one before. My conventions are setup to include anything that ends with 'event' and it's working fine between the other services.  Here's something else I don't quite understand:

```
	"NServiceBus.TimeOfFailure" : "2017-01-10 16:34:32:827644 Z",
	"NServiceBus.FailedQ" : "DAS.Services.Surveys.Write@[dbo]",
	"NServiceBus.ProcessingMachine" : "DASWEB1",
	"NServiceBus.ProcessingEndpoint" : "DAS.Services.Surveys.Read",
	"$.diagnostics.hostid" : "a1ef97271706b8cf80df4f5aba5f048c",
	"$.diagnostics.hostdisplayname" : "DASWEB1"
```

The way that I'm reading this is that the machine named DASWEB1 is trying to process the event at the endpoint called DAS.Services.Surveys.Read and that message is being read out of the DAS.Services.Surveys.Write queue. Is that correct? If so, I'm even more confused. DASWEB1 is shut down, so I don't see how it could be processing anything. And event it was, I don't know why Surveys.Read is trying to process it as it isn't subscribed to anything. Here's the full exception: http://pastebin.com/YnwiwS8g

Can someone explain this? Also, if there's a user group or discord/slack channel that would be better to post in (hopefully as responsive), let me know.

**Comment by andreasohlund** [comment] 2017-01-10 18:45
The `NServiceBus.EnclosedMessageTypes` header is the one that contains the message type of the incoming message. Looking at the exception it seems to be:

```
DAS.Infrastructure.Messaging.Event.Shared.AddonConfigurationSetEvent, DAS.Infrastructure.Messaging, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null
```

Can you confirm that the `AddonConfigurationSetEvent` message is include in your convention and that the assembly is correct? (you might need assembly redirects if the asm version differs)

>The way that I'm reading this is that the machine named DASWEB1 is trying to process the event at the endpoint called DAS.Services.Surveys.Read and that message is being read out of the DAS.Services.Surveys.Write queue. Is that correct? 

That seems correct, looking at the headers the message originated at:

```
"NServiceBus.OriginatingMachine" : "UJSTAFFORD"
    "NServiceBus.OriginatingEndpoint" : "DASAPI" 
```

Processing failed at the endpoint:

```
    "NServiceBus.ProcessingMachine" : "DASWEB1",
    "NServiceBus.ProcessingEndpoint" : "DAS.Services.Surveys.Read",
```

But the queue where it failed in was 

```
"NServiceBus.FailedQ" : "DAS.Services.Surveys.Write@[dbo]",
```

Could it be that either: 

1. DAS.Services.Surveys.Read is in someway configured to read from the DAS.Services.Surveys.Write queue? ( To my knowledge this is not possible in v6)
2. The message has failed previously and have been retried/manually moved to the wrong queue? ( @Particular/servicecontrol-maintainers can you confirm that we strip the FailedQ header on retries via ServiceControl)

You seems to be using the sqlserver transport is that correct?
Are you using ServicePulse/ServiceControl to manage your error queue?

**Comment by dasjestyr** [comment] 2017-01-11 04:06
Yeah it's sqlserver transport. I checked everything and I don't see anything that would indicate 1. or 2.. I didn't move any messages to any queues. Very bizarre. I just licensed yesterday, so I haven't gotten set up with servicepulse yet. I'm not even sure where to grab it, but it was on the todo list.

**Comment by andreasohlund** [comment] 2017-01-11 07:56
Is the problem consistent? 

Does your endpoint process other messages as expected?

**Comment by dasjestyr** [comment] 2017-01-12 02:18
Consistent no. I see this one happen during development and the only way to correct it is usually to clear all of the queues and retry the request

**Comment by andreasohlund** [comment] 2017-01-12 07:46
@Particular/sqlserver-transport-maintainers any ideas?

**Comment by MarcinHoppe** [comment] 2017-01-12 07:55
I'm not sure this is transport specific. Does the issue go away when switching to a different transport, e.g. MSMQ?

**Comment by SzymonPobiega** [comment] 2017-01-12 07:57
@dasjestyr can you post your endpoint setup code?

**Comment by dasjestyr** [comment] 2017-01-12 22:44
@MarcinHoppe I haven't tried MSMQ

@SzymonPobiega 

```
config.SendFailedMessagesTo("error");
config.MakeInstanceUniquelyAddressable(descriminator);
config.UseContainer<WindsorBuilder>(customizations =>
{
    customizations.ExistingContainer(container);

});
config.UseSerialization<NewtonsoftSerializer>();
config.AddDeserializer<NewtonsoftSerializer>();

config.UsePersistence<NHibernatePersistence, StorageType.Sagas>();
config.UsePersistence<NHibernatePersistence, StorageType.Subscriptions>();
config.UsePersistence<NHibernatePersistence, StorageType.Timeouts>();
config.UsePersistence<NHibernatePersistence, StorageType.Outbox>();
config.UsePersistence<NHibernatePersistence, StorageType.GatewayDeduplication>();
config.EnableOutbox();

config.UseTransport<SqlServerTransport>();
config.EnableInstallers();
```

**Comment by SzymonPobiega** [comment] 2017-01-16 08:44
@dasjestyr 

> I've had this one before. My conventions are setup to include anything that ends with 'event' and it's working fine between the other services. Here's something else I don't quite understand:

The endpoint config you posted seems to not have to convention set up?

**Comment by danielmarbach** [comment] 2017-01-16 09:43
@dasjestyr 

you could also simplify it by removing

`config.AddDeserializer<NewtonsoftSerializer>();`

and replacing
```

config.UsePersistence<NHibernatePersistence, StorageType.Sagas>();
config.UsePersistence<NHibernatePersistence, StorageType.Subscriptions>();
config.UsePersistence<NHibernatePersistence, StorageType.Timeouts>();
config.UsePersistence<NHibernatePersistence, StorageType.Outbox>();
config.UsePersistence<NHibernatePersistence, StorageType.GatewayDeduplication>();
```

with 

`config.UsePersistence<NHibernatePersistence>();`

and as @SzymonPobiega pointed out if you are not using `IMessage`, `IEvent` and so on you need to setup the conventions properly.

**Comment by dasjestyr** [comment] 2017-01-16 18:01
@SzymonPobiega @danielmarbach  They're set up in a different process. I have that stuff in a shared library to share between microservices. They just allow anything that ends in "Event" for events.

**Comment by danielmarbach** [comment] 2017-01-17 08:00
@dasjestyr Could you send me a repro solution to daniel dot marbach at particular dot net. Maybe this is the fastest way to get you unstuck.

**Comment by dasjestyr** [comment] 2017-01-17 17:54
@danielmarbach I'm actually not stuck at the moment. As I mentioned earlier, I just cleared all the tables/queues and it started working. I think since then, it's just been a commentary on how I tend to get into these unusable states. I'm trying to pay more attention to it so that I can capture the conditions if/when it happens again.

So to recap, from time to time, I get that deserialization error and I have no idea why. Up until this point, I've had to clear the queues in order to get it working again.

**Comment by danielmarbach** [comment] 2017-01-18 06:51
That almost sounds like an assembly scanning issue. Does it happen on endpoint restarts or even when the endpoint is running for a longer period of time? The fact that you need to clear the queues is very bizare and shouldn't happen. After all we want to provide you a robust and reliable solution. Can you send me the full log files when it happens again?

**Comment by dasjestyr** [comment] 2017-01-18 17:35
I will. I usually run into it when I'm developing new messages for a new feature. I just finished this one up, so it could be a little bit before the next one. I'm sure my frustration will remind me to come back here to post. There was another potentially related issue where when my nuget package (containing the events and commands) would break everything because the assembly version didn't match. I read that it should only break if a minor version is incremented, which wasn't the case and was resulting in the same deserialization errors. I'm going to move some things around for maintainability and revisit that scenario. Maybe I can stir something up.

**Comment by mikeminutillo** [comment] 2017-01-19 03:50
> @Particular/servicecontrol-maintainers can you confirm that we strip the FailedQ header on retries via ServiceControl

I can confirm. There is a list of headers that get stripped out [here](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Retries/RetryProcessor.cs#L18) and `NServiceBus.FailedQ` is on the list. That list is used to construct the set of headers for retry [here](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Retries/RetryProcessor.cs#L184) and those are used to construct the `TransportMessage` that is retried [here](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/Recoverability/Retries/RetryProcessor.cs#L205).

**Comment by andreasohlund** [comment] 2017-01-25 10:22
@dasjestyr we're closing this issue for now, just reopen it should you find more clues to why you're seeing this behavior

**Closed by andreasohlund** 2017-01-25 10:22 UTC
Labels: Discussion
