### ISSUE TITLE
Registering busConfiguration.DefineCriticalErrorAction callback results in StackOverflowException

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#2762] opened 2015-06-25 21:58 UTC
The doco mention that you can register a callback so that the host can get notified when the bus decides to shutdown:

http://docs.particular.net/nservicebus/hosting/critical-errors#custom-handling

Adding the callback results in a StackOverflowException

## To reproduce:

* Register a very simple callback in a console self host (f.e. console self host from the doco samples) 
* Start the host
* Stop the MSMQ windows service

Following is the initialization from the modified sample:

```
        BusConfiguration busConfiguration = new BusConfiguration();
        busConfiguration.EndpointName("Samples.SelfHosting");
        busConfiguration.UseSerialization<JsonSerializer>();
        busConfiguration.EnableInstallers();
        busConfiguration.UsePersistence<InMemoryPersistence>();
        busConfiguration.DefineCriticalErrorAction(OnCriticalError);

        using (IBus bus = Bus.Create(busConfiguration).Start())
        {
            while (true)
            {
                try
                {
                    Console.WriteLine("\r\nBus created and configured; press any key to stop program\r\n");
                    if (Console.ReadKey().Key == ConsoleKey.Escape) return;
                    bus.SendLocal(new MyMessage());
                }
                catch
                {
                    Console.WriteLine("Boem!");
                }
            }
        }
```

**Comment by danielmarbach** [comment] 2016-03-11 12:46
Duplicate of https://github.com/Particular/NServiceBus/issues/3542

**Closed** 2016-03-11 12:46 UTC
Labels: Withdrawn: Duplicate
