### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by nickpts** [Particular/NServiceBus#5220] opened 2018-07-24 11:20 UTC
I get the following error when closing some long running threads:

> Logger: NServiceBus.ExpiredTimeoutsPoller
> Message: Failed to fetch timeouts from the timeout storage
> Exception: System.ObjectDisposedException: Cannot access a disposed object.
> Object name: 'ExpiredTimeoutsPoller'.
>    at NServiceBus.ExpiredTimeoutsPoller.ThrowIfDisposed()
>    at NServiceBus.ExpiredTimeoutsPoller.SpinOnce(CancellationToken cancellationToken)
>    at NServiceBus.ExpiredTimeoutsPoller.<InnerPoll>d__10.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NServiceBus.ExpiredTimeoutsPoller.<Poll>d__9.MoveNext()

I need to understand why this is happening when I do not have recoverability options turned on. This is the code. 

When initilaising:

```c#
var endpoint = _baseContainer.GetInstance<IEndpointInstance>();
foreach (var eventType in _eventsToSubscribeTo)
{
    endpoint.Subscribe(eventType);
}
```

Main method:

```c#
private static IEndpointInstance CreateEndpointInstance(IContext ctx, string instance)
{
    var someEndpointConfig= ctx.GetInstance<ServiceBusEndpointSection>("someEndpoint");
    var someOtherEndpointConfig= ctx.GetInstance<ServiceBusEndpointSection>("someOtherEndpoint");
    var persistenceConfig = ctx.GetInstance<ServiceBusSqlServerPersistenceSection>("persistence");
    var transportConfig = ctx.GetInstance<ServiceBusSqlServerTransportSection>("transport");

    var endpointConfiguration = new NServiceBus.EndpointConfiguration($"{someEndpointConfig.Name}.{instance}");
    endpointConfiguration.DisableFeature<AutoSubscribe>();

    endpointConfiguration.SendFailedMessagesTo("error");
    endpointConfiguration.AuditProcessedMessagesTo("audit");
    endpointConfiguration.EnableInstallers();
    endpointConfiguration.Recoverability().Delayed(settings => settings.NumberOfRetries(0));
    endpointConfiguration.LimitMessageProcessingConcurrencyTo(1);

    LogManager.Use<Log4NetFactory>();

    endpointConfiguration.Recoverability().Immediate(immediate => { immediate.NumberOfRetries(0); });
    //endpointConfiguration.Conventions().DefiningEventsAs(t => t != null && t.Namespace.StartsWith("CompanyName") && t.Namespace.EndsWith(".Events"));

    // Configure Transport 
    var transport = endpointConfiguration.UseTransport<SqlServerTransport>()
        .ConnectionStringName(transportConfig.ConnectionStringName)
        .DefaultSchema(transportConfig.Schema)
        .UseSchemaForQueue("error", transportConfig.Schema)
        .UseSchemaForQueue("audit", transportConfig.Schema);

    transport.Transactions(TransportTransactionMode.ReceiveOnly);

    foreach (var eventType in _eventsToSubscribeTo)
    {
        transport.Routing().RegisterPublisher(eventType, someOtherEndpointConfig.Name);
    }

    // Configure persistence
    var connectionString = ConfigurationManager.ConnectionStrings[persistenceConfig.ConnectionStringName];
    var hibernateConfig = new NHibernate.Cfg.Configuration();
    hibernateConfig.DataBaseIntegration(x =>
    {
        x.ConnectionString = connectionString.ConnectionString;
        x.Dialect<MsSql2012Dialect>();
    });
    hibernateConfig.SetProperty("default_schema", persistenceConfig.Schema);

    var connection = endpointConfiguration.UsePersistence<NHibernatePersistence>();
    connection.UseConfiguration(hibernateConfig);

    endpointConfiguration.UseContainer<StructureMapBuilder>(c => c.ExistingContainer(ctx.GetInstance<IContainer>()));
    return Endpoint.Start(endpointConfiguration).ConfigureAwait(false).GetAwaiter().GetResult();           
}
```

In dispose method:

```c#
var endpoint = _baseContainer.GetInstance<IEndpointInstance>();
if (endpoint != null)
{
    foreach (var eventType in _eventsToSubscribeTo)
    {
        endpoint.Unsubscribe(eventType);
    }
}

_baseContainer.Dispose();
```

**Comment by adamralph** [comment] 2018-07-25 09:29
@nickpts btw you should do the same thing with your calls to `Subscribe`.

**Comment by nickpts** [comment] 2018-07-30 08:16
Thank you, I will give this a go. 
However, can you help me understand what is going on internally? The error itself does not point towards a problem with awaitable subscribe/unsubscribe.

**Comment by adamralph** [comment] 2018-07-30 14:45
@nickpts the problem is that if you don't `await` the unsubscribe calls, they could still be running while the container is shut down, which results in objects being disposed by the container shutdown, and then calls into those objects relating to unsubscribing. You could potentially encounter similar, but different problems if you don't `await` the subscribe calls.

**Comment by danielmarbach** [comment] 2018-08-14 15:15
@nickpts I'm closing this issue. Feel free to reopen if the above proposals don't fix it or raise other issues if you have follow up questions.

**Closed by danielmarbach** 2018-08-14 15:15 UTC

**Comment by nickpts** [comment] 2018-09-05 09:07
@danielmarbach, sorry for reopening but I am still getting the exception. 

Any other suggestions other than using core betas with the analyzer?

**Comment by danielmarbach** [comment] 2018-09-05 09:41
@nickpts the core 7.1.x and 6.5.x contains the analyzers. RTM has been shipped. No need to use the beta versions anymore. Can you try to add those analyzers and see if there is anything missing in your code and then report back here?
