### ISSUE TITLE
Saga ReplyToOriginator stopped working with 5.2

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus#2748] opened 2015-06-09 15:28 UTC
### Symptoms

Callbacks are not invoked for replies perfomed using `saga.replyToOriginator`. Instead the message goes into the error queue with a `No handlers found for message` exception

### Who's affected

All users using `ReplyToOriginator` in combination with callbacks

### Original report
After upgrading from NSB 4.8 to 5.2 the Saga->ReplyToOriginator(Msg) stopped working. Instead the Message ends up in the Error queue with a "no handler found" exception.

The transportation method used is Azure ServiceBus, created a fresh test-project to verify this behaviour, that can be found here, http://halan.blob.core.windows.net/debug/NSB5_SagaReplyIssueR1.zip

**Comment by andreasohlund** [comment] 2015-06-09 16:55
@SeanFeldman could this be a ASB specific bug ? (acceptance tests on the core seems to be green)

**Comment by SeanFeldman** [comment] 2015-06-09 20:26
@danielHalan get 404 when trying to download the repro. Is that a private blob by any chance?

**Comment by danielHalan** [comment] 2015-06-09 20:28
Fixed

**Comment by yvesgoeleven** [comment] 2015-06-10 12:11
Looks like the message intent on the Replied message is Send and not Reply

**Comment by SimonCropp** [comment] 2015-06-10 12:14
@yvesgoeleven that is what i got here. http://docs.particular.net/nservicebus/messaging/message-headers#reply-headers-example-reply-headers  
but note that doco is generated from real headers. so if this is a bug then the doco would also include that bug

**Comment by yvesgoeleven** [comment] 2015-06-10 12:19
This seems to be a duplicate of https://github.com/Particular/NServiceBus/pull/1974

**Comment by yvesgoeleven** [comment] 2015-06-10 12:21
@SimonCropp that's not what I'm seeing in @danielHalan 's repro

**Comment by yvesgoeleven** [comment] 2015-06-10 12:37
So what happens is:

MessageIntent is set to Send instead of Reply
Causing CallbackInvocationBehavior to skip the message
Instead LoadHandlersBehavior goes looking for regular handlers, and can't find any
Throwing the exception

**Comment by andreasohlund** [comment] 2015-06-10 13:00
Turns out that this is causing v5 callback to not fire. After talking to @yvesgoeleven and @SimonCropp we decided to hotfix v5.

Assigning to 5.2.2 milestone

**Closed** 2015-06-11 14:26 UTC
Labels: Bug

**Comment by yvesgoeleven** [comment] 2015-06-12 11:50
Hi @danielHalan 

Version 5.2.2 has just been released to nuget, which fixes the ReplyToOriginator issues.

However, even with this fix, your sample won't run as you would expect, I had to make a few changes in order to get it going properly.
* The sample makes use of multiple serial callbacks and also uses ReplyToOriginator multiple times. Now ReplyToOriginator has been designed to always reply to the callback of the message from which the saga originated, hence both replies would attempt to get back to the first callback and in case of a reply to the second command it cannot find that callback anymore as it had already been invoked. So instead of using ReplyToOriginator the second time in the saga you should have been using bus.Reply  so that it replies to the callback that send the second message.
* Secondly I also had issues with the waithandles used in the controller. Your controller waits for completion of the first waithandle, while it should have waited until the ResponseText was set. So I also changed that to use a ManualResetEvent instead of the AsyncWaitHandle of the AsyncResult.

Can I upload you the code somewhere?

**Comment by danielHalan** [comment] 2015-06-12 20:23
@yvesgoeleven Great, sure, maybe easiest to PM me on Twitter with a OneDrive/Dropbox link
