### ISSUE TITLE
DateTimeOffset timezone information incorrectly deserialized when using JsonSerializer resulting in corruption

### ISSUE THREAD

**Issue by danielHalan** [Particular/NServiceBus#4355] opened 2016-11-30 08:45 UTC
## Who's affected

* Everyone using `JsonSerializer` in combination with messages that contain `DateTimeOffset `properties.

## Symptoms

Noted that an object's DateTimeOffset property get converted to the running servers UTC timezone when sent. (Using "JsonSerializer", and ASB)

i.e. if Server is UTC+5, and DateTimeOffset is 12:00+1, it gets converted to 16:00, resulting in "2016-12-01T16:00:00+05:00"

## Steps to reproduce

To verify that this is not an issue with Json.Net serializer, I've extracted the settings used in NSB.JsonSerializer, and Serialize the Command-object just before sending it to the Bus, and when serialized it shows the Correct unmodified Serialization with UTC+1 timezone

        var str = Newtonsoft.Json.JsonConvert.SerializeObject(cmd, new JsonSerializerSettings {
          TypeNameAssemblyFormat = FormatterAssemblyStyle.Simple,
          TypeNameHandling = TypeNameHandling.None,
          Converters =
                    {
                        new IsoDateTimeConverter
                        {
                            DateTimeStyles = DateTimeStyles.RoundtripKind
                        }
                    }
        });.

## Plan of Attack
- [x] Announcement https://github.com/Particular/Announcements/pull/98
- [x] Fix in 6.1 #4367 
- [x] Backport to 6.0.4 #4379 
- [x] Backport to 5.2.21 #4374

**Comment by danielmarbach** [comment] 2016-11-30 13:33
@danielHalan by NSB.JsonSerializer you mean our internal or our external serializer nuget package?

**Comment by danielmarbach** [comment] 2016-11-30 13:33
@Particular/azure-maintainers can you chime in on this one to brainstorm whether this is ASB or Core related?

**Comment by danielHalan** [comment] 2016-11-30 14:08
internal, NServiceBus.JsonSerializer, NServiceBus.Core

**Comment by timbussmann** [comment] 2016-11-30 14:53
I think this could be related: https://github.com/JamesNK/Newtonsoft.Json/issues/744

need to test this.

**Comment by danielmarbach** [comment] 2016-11-30 15:28
We are investigating this @danielHalan We need to have a closer look especially for backwards compatibility on the wire.

Would it be possible for you in the meantime to switch to the external json serializer? There you can change the serializer settings

https://docs.particular.net/nservicebus/serialization/newtonsoft#usage-custom-settings

**Comment by danielHalan** [comment] 2016-12-01 02:16
Ok, will look into it, also we are using NServiceBus v5.2.19

**Comment by SeanFeldman** [comment] 2016-12-01 04:57
@danielmarbach this is message serialization. Transport doesn't modify payloads.

**Comment by danielmarbach** [comment] 2016-12-01 11:53
@danielHalan @timbussmann already made some good progress. We are tracking it down to the IsoDateTimeConverter. The external json serializer also has the DateTime converter. You have to make sure that you specify the settings explicitly in order to avoid the code that adds it. We will work on a fix in the meantime.

**Comment by timbussmann** [comment] 2016-12-01 13:02
https://github.com/Particular/NServiceBus/pull/4367 fixes this for v6.1. 
I still need to verify the behavior of the NServiceBus.Newtonsoft.Json package.
As described by @danielHalan this also seems to be the behavior in v5, I need to see whether we can address it in the first place (e.g. maybe not possible due to to old json version) or what kind of workaround would be available.

**Comment by timbussmann** [comment] 2016-12-01 15:26
@danielHalan as a workaround for both v5 and v6 right now, you would need to use the `NServiceBus.Newtonsoft.Json` package as it allows custom configuration of the serializer. In v5 the configuration would look like this:

            var serializer = configuration.UseSerialization<NewtonsoftSerializer>();
            serializer.Settings(new JsonSerializerSettings());

note that you need to set the settings to override the default settings using the IsoDataConverter. In case you're also using XML properties in your message, it might be required to configure additional settings.

@Particular/nservicebus-maintainers same changes would be required for v5, should we backport these changes?

**Comment by andreasohlund** [comment] 2016-12-01 18:28
>same changes would be required for v5, should we backport these changes?

Given that there is a workaround and that you would find this during development(?) I'd say no backport?

**Comment by danielHalan** [comment] 2016-12-02 12:21
NServiceBus.Newtonsoft.Json 1.0 has dependency to NSB6, only v0.3.0 available for NSB5, is v0.3 production ready?

**Comment by danielHalan** [comment] 2016-12-02 12:50
Checked using v0.3.0, but it didn't change the serialized DateTimeOffset, used following settings,

      var serializer = cfg.UseSerialization<NewtonsoftSerializer>();
      serializer.Settings(new JsonSerializerSettings() {
        DateFormatHandling = DateFormatHandling.IsoDateFormat,
        DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind
      });

also seems as the settings was not considered, as when changed DateFormatHandling to MicrosoftDateFormat, which should result in "\/Date(1198908717056)\/" format, it still produced ISO8601-string.

**Comment by andreasohlund** [comment] 2016-12-02 12:53
>only v0.3.0 available for NSB5, is v0.3 production ready

Even if it was we can't see usage of a non stable package as a viable workaround, so in that case need to backport? (cc @Particular/nservicebus-maintainers )

**Comment by SimonCropp** [comment] 2016-12-02 20:09
I don't think the 0.x version of the external nsb.json serializer should be considered production ready. The API in 0.x nugets should not be considered stable and we are unlikely to back port any fixes to it.

**Comment by andreasohlund** [comment] 2016-12-03 07:05
Makes sense, so we need to backport the fix to the core 5.2.X given that this corrupts messages

**Comment by danielmarbach** [comment] 2016-12-05 07:50
@Particular/nservicebus-maintainers I'm going to backport it

**Comment by danielmarbach** [comment] 2016-12-05 14:26
Update the plan of attack. This probably needs more backporting. Waiting for https://github.com/Particular/NServiceBus.Serializers.CompatTests/pull/1 to reach to a conclusion

**Comment by bording** [comment] 2016-12-06 16:09
@danielHalan This fix will be in the 6.1 release, and we have backported it to 6.0.4 and 5.2.21, which are available on NuGet now.

**Closed by bording** 2016-12-06 16:09 UTC
Labels: Bug

**Comment by danielHalan** [comment] 2016-12-10 19:02
Hi, can still reproduce the issue with NSB 5.2.21, I've created an test project available here, https://www.dropbox.com/s/fx7ek02ummekr83/NSB_JsonTest5.zip?dl=0

**Comment by bording** [comment] 2016-12-10 22:24
@danielHalan Taking a quick look at your sample, I only see code that sends the message. It appears that the endpoint that receives the message wasn't included. Has the receiving endpoint been upgraded to 5.2.21 as well? If not, you won't see the behavior fix, because the problem isn't on the sending/serializing side, it's on the receiving/deserializing side.

**Comment by danielHalan** [comment] 2016-12-14 11:05
Can confirm it worked with both ends updated. 

First checked only if the message had correct TimeZone for the DateTime (T16:00:00+XX:00) when serialized and sent to the bus, but see that there is a solution changing the time of the message.

**Comment by bording** [comment] 2016-12-14 20:38
@danielHalan Glad to hear it's working for you!
