### ISSUE TITLE
EndPoint.Start throws System.ArgumentException 

### ISSUE THREAD

**Issue by joproulx** [Particular/NServiceBus#5348] opened 2019-03-22 20:18 UTC
NServiceBus version: 7.1.6
.Net Core 3.0

The following exception occurs when trying to run a WPF project (.Net Core 3.0) based on the "Getting started" example. The exception is thrown at the Endpoint.Start() method:

```
var endpointConfiguration = new EndpointConfiguration("ClientUI");
var transport = endpointConfiguration.UseTransport<LearningTransport>();
var endpointInstance = await Endpoint.Start(endpointConfiguration).ConfigureAwait(false);
```

Here is the exception:

```
System.ArgumentException
  HResult=0x80070057
  Message=Empty path name is not legal.
Parameter name: path
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at NServiceBus.AssemblyValidator.ValidateAssemblyFile(String assemblyPath, Boolean& shouldLoad, String& reason)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.TryLoadScannableAssembly(String assemblyPath, AssemblyScannerResults results, Assembly& assembly)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies()
   at NServiceBus.EndpointConfiguration.Scan(AssemblyScanner assemblyScanner)
   at NServiceBus.EndpointConfiguration.GetAllowedTypes(String path)
   at NServiceBus.EndpointConfiguration.Build()
   at NServiceBus.Endpoint.Create(EndpointConfiguration configuration)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NServiceBusTests.MainWindow.<StartAsync>d__3.MoveNext() in F:\Dev\Tests\NServiceBusTests\NServiceBusTests\MainWindow.xaml.cs:line 69
```

After investigating, the following call [AppDomain.CurrentDomain.GetData("TRUSTED_PLATFORM_ASSEMBLIES") ](https://github.com/Particular/NServiceBus/blob/65fee422bdd79a3e5d4adc3dcc40353cb5b9dd82/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L92), on my machine and with .NET Core 3.0, returns a string terminated by a separator ';' character. When [this is being split](https://github.com/Particular/NServiceBus/blob/65fee422bdd79a3e5d4adc3dcc40353cb5b9dd82/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L96), the last item of the array will therefore be an empty string. This will ultimately make the File.OpenRead throws because the filepath is empty.

(Please note that I have tested with .Net Core 2.2 and I don't have this separator character at the end of the string in that case)

A quick fix would be to use `StringSplitOptions.RemoveEmptyEntries` option when [splitting the assembly string](https://github.com/Particular/NServiceBus/blob/65fee422bdd79a3e5d4adc3dcc40353cb5b9dd82/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L96)

**Comment by bording** [comment] 2019-03-22 22:50
@joproulx Thanks for the report. Using .NET Core 3.0 preview 3, I see the same behavior you are seeing.

Before we make any changes here, I think it makes sense to file an issue against the CoreCLR repo to see if this was an intentional change or not. If it wasn't, then there should be plenty of time to get it fixed for .NET Core 3.0 since it's not due to be released for a while.

Since you've already spent time looking into this, would you like to file an issue at https://github.com/dotnet/coreclr to ask about it? If not, I'll be happy to do it and link to it here.

**Comment by joproulx** [comment] 2019-03-25 19:57
@bording Thanks for the reply. FYI: Bug was opened and was added to the .Net Core 3.0 milestone.

So I guess I'll use .Net Core 2.2 until then :)

**Comment by bording** [comment] 2019-03-25 20:27
@joproulx I'll be sure to follow the issue and see what the outcome is.

**Comment by bording** [comment] 2019-04-18 22:32
.NET Core 3.0 Preview 4 is out, and I've just confirmed that the fix is in there and NServiceBus is working! 🎉

I'm going to go ahead and close this. Thanks for reporting it!

**Closed by bording** 2019-04-18 22:32 UTC
