### ISSUE TITLE
Using non-FIPS compliant encryption (MD5)

### ISSUE THREAD

**Issue by richardmatsu** [Particular/NServiceBus#1217] opened 2013-05-31 18:26 UTC
MD5 encryption is being used in RavenPersistenceConstants. MD5 is not FIPS compliant.

See this thread for details:

http://tech.groups.yahoo.com/group/nservicebus/message/19200

**Comment by AndrewInScotland** [comment] 2015-04-22 17:29
I'm picking up on richardmatsu's work (same project).
We are still experiencing the same issue with FIPS compliance. The problem is in UnicastBus's constructor, where it calls GenerateDefaultHostId. This uses the DeterministicGuid class, which uses MD5. It looks like this is the only place that uses MD5. 
Is there any update on this issue? We are still stuck on 4.3.8.

**Comment by johnsimons** [comment] 2015-04-22 23:34
@AndrewInScotland what version do you want to upgrade to?
If you upgrade to v5.1.2 or above, you can override the HostId as explained in http://docs.particular.net/nservicebus/hosting/override-hostid#how-do-i-override-an-endpoint-host-identifier

Is this feasible for you ?

**Comment by andreasohlund** [comment] 2015-04-23 06:42
Not sure that would work since I think FIPS just checks if there is code
that uses MD5 and doesn't care if it's not being called  :(

**Comment by SimonCropp** [comment] 2015-04-23 06:44
@andreasohlund i dont think so. look at the stack trace
```
of the Windows Platform FIPS validated cryptographic algorithms.
at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
at NServiceBus.Persistence.Raven.RavenPersistenceConstants.DeterministicGuidBuilder(String input)
at NServiceBus.ConfigureRavenPersistence.RavenPersistence(Configure config)
at NServiceBus.Hosting.Windows.Profiles.Handlers.ProductionProfileHandler.NServiceBus.Hosting.Profiles.IHandleProfile.ProfileActivated()
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at NServiceBus.Hosting.Profiles.ProfileManager.ActivateProfileHandlers()
at System.Collections.Generic.List`1.ForEach(Action`1 action)
at NServiceBus.Configure.Initialize()
at NServiceBus.Hosting.GenericHost.Start()
```

only throws when that line is hit

**Comment by andreasohlund** [comment] 2015-04-23 08:37
Got it, thanks!

**Comment by andreasohlund** [comment] 2015-04-23 08:40
@AndrewInScotland @richardmatsu Have you guys seen this one:

http://blogs.technet.com/b/secguide/archive/2014/04/07/why-we-re-not-recommending-fips-mode-anymore.aspx

what's your take on this?

I'm not trolling here just want to get your view on this since it will help us alot to assess if we want to support FIPS or not.

**Comment by AndrewInScotland** [comment] 2015-04-24 03:07
It's a compelling argument. FIPS doesn't guarantee anything. The problem
is that some of our government and military customers may not see things
in the same light.

The fix looks fairly straightforward to me. Use SHA1 instead of MD5. We
could change the Create method in the DeterministicGuid class as follows:

        public static Guid Create(params object[] data)
        {
            // use SHA1 hash to get a hash of the string
            const int GuidSize = 16;
            var inputBytes = Encoding.Default.GetBytes(String.Concat(data));
            var hashBytes = new
SHA1CryptoServiceProvider().ComputeHash(inputBytes);
            // resize the array to 16 bytes to match guid size
            Array.Resize(ref hashBytes, GuidSize);
            // generate a guid from the hash
            return new Guid(hashBytes);
        }

My initial test indicates this works for our purposes, but there may be
something I haven't thought of.

**Comment by andreasohlund** [comment] 2015-04-24 06:51
Got it, thanks for keeping us in the loop!

**Comment by SimonCropp** [comment] 2015-04-24 07:24
@AndrewInScotland the main reason preventing us from doing that is that it is a significant breaking change

**Comment by AndrewInScotland** [comment] 2015-04-24 14:58
Maybe we can find a way to make it optional, to support both?

In response to an earlier query: yes, it's the use of MD5 (not its
presence) that violates FIPS.

I have looked at the offered workaround, but it won't work for us.
See the constructor in NServiceBus.Features.UnicastBus. It calls
GenerateDefaultHostId when it sets up the Defaults, which in turn calls
DeterministicGuid. This default value is later overridden by the
previous call to UniquelyIdentifyRunningInstance (as recommended by the
link), so the behavior is almost correct. It's just the Defaults trigger
a FIPS violation.

**Comment by mauroservienti** [comment] 2015-04-28 08:53
@johnsimons 

> If you upgrade to v5.1.2 or above, you can override the HostId as explained in http://docs.particular.net/nservicebus/hosting/override-hostid#how-do-i-override-an-endpoint-host-identifier

that does not work, I tested it and we have a case regarding that (#10388), the fact is that the `UnicastBus` `Feature` class sets up defaults meaning that the default implementation, that utilizes `MD5`, is still called at start up regardless of the fact that you are overriding or not the endpoint host identifier.

**Comment by johnsimons** [comment] 2015-04-28 22:23
@mauroservienti yeah that is disappointing, I guess we need to re-evaluate this in the next major release, I'll raise an issue about it.

**Comment by areicher** [comment] 2015-08-13 16:09
Is [#2721](https://github.com/Particular/NServiceBus/issues/2721) the last known remaining barrier to running in FIPS mode?  Is there any chance #2721 fixed in a 5.x release instead of needing to wait for the next version (or is there some other workaround)?  This has suddenly become a pretty important issue for us.

**Comment by areicher** [comment] 2015-08-26 21:09
I found in addition to the host ID, there are a a number of MD5 hash usages in the NServiceBus.Raven implementation - including subscription and Saga ids.  If I hack those out I'm able to run while using FIPS mode without any problems; however, I don't have a clean solution.  If a pluggable ID generation scheme was used (as described for Sagas here: #2445), it would allow those of us that are subjected to this (draconian) setting to continue using NServiceBus while not causing maintenance issues for Particular or migration issues for everyone else...

**Comment by danielmarbach** [comment] 2015-09-09 20:41
Please see this PR which backports the V6 changes to v5 

https://github.com/Particular/NServiceBus/pull/2872

**Comment by andreasohlund** [comment] 2015-09-13 08:47
@danielmarbach since its released do we close this one?

**Comment by danielmarbach** [comment] 2015-09-13 09:12
Not released yet. Hotfix branch is there but I need to tidy up the required
sections and then kickoff the release



-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by danielmarbach** [comment] 2015-09-13 13:00
HostId fix is Released with 5.2.6

**Comment by DavidBoike** [comment] 2015-09-17 14:09
To sum up before closing this issue:

As a matter of product strategy, we will not be investing any effort into supporting FIPS mode, nor will we officially support it.

Fully supporting FIPS compliance would require so much more than swapping out a few encryption algorithms. For instance, MD5 is not FIPS compliant, and should never be used for hashing passwords or secretive data. But we use MD5 extensively for hashing already clear-text data. In some cases, as with our RavenDB persistence library, these hashes become part of unique keys stored in a database.

It's our duty to our customers to maintain backward compatibility with this long-lived data, and so swapping out the MD5 algorithm for another is no easy task. Additionally, there is no added benefit for the broad majority of our customers to offset this pain. Since security is not in play, switching to a more secure algorithm (at great cost) provides no added value.

FIPS compliance may be possible, but it would require pluggable interfaces and full backwards compatibility to enable it, which is a non-trivial effort to design, test, maintain, and support. Additionally, true support of FIPS would require us to run all of our tests on FIPS-enabled hardware, including NServiceBus and all of its downstream dependencies as well. This is not an investment we are prepared to make.

Although we are not officially supporting or investing into FIPS compliance, we will occasionally make changes to [decrease the amount of friction around users extending the platform](https://github.com/Particular/NServiceBus/issues/2721), making it easier for users to enable FIPS compliance via extensibility.

Additionally, NServiceBus is still open-source software, and we are an open source company. Therefore, we will accept any pull request that makes NServiceBus more friendly to FIPS as long as that pull request does not compromise any of the underlying design or features.

**Closed by DavidBoike** 2015-09-17 14:09 UTC
Labels: Type: Feature

**Comment by SeanFeldman** [comment] 2016-04-20 18:43
Added summary of comments.

**Comment by DavidBoike** [comment] 2019-03-06 16:15
Very old thread, and no change in policy, but we now have a documentation article on FIPS mode:

https://docs.particular.net/nservicebus/compliance/fips
