### ISSUE TITLE
Enhance SendOptions documentation

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus#3764] opened 2016-05-20 20:22 UTC
New to NServiceBus 6, I saw the `SendOptions` class as a parameter in several `IEndpointInstance` communication methods (ie `Send`).  Wanting to know more about it, I used Go To Definition in VS and what I found wasn't very helpful:

```
/// <summary>
/// Allows the users to control how the send is performed.
/// </summary>
public class SendOptions : ExtendableOptions
{
}
```

When I was working with this class for the first time, I was in the context of a unit test and had the Should library loaded, meaning I had loads of extension methods in intellisense, so it was difficult to discover what I could do with `SendOptions`.

Additionally, looking at `SendOptions`'s base class, `ExtendableOptions` I thought this class was meant for low level behavioral tweaking (ie internal manipulations of OutgoingHeaders).

**Proposed:**

Add additional documentation to `SendOptions`
1. Explaining that you work with this class via extension methods (ie `RoutingOptionExtensions`).
2. Provide some common usage examples.

**Comment by johnsimons** [comment] 2016-05-21 04:54
This is a duplicate of #3572

**Comment by timbussmann** [comment] 2016-05-23 11:28
Hey @ppittle ,

Thanks a lot for providing us with your v6 upgrade experience! I like your proposal to add some basic documentation and simple example on how `SendOptions` are used. We tried to document the `SendOptions` usage in the official documentation as close as possible to the related use cases. Was there something specific you wanted to achieve with the options in the tests?

@johnsimons the issue you linked is mainly discussing the API design and not the documentation part of, so I'm not sure this is really a "duplicate".

**Comment by ppittle** [comment] 2016-05-23 21:53
+1 for @timbussmann "not duplicate" comment.   Regardless of how the design is locked down, it would be nice to have some more documentation around `SendOption`

@timbussmann - By "as close as possible to the related use cases" I am thinking you're referring to the top pages that come back from a [Search for SendOptions](http://docs.particular.net/search?q=SendOptions) on the Particular Documentation site.  So [Delayed Delivery](http://docs.particular.net/nservicebus/messaging/delayed-delivery) details how to use `SendOptions` if you want to defer delivery of a message.  This documentation works well if, as a developer, you know what you are trying to do and "use SendOptions" is the answer.

Where the documentation falls down is: as a developer, I look at the intellisense of the `Send` method.  Ok, there's an overload that takes in a `SendOptions`.  What's `SendOptions`?  It's an empty class that wraps `ExtendableOptions`.  `ExtendableOptions` looks to provide low level manipulation of message headers.

Essentially, it would have been helpful for me if there was some documentation answering "what can you do with SendOptions".

**Example:**

    /// <summary>
    /// <para>
    /// Allows the users to control how the send is performed.  Functionality is provided
    /// via extension methods (ie <see cref="(forget where class name).DelayDeliveryWith" />)
    /// </para>
    /// <para>See http://docs.particular.net/nservicebus/SendOptions for more information and a 
    /// list of common methods.
    /// </summary>
    public class SendOptions : ExtendableOptions    {    }

Then http://docs.particular.net/nservicebus/SendOptions would aggregate the list of commonly used extension methods and their (intellisense) documentation.

And, happy to provide the feedback.  It's great to see a company as open as Particular!

**Comment by johnsimons** [comment] 2016-05-23 22:35
I do still think the reason we are discussing this is because the API does not help the user to success, it is not discoverable as @ppittle found out.
The fact that a user had to look for intellisense doco to figure out how to use it is a fail IMHO.

**Comment by distantcam** [comment] 2016-06-30 06:26
Should we consider merging code from the extensions into the class?

For example all of [DelayedDeliveryOptionExtensions](https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/DelayedDelivery/DelayedDeliveryOptionExtensions.cs) into [SendOptions](https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/SendOptions.cs)?

**Comment by andreasohlund** [comment] 2016-06-30 07:57
@timbussmann I remember that we had a lengthy discussion on this topic but I can't find the link. Do you remember?

(conclusion was that extension methods is needed since downstream components are adding methods as well).

If you do "var sendOptions = new SendOptions(); sendOptions." doesn't intellisense show all the options available?

I know that there was some ideas around a lambda instead

```
  handlerContext.Send(new MyMessage(), options => 
{
   options.Xyz();
   options.Bla();     
})
```

not sure if that would help much?

**Comment by timbussmann** [comment] 2016-06-30 12:16
some discussions here: https://github.com/Particular/NServiceBus/pull/3559#issuecomment-194763889
and here: https://github.com/Particular/NServiceBus/issues/3572

**Comment by distantcam** [comment] 2016-07-01 04:51
> conclusion was that extension methods is needed since downstream components are adding methods as well

My suggestion doesn't stop downstream components from also adding methods via extension. I'm just suggesting that for methods in the same namespace and same assembly as the item they're extending, we should just put those methods in the class instead of having them in an extension class. This also avoids the "empty" class with everything implemented in extensions.

**Comment by danielmarbach** [comment] 2016-07-01 12:55
I actually like the approach @distantcam suggested as long as we can keep
the autonomy of the capabilities. But I think that is the challange. Let's
explore it

**Comment by andreasohlund** [comment] 2016-07-01 13:01
Perhaps we can use partials?

**Comment by andreasohlund** [comment] 2016-07-01 13:37
Also: Remember that we want to have good intellisense for users but browsing/organizing the source code is something we want to optimize for us? (since we are the ones doing it on a daily basis)


Here is what I get:

![intellisense](https://cloud.githubusercontent.com/assets/125028/16523049/a1fe477c-3fa1-11e6-8a28-28c02733fe09.PNG)

Can we improve?

**Comment by bording** [comment] 2016-07-01 17:37
> Perhaps we can use partials? (don't kill me yet)

That won't work for downstreams because partial classes can't span assemblies.

**Comment by andreasohlund** [comment] 2016-07-01 17:42
Ah, didn't know, thanks!

**Comment by danielmarbach** [comment] 2016-07-01 20:28
Read @distantcam comment again folks ;) we proofed by dogfooding our model
is extendable. We can use the partial approach for core (backtracking on
the extension method model in the core) but downstreams will use the
extension method pattern

**Closed** 2019-10-01 15:37 UTC
Labels: candidate-for-next-release
