### ISSUE TITLE
Make SendOptions Set methods Fluent

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus#3763] opened 2016-05-20 20:15 UTC
Currently the `SendOptions` set methods (at least the ones in `RoutingOptionExtension`) return void.  It would be easier to work with `SendOptions` if the set methods were fluent (ie returned `SendOptions`).

Example (current):

    IEndpointInstance endpoint;

    var options = new SendOptions();
    options.SetDestination("example-queue");
    await endpoint.Send(new Message(), options);

Example (proposed):
    IEndpointInstance endpoint;

    await endpoint.Send(new Message(), new SendOptions.SetDestination("example-queue"));

Example (proposed change to `RoutingOptionsExtensions.SetDestionation`.  Should be applied to all other set methods as well):

    public static SendOptions SetDestination(this SendOptions options, string destination)
    {
      Guard.AgainstNull("options", (object) options);
      Guard.AgainstNullAndEmpty("destination", destination);
      UnicastSendRouterConnector.State state = options.Context.GetOrCreate<UnicastSendRouterConnector.State>();
      int num = 1;
      state.Option = (UnicastSendRouterConnector.RouteOption) num;
      string str = destination;
      state.ExplicitDestination = str;

      return options;
    }

**Comment by johnsimons** [comment] 2016-05-21 04:53
This is a duplicate of #3572

**Comment by timbussmann** [comment] 2016-05-23 11:35
hey @ppittle,

Thanks for your feedback regarding the `SendOptions`! We are currently thinking about different options to improve the `SendOptions` API in the future and a fluent API is something to consider (although we're trying to provide less fluent APIs in general). I'd be very interested in your opinion on this suggestion here: https://github.com/Particular/NServiceBus/pull/3559

**Comment by timbussmann** [comment] 2016-10-28 07:36
We have another issue around improving the SendOptions story here: https://github.com/Particular/NServiceBus/issues/3613. I think we're currently more on the side of providing a different approach on using SendOptions instead of just making them chainable for various reasons (see discussions in the linked issue). I'm closing this as #3613 has some follow up actions on it, you might be interested in following that issue. Thanks again for raising this.

**Closed by timbussmann** 2016-10-28 07:36 UTC
Labels: Discussion
