### ISSUE TITLE
Rename UnicastBusConfig to RoutingConfig 

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#1465] opened 2013-08-21 17:55 UTC
After separating out the audit, and the distributor config from UnicastBusConfig, it makes more meaning to call it Routing config, as it essentially provides the endpoint message mappings.

Also what needs to be happen to the `TimeoutManagerAddress` which is currently specified in the UnicastBusConfig?

Should it be `RoutingConfig` or `MessageRoutingConfig` ?

**Comment by danielmarbach** [comment] 2016-01-28 08:02
@indualagarsamy Should we close this since we are working on a new routing proposal anyway?

**Comment by indualagarsamy** [comment] 2016-01-28 08:37
@danielmarbach - with the new routing proposal, are we still going to support have a UnicastBusConfig in the app.config?
I didn't think we are going to code only config approach for v6.

**Comment by danielmarbach** [comment] 2016-01-28 10:08
Yeah but still is this issue relevant?

**Comment by timbussmann** [comment] 2016-02-05 13:47
@udidahan it looks like this also a "bus" we want to get rid off? Should that be in v6 scope then?

**Comment by indualagarsamy** [comment] 2016-02-05 20:07
@danielmarbach - I think its very relevant. 
@timbussmann Yes. UnicastBusConfig never made sense to me. Now that we are trying to get rid of the bus, not sure why we wouldn't want to get this done.

**Comment by andreasohlund** [comment] 2016-02-05 21:36
Not saying it would solve it but it would definitely have a positive impact on first time users understanding how to setup the routing, see https://github.com/Particular/NServiceBus/issues/3298

**Comment by danielmarbach** [comment] 2016-02-05 21:46
and since we want to get rid of the b-word ;) :+1:

**Comment by andreasohlund** [comment] 2016-02-09 12:05
Config section usage is confirmed to be a blocker for dotnet core support, should we consider to have the new section, if that is what we decide to go with, in a separate package?

https://github.com/Particular/PlatformDevelopment/issues/300#issuecomment-181618694

**Comment by SzymonPobiega** [comment] 2016-02-10 06:21
I don't see a point in renaming it because this suggest we still want people, even new users, to use it. 

We want people to switch to code API for logical routing (type -> endpoint) and (optionally) to use routing file (e.g. in MSMQ). So I would keep the old name and possibly move it to a separate package.

**Comment by timbussmann** [comment] 2016-02-10 11:15
I think there are two issues here:
* aligning to the decided naming concept (get rid of bus) which is in the v6 scope -> renaming it (this issue obviously)
* removing the config section in favor of a code first api: there is another issue which is not yet in scope for v6.

since we also made an exception for DataBus, I think this seems to be a question of priorities whether to rename or to keep it until we remove it anyway.

**Comment by danielmarbach** [comment] 2016-02-12 09:43
Flagged as CoreV6. Let's discuss it for V6.

**Comment by timbussmann** [comment] 2016-02-12 12:09
Since we want to remove it, I'd suggest to make sure we have code first APIs available for all `UnicastBusConfig` options with the rollout of v6 and then just kill it in the next release instead of having users going through the pain of renaming it first. New users could instead directly use the code first API.

**Comment by danielmarbach** [comment] 2016-02-12 14:06
Agree. That is a good strategy to move forward

**Comment by indualagarsamy** [comment] 2016-03-02 00:35
@Particular/nservicebus-maintainers - I am good with @timbussmann's suggestion. 
If you have doco issues/PRs/doco already published for the code level API changes, can you please link those to this issue. 
In that case, I am good with closing this issue.

**Comment by timbussmann** [comment] 2016-03-02 09:39
@indualagarsamy there is https://github.com/Particular/NServiceBus/issues/3424 which is already linked.

Closing this then.

**Closed by timbussmann** 2016-03-02 09:39 UTC
Labels: Tag: Core v6, Type: Feature
