### ISSUE TITLE
Creating multiple endpoints in one process does not associate handlers correctly

### ISSUE THREAD

**Issue by robbaman** [Particular/NServiceBus#5700] opened 2020-07-29 15:17 UTC
We use separate endpoints in a single .Net Core process to allow for different queues for different message priorities. Since we use an externally managed serviceprovider we create a startable endpoint which we then later start. The following code illustrates how we do this:

``` C#
var epc1 = new EndpointConfiguration("SomeService");
epc1.UseTransport<RabbitMQTransport>()
	.UseConventionalRoutingTopology()
	.ConnectionString("host=localhost;username=guest;password=guest;virtualhost=vhost;RequestedHeartbeat=600");
epc1.AssemblyScanner().ExcludeAssemblies(typeof(MessageBus.Priority.SomeHandler).Assembly.GetName().Name);
var ep1 = EndpointWithExternallyManagedServiceProvider.Create(epc1, services);

// Create 'priority' endpoint ignoring all handlers in the regular assembly
var epc2 = new EndpointConfiguration("SomeService.Priority");
epc2.UseTransport<RabbitMQTransport>()
	.UseConventionalRoutingTopology()
	.ConnectionString("host=localhost;username=guest;password=guest;virtualhost=vhost;RequestedHeartbeat=600");
epc2.AssemblyScanner().ExcludeAssemblies(typeof(MessageBus.Regular.SomeHandler).Assembly.GetName().Name);
var ep2 = EndpointWithExternallyManagedServiceProvider.Create(epc2, services);
```

Later we will start the two endpoints when the ServiceProvider has been created from the ServiceCollection. 

In the past (not sure when this changed) this would work fine and each endpoint would register handlers from the assembly you'd expect. Recently however only the first endpoint gets any handlers associated with it. It does correctly exclude the handlers from the assembly it is supposed to exclude, but the second endpoint just gets no handlers. The log file will contain lines for both endpoints, but only the first will have a list of lines like these:

```
2020-07-29 15:00:50,192 [1] DEBUG NServiceBus.Unicast.MessageHandlerRegistry - Associated 'NameSpace.ISomeEvent' message with 'NameSpaceSomeEventHandler' handler.
```

Also, the `configuration.txt` files created in the .diagnostics directory (one file per endpoint) both contain a `Receiving` node but the first has a `MessageHandlers` node containing a list of handlers, the other just has `"MessageHandlers": {}`.

Please note that if I reverse the order the two endpoints are created, the (new) first will now have handlers and the other (that previously had handlers) will no longer have handlers.

I don't recall having changed anything about this code since this worked (probably except updating the NServiceBus versions), so any help on what is happening here would be greatly appreciated.

EDIT:
I've created a minimal version that can be used to reproduce this issue at https://github.com/robbaman/MultiEndpointTest

**Comment by robbaman** [comment] 2020-07-29 19:58
I've narrowed down this problem to the ReceiveComponent where it checks whether there is an 'external' handlerregistry by looking for a registration for the `MessageHandlerRegistry` type. 
https://github.com/Particular/NServiceBus/blob/ad7ecd6b8e77daf8d8ce4c72673fa1ad7e4491ed/src/NServiceBus.Core/Receiving/ReceiveComponent.cs#L81 

This type is however later registered as a singleton dependency with the DI container:
https://github.com/Particular/NServiceBus/blob/ad7ecd6b8e77daf8d8ce4c72673fa1ad7e4491ed/src/NServiceBus.Core/Receiving/ReceiveComponent.cs#L282

When starting two endpoints within the same application there is only one DI-container and thus when configuring the first endpoint it works fine, but when configuring the second it suddenly thinks an external source is registering the handlers and no assembly scanning occurs.

**Comment by ramonsmits** [comment] 2020-07-29 21:30
@robbaman Each endpoint should get its own child container. Create 2 child container instance that are passed to `EndpointWithExternallyManagedServiceProvider.Create`.

**Comment by robbaman** [comment] 2020-07-29 21:41
Hi @ramonsmits Thanks for getting back to me. 

The `EndpointWithExternallyManagedServiceProvider.Create` method takes an IServiceCollection. As far as I know the Microsoft Dependency Injection container platform does not support child container instances. Am I missing something here?

**Comment by timbussmann** [comment] 2020-07-31 09:43
@robbaman each endpoint registers additional services into the ServiceCollection. If you pass the same collection to both endpoints, they have conflicting service registrations. If you run multiple endpoints, each endpoint needs it's own ServiceCollectiona and ServiceProvider instance.

**Comment by robbaman** [comment] 2020-07-31 10:37
Hi Tim. I see what you mean, but does this mean there's no (easy) way to run multiple endpoints in the same service when using the Microsoft DI framework IServiceCollection to register the services (seeing how there is only one ServiceCollection available during application startup).

Note that we use StructureMap so we naturally also looked at the docs here https://docs.particular.net/samples/dependency-injection/structuremap/ on how to use StructureMap with NServiceBus, but if you follow that example, which has the following code:

```
endpointConfiguration.UseContainer(new StructureMapServiceProviderFactory(registry));
```

You end up with multiple separate DI-containers (one from the (AspNetCore)Host itself and one created by NServiceBus for each of the endpoints). Each of these containers will have their own Singleton instances which is generally not what you'd want.

What we've done for now is create a custom `IConfigureComponents` implementation wrapping a StructureMap registry based off the `ServiceCollectionAdapter` provided by the NServiceBus.Extensions.DependencyInjection package. 

We then create the startable-endpoint using the `EndpointWithExternallyManagedContainer.Create` method passing in an `IConfigureComponents`-wrapped Registry profile (the StructureMap way of configuring a named child container). Finally we start this startable-endpoint using an IBuilder wrapper for the StructureMap IContainer (the Child container obtained by calling GetProfile on the main container using the same profile name).

This way we'll have the regular StructureMap Registry as root of the application containing a profile (child container) for each endpoint. All the 'normal' stuff (including our own singletons) are registered in the root Registry and are thus true application wide singletons. Any (singleton) registrations by the `EndpointWithExternallyManagedContainer.Create` call are created as part of their own Profile and are thus scoped to their own container, which is also the container used by the endpoint.

While we did solve this for ourselves (after a fashion) there are two things I'd like to pass to you:

1) Using the `EndpointWithExternallyManagedServiceProvider.Create` within a netcore hosted environment (where the IServiceCollection is created for you) is not compatible with creating multiple endpoints, without giving any indication that it's not supported. There are no errors, the endpoint will just not be configured correctly.
2) The beforementioned `endpointConfiguration.UseContainer(new StructureMapServiceProviderFactory(registry));` Will create completely separate container for each endpoint in addition to the one already created by the host, which makes working with singletons very intuitive.

**Comment by timbussmann** [comment] 2020-07-31 11:29
> I see what you mean, but does this mean there's no (easy) way to run multiple endpoints in the same service when using the Microsoft DI framework IServiceCollection to register the services (seeing how there is only one ServiceCollection available during application startup).

I think we need to be careful about what we're talking about. From your sentences, I get the feeling you're talking about the [Microsoft Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1) that manages a single DI container and its lifecycle. For this usage, we have a dedicated package for easy NServiceBus integration here: https://docs.particular.net/nservicebus/hosting/extensions-hosting. This approach is recommended when you're using the generic host standalone or e.g. as part of ASP.NET Core. This package only supports one endpoint per generic host, due to the single DI container available.

The NServiceBus.Extensions.DependencyInjection package provides support for IServiceCollection/IServiceProvider based DI containers outside the generic host cases, when you as the user manage the IServiceProvider lifecycle yourself.

As said before, every endpoint requires it's own, isolated service registry and provider from other endpoints. It heavily depends on the actual DI container used on how this can potentially support multi-endpoint scenarios, e.g. whether the container supports child-containers or not.

If you are using the default IServiceCollection/IServiceProvider implementation and you want to share object instances across both endpoints, you should probably register the singleton-instance upfront on each of the individual IServiceCollection instances. It's kinda important to not register it using a factory, as each endpoint has its own ServiceProvider and therefore the factories will still create one singleton instance per IServiceProvider instance.

In general, we do not recommend running multiple endpoints on a single process. Is there a specific reason you can't combine the two endpoints into a single endpoint or run them in isolated processes?

**Comment by robbaman** [comment] 2020-07-31 11:57
> In general, we do not recommend running multiple endpoints on a single process. Is there a specific reason you can't combine the two endpoints into a single endpoint or run them in isolated processes?

I see. The reason we're doing this is because we want to have different service levels (ie priority or not) for messages with each their own RabbitMQ queue, but still have a mostly identical code base (business rules, datacontext, etc) for handling the messages.

While we could've ofc gone with separate processes, for us that'd meant having even more administrative tasks (like managing build queues etc) and it would make it harder to create a shared cache for instance. In the end it just seemed easier to have multiple endpoints in the same process.

**Comment by timbussmann** [comment] 2020-08-03 06:41
thanks for sharing those details 👍 
Typically, when providing different service levels, there is a good reason to hose them on different machines as your requirement on hardware and availability are typically higher for the priority-service. When those two endpoints run on the same machine, the priority service has to compete for all available resources (disk, network, cpu, ...) against the regular endpoint and that's often not helping to achieve actual priority. I'd argue you gain more flexibility and freedom by splitting those endpoints into dedicated processes but I understand that it causes more administrative effort to handle all of that (I'll forward this aspect to our internal feature request backlog).

**Comment by robbaman** [comment] 2020-08-03 10:55
Thanks, I suppose it's not the most common of scenario's, so for now I guess it should suffice to just provide something of a warning in the section on the externally managed mode https://docs.particular.net/nservicebus/dependency-injection/#externally-managed-mode and here https://docs.particular.net/nservicebus/dependency-injection/extensions-dependencyinjection

Now that I understand how it works it makes total sense that some hoops need to be jumped to make it do what I want it to do, but it wasn't directly clear why it doesn't work or that it's not supported out of the box. 

Judging by the docs as they are now, it seems one can just call `EndpointWithExternallyManagedServiceProvider.Create(endpointConfiguration, serviceCollection)` multiple times with different configurations. But this will not throw errors during configuration or when running, but it will simply not do what you expect. Which is why it took me quite some time to figure out what went wrong.

**Comment by timbussmann** [comment] 2020-08-03 10:57
thanks for the feedback, we will try to improve our documentation to make the intended behavior more clear 👍

**Comment by timbussmann** [comment] 2020-08-11 11:12
I've tried to improve the docs with this PR: https://github.com/Particular/docs.particular.net/pull/4958. Closing this issue with this for now. Please feel free to reopen if we missed something.

**Closed by timbussmann** 2020-08-11 11:12 UTC
