### ISSUE TITLE
Impact on NSB license when changing languages

### ISSUE THREAD

**Issue by karenfruchtman** [Particular/NServiceBus#2421] opened 2014-09-30 11:09 UTC
Problem raised by Startup customer jostein.aksnes@gmail.com

Their license file worked on one developer's machine, but not on another.  Upon further checking:

"It seems like the problem was related to changing the date format on the
developer machine from Thai to English. When this was done NServicebus was
complaining, and once it was set back to Thai it worked fine again.

The license was applied when the thai date time format was applied, so
maybe there are some issues when the dates are stored in the registry etc.
for the license?"

**Comment by johnsimons** [comment] 2015-03-02 00:13
@gbiellem any news on this one ?
This is an interesting bug that quite possible affects other products too, how should this be handled ?

**Comment by gbiellem** [comment] 2015-03-02 03:13
@johnsimons  Thanks for the reminder.

I just checked it out then and yes it's broken. The root cause  appears to be that the Thai locale's date format is based on the Buddhist calendar not the Gregorian calendar,  so the current year is 2558 not 2015.  Bug will be present across all the products using "Particular.Licensing".

**Comment by johnsimons** [comment] 2015-03-02 03:18
@gbiellem can you raise a concern in requirements to handle this ? And close this one once done.

**Comment by gbiellem** [comment] 2015-03-02 03:53
No problem - Raised in requirements https://github.com/Particular/Requirements/issues/220

**Closed by gbiellem** 2015-03-02 03:53 UTC
Labels: Bug, Needs: Scheduling

**Comment by karenfruchtman** [comment] 2015-03-02 04:56
@gbiellem @johnsimons Thanks, guys!  I have updated the client who raised the issue.
