### ISSUE TITLE
Disposal Behavior for Dependency Injection Containers

### ISSUE THREAD

**Issue by kevin-whalley-gc** [Particular/NServiceBus#2681] opened 2015-03-12 17:56 UTC
Hi,

We've noticed that when sharing an Autofac Container between NServiceBus and an ASP.NET MVC application that if NServiceBus encounters a critical error it will dispose of the container, causing an exception in the web application because controllers can no longer use the container for dependency resolution when instantiating.

I understand that NServiceBus attempts to dispose of all disposable components, but my instinct is that it should draw a line between components its instantiated and components that were injected during configuration. Is this a configuration option we can set or a hard coded behavior?

**Comment by johnsimons** [comment] 2015-03-17 00:29
@kevin-whalley-gc unfortunately is a hard coded behavior that cannot easily be bypassed.
I do agree with you and I actually previously raised this concern with my colleagues, I do think that NServiceBus should not dispose of the container that users pass to us, that is wrong IMO.

I'll raise this again

**Comment by johnsimons** [comment] 2015-03-17 01:03
@kevin-whalley-gc is the reason you are sharing a container between NServiceBus and MVC because you want to inject `IBus` in your controllers ?
If this is the reason, I recommend bypassing that complexity and accessing a static IBus in the global, would that work ?

**Comment by kevin-whalley-gc** [comment] 2015-03-17 01:05
@johnsimons we shared the container because our message handlers and MVC share some of the injected dependencies, so it made sense to use one bus

**Comment by johnsimons** [comment] 2015-03-17 01:07
@kevin-whalley-gc what version of NServiceBus are you on ?

**Comment by johnsimons** [comment] 2015-03-17 01:14
@kevin-whalley-gc you should be able to override the default implementation by overriding the critical action see http://docs.particular.net/nservicebus/upgrades/4to5#moved-definecriticalerroraction-to-be-a-configurationbuilder-extension

**Comment by kevin-whalley-gc** [comment] 2015-03-17 01:48
@johnsimons, Will we need to add any of the normal critical error process into our definition? E.g. if we override it, but don't add any of the normal resource cleanup will that have an adverse effect?

We are on NServiceBus 5.x

**Comment by johnsimons** [comment] 2015-03-17 01:57
@kevin-whalley-gc well, when a critical error is raised, it means the bus is in a state that is better to shut it down then to keep it going.
By overriding that config option, you are taking full control of what to do next.
If you call `bus.Dispose()` that will cause the container to be disposed, which is not what u want.
Not really sure what advice to give here, @Particular/nservicebus thoughts ?

**Comment by kevin-whalley-gc** [comment] 2015-03-17 02:05
@johnsimons My thinking is, I can use DefineCriticalError to create a new bus instance for my MVC app, and I'm curious if I do this once or twice without disposing of the previous bus like normal, would it affect performance / queue connectivity if there is a zombie bus out there that hasn't been fully shut down

**Comment by johnsimons** [comment] 2015-03-17 02:47
@kevin-whalley-gc the question I have for you is why are you getting critical errors ?

**Comment by kevin-whalley-gc** [comment] 2015-03-17 15:38
@johnsimons We use RabbitMQ as our transport, so whenever it has connectivity issues the circuit breaker will arm and trigger a shutdown.

**Comment by andreasohlund** [comment] 2015-03-17 19:27
As of v2.1 you can control how long we should keep on retrying before
shutting down

http://docs.particular.net/nservicebus/rabbitmq/configuration-api#controlling-behavior-when-broker-connection-is-lost

would that help?

**Comment by kevin-whalley-gc** [comment] 2015-03-17 21:36
Thanks @andreasohlund for bringing that up. The team and I are going to discuss what we want to do here.

Approaches:

1. Extend out the retries for the RabbitMQ transport so it is more tolerant of the network, or doesn't go down at all
2. Setup two containers, one for MVC and one for NServiceBus so MVC is still functional if NServiceBus goes down
3. Define our own CriticalErrorAction to prevent the Autofac Container from being disposed

-- With options 2 and 3 we will also consider whether we can re-instantiate the bus in-process, or treat it as a hard failure and require a manual step to restart the website in IIS.

**Comment by andreasohlund** [comment] 2015-03-18 05:16
Another option is to do a Environment.FailFast in the on critical error and force a complete app pool restart?

**Comment by johnsimons** [comment] 2015-03-18 23:21
> Another option is to do a Environment.FailFast in the on critical error and force a complete app pool restart?

@andreasohlund I don't think that is what @kevin-whalley-gc is after, a temporary rabbitmq disconnection should not need a full app pool restart IMO

**Comment by johnsimons** [comment] 2015-03-24 01:24
@kevin-whalley-gc it seems to me with https://github.com/Particular/NServiceBus/issues/2681#issuecomment-82555063 and https://github.com/Particular/NServiceBus/issues/2681#issuecomment-82609226 this issue is now not a problem anymore ?
Is it ok for me to close it?

**Comment by kevin-whalley-gc** [comment] 2015-03-24 15:49
@johnsimons Yes, we've decided to work on some re-initialization logic in the DefineCriticalAction.

**Closed** 2015-03-24 22:15 UTC
Labels: Bug, Needs: Triage

**Comment by chandmk** [comment] 2015-03-26 16:03
We have similar problem with MSMQ. V5.2

We are sharing autofac container between WCF and Bus.  We have shared dependencies that need to be injected into the MessageHandlers and WCF request processor types.

When ever a critical error occurrs, container is getting disposed.  Bus usage is about 20% of the overall usage of the WCF service.  If you take down the container, now this WCF service becomes unusable, which in turn is affecting our public facing site.

One example of critical error is,  if we recycle MSMQ service on the host machine, WCF service goes down.  

We also have other end points that are being hosted by NServiceBus.Host, and this behavior is totally understandable.

What options do we have to gracefully recover from these errors without affecting the wcf service?
Do have any advise for us to do in DefineCriticalErrorAction override?

**Comment by johnsimons** [comment] 2015-03-27 05:07
@chandmk I wish I could give you advice on what to do in `DefineCriticalErrorAction` override, but that really depends on your requirements.

Unfortunately when `DefineCriticalErrorAction` is called it means that something is seriously wrong and usually is safer to shutdown the bus then to keep on going.
Obviously if you are co-hosting the bus with another public API or website, it does make sense to take control of what to do in this situation. 
The best you can do, is once that method is called, schedule a safe and controlled restart for the process.

**Comment by chandmk** [comment] 2015-03-27 11:41
As you are disposing the given container out of the box, now there are multiple failure points that can bring down the WCf service.  MSMQ, storage endpoints (Timeouts, Subscriptions, Retries), queue permissions, not sure what else is there..

In the logs I also noticed instances of container getting disposed without corresponding log entry from critical error handler.

When we override the DefineCriticalErrorAction method and simply log the error, and do nothing else, this is bringing down the app pool.  

Is there any way to not dispose the container and also not bring down the apppool?  

My idea is that if we can allow only the bus related actions (instead of entire site) to fail, and once the problem is fixed/solved, either bus starts functioning normally or we can recycle the app pool manually

**Comment by danielmarbach** [comment] 2015-03-27 14:10
@johnsimons I quickly discussed this today with @andreasohlund and @SimonCropp . We think we need to change the core to not dispose the `IContainer` implementation when it is passed in by outsid because in that case we don't own the disposable resource.

@chandmk as a workaround what about setting up two containers and forwarding calls from one to another for the shared dependencies?

**Comment by chandmk** [comment] 2015-03-27 16:52
@danielmarbach, after a bit more digging there is a bigger problem here than simply creating multiple containers.

In the following scenario
a. RavenDB goes down.
b. A critical error is thrown
c. Bus is now disposed.  Application container is not disposed.
d. RavnDB comes backup online
e. Is it possible to bring the Bus up without restarting the app pool? If we were to restart the bus via code, how would it know every thing is fine?  How many times we should try?  

May be out of box should use circuitbreaker pattern to avoid manual app pool reset.  It would keep failing all Bus calls through and works through some kind of SLA?  This way problem self corrects itself when all the dependencies are available?

**Comment by kevin-whalley-gc** [comment] 2015-03-27 17:13
@danielmarbach @chandmk 

What I've tested in a development environment is yes, you can create a new bus, pass it back into the container, and we have our own circuit breaker so it doesn't endlessly retry, but share the same problems with determining whether the restart was successful - how can we tell the circuit breaker to reset its failure count if we don't know

**Comment by chandmk** [comment] 2015-03-28 15:52
@danielmarbach,

I ended up with the following for now...

a. Set Up two duplicate containers.  I don't like this. And I hope this is temporary arrangement.
b.  Save the created bus into static variable and register that as single instance into WCF container.
c. Override DefineCriticalErrorAction. (When a queue goes down this method is being called multiple times, may be we need to lock the method to prevent multi reinitialization attempts.)
     1. Dispose the bus saved in static variable.  
      2. In a wait and retry loop, we try create the bus again and reset the static variable.  We choose a minute as the retry interval.  This puts the WCF service in a limp mode.  All BUS related operations would fail. Logs also show that we are retrying for Bus to come up.
     3. When the dependencies come back and when Bus is recreated we break out of the loop.

All in all it feels like we are solving a problem that we thought should have been in the box for any self hosted integration scenario.

**Comment by bhardwajgaurav007** [comment] 2018-01-09 10:53
I am facing similar issue. Has this issue being fixed by NServiceBus team?

**Comment by danielmarbach** [comment] 2018-01-09 10:56
@Particular/nservicebus-maintainers @Particular/container-maintainers please chime in and advice.

**Comment by andreasohlund** [comment] 2018-01-09 11:37
@bhardwajgaurav007 just to make sure I understand your scenario: You have a webapp using NServiceBus and you want to avoid the bus being disposed should a critical failure be detected.

Would would you like to happen? 

If you want to keep on retrying =>

Override the behavior using https://docs.particular.net/nservicebus/hosting/critical-errors?#custom-handling and just make the method a "no-op".

If you want to shutdown the process: Override the behavior and do a `Environment.FailFast` or similar.


Does this help?

Note: As of the upcoming v7 version NServiceBus will default to the "retry for ever" option (https://docs.particular.net/nservicebus/hosting/critical-errors?version=core_7#default-behavior)
