### ISSUE TITLE
V5: Enabling the outbox currently results in a TransactionScope with RequiresNew to be created

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3278] opened 2015-12-31 10:07 UTC
NServiceBus is creating a transaction scope in OutboxDeduplicationBehavior which creates transaction scope with the following comment:

>  //we use this scope to make sure that we escalate to DTC if the user is talking to another resource by misstake

This makes me wonder why this is here. This scope results in the transactional behavior of the SQL transport combined with the NHibernate persistance that has 'session connection' sharing.

Having this transaction scope does result in that NHibernate is relying on TransactionScope and not creating its own transactions and due that `NHibernateStorageContext.Connection.DatabaseTransaction` does not contain the transaction.

@andreasohlund mentioned that this behavior is not present in V6: https://github.com/Particular/NServiceBus/pull/3249

I tested a custom build that didn't create that TransactionScope and it seems that SQL Transport + NH Persistence is working fine.

Having the transaction scope is not promoting to DTC so it is not creating issues. I didn't expect that transactionscope to be there/active when calling `DisableDistributedTransactions`.

**Comment by udidahan** [comment] 2016-01-03 16:28
Would you say that this is a bug, design flaw, or something else?

**Comment by ramonsmits** [comment] 2016-01-06 10:03
@udidahan Not sure what to think of it. I do think that the creation of the transaction scope should not be done by the outbox behavior. I would expect a seperate behavior to do this which in this case would be enabled via a feature toggle. Maybe V6 has such a design?

I would say this is more of a design flaw/issue than a bug.

If it would be a feature then the behavior would be more visible to the user.

**Comment by udidahan** [comment] 2016-01-06 10:43
@ramonsmits then I suggest labeling it as a design flaw.

Since it's not a bug, if you want to push for it being prioritized, then you should label it with "consider for short term focus".

**Comment by ramonsmits** [comment] 2016-01-07 19:58
@udidahan I don't see this label. I had a meeting with @andreasohlund today where he explained the transactional models for V6 and it seems that it is addressed sufficiently. Transaction scopes are not hidden by enabling certain features and seems very explicit in the new API.

Based on the current process that we only fix bugs in V5 and this being a design flaw I would say that we do not need to change this but that we can improve doco. I've created an issue for this and I think this issue can be closed.

**Comment by andreasohlund** [comment] 2016-01-07 20:27
@ramonsmits link to the created issue and close this one?

**Closed** 2016-01-07 20:28 UTC

**Comment by udidahan** [comment] 2016-01-08 07:55
@ramonsmits it was just a suggestion. I wanted to leave the final decision with you.
