### ISSUE TITLE
Extend CommonObjectBuilder 

### ISSUE THREAD

**Issue by matiii** [Particular/NServiceBus#5218] opened 2018-07-18 07:04 UTC
Could you provide similar solution for dependency injection as below ? Its really boilerplate code to do it myself...

```
using NServiceBus;
using NServiceBus.ObjectBuilder;

namespace Shared.Extensions
{
    public static class ConfigureComponentExtensions
    {
        public static IComponentConfig<TBase> ConfigureComponent<TBase, T>(this IConfigureComponents registration, DependencyLifecycle dependencyLifecycle) where T : TBase
        {
            registration.ConfigureComponent<T>(dependencyLifecycle);

            return registration.ConfigureComponent<TBase>(builder => builder.Build<T>(), dependencyLifecycle);
        }
    }
}
```

**Comment by timbussmann** [comment] 2018-07-19 09:10
hey @matiii 

can you give us some more detail about what you're using this type of registrations for? At first glance, it looks like you want to register subclasses while being able to resolve them when requesting the base class type, is that correct?

**Comment by matiii** [comment] 2018-07-20 06:18
Hi, As base types I use interfaces instead of implementations.

**Comment by timbussmann** [comment] 2018-07-20 12:39
@matiii can you give an example of your usage of this extension method then? Because NServiceBus does register implemented interfaces automatically with the container by default, so there should be no additional code required for that.

**Comment by matiii** [comment] 2018-07-23 08:31
**Error**
> Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Handler' can be invoked with the available services and parameters

Code example
```
class Handler: IHandleMessages<Command> 
{
 private readonly IService _service;

 Handler(IService service){ _service = service; }

 public void Handle(Command c) { }
}
```

**Comment by timbussmann** [comment] 2018-07-23 12:50
@matiii Please share your endpoint configuration including the registration of your `IService` implementation with us.

**Comment by matiii** [comment] 2018-07-24 06:05
```
public class EndpointConfig : IConfigureThisEndpoint, AsA_Server
    {
        public void Customize(BusConfiguration configuration)
        {
            NServiceBus.Logging.LogManager.Use<NLogFactory>();
            configuration.EndpointName(ConfigurationManager.AppSettings["EndPointName"]);
            configuration.Conventions()
                .DefiningCommandsAs(t => t.Namespace != null && t.Namespace.EndsWith("Commands"));
            configuration.Conventions().DefiningEventsAs(t => t.Namespace != null && t.Namespace.EndsWith("Events"));
            configuration.UsePersistence<InMemoryPersistence>();

            configuration.RegisterComponents(c =>
            {
                c.ConfigureComponent<IKnownErrorsProvider, KnownErrorsProvider>(DependencyLifecycle.SingleInstance);

                c.ConfigureComponent<IService, Service>(DependencyLifecycle
                    .InstancePerCall);
            });
        }
    }
```

**Comment by timbussmann** [comment] 2018-07-24 13:00
@matiii I'm having troubles reproducing your issue with the information received from you. Implemented interfaces are automatically registered with the container on registered classes by default without the need for the suggested extension method in the issue description. Can you share a project which reproduces the issue with us?

**Comment by matiii** [comment] 2018-07-27 05:58
Hi, Could you provide your PoC ? I will adjust it.

**Comment by timbussmann** [comment] 2018-07-30 08:17
@matiii here's a basic example of automatic interface registration: https://gist.github.com/timbussmann/35187d7c616b10b925f11f9896c61659

**Comment by matiii** [comment] 2018-07-30 09:38
Yep, it works. My mistake.

**Comment by timbussmann** [comment] 2018-07-31 06:27
Thanks for confirming. I'll close this issue then.

**Closed by timbussmann** 2018-07-31 06:27 UTC
