### ISSUE TITLE
Make AcceptanceTests scenario message idempotent

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3223] opened 2015-12-14 14:10 UTC
We have a few acceptance tests that do something like this

https://github.com/Particular/NServiceBus/commit/09e0c051da62c4824712502fdbe51347b54f9699

For example in Azure it is a costly operation to cleanup the resources. Therefore they resources stay around between test runs. We need a generic concept to handle messages from previous runs. One simply way to achieve this could be the following

* Add unique id to the ScenarioContext which gets assigned when a context is created
* An outgoing behavior adds that id to a message header like `$acceptancetests.scenariocontextid`
* An incoming behavior filters out messages where `$acceptancetests.scenariocontextid` does *not* match the current scenario context id.

**Comment by timbussmann** [comment] 2015-12-14 14:17
+:100: to remove this logic from all the scenarios

**Comment by SeanFeldman** [comment] 2015-12-14 14:52
This sounds like a duplicate of PR https://github.com/Particular/NServiceBus/pull/3215

**Comment by DavidBoike** [comment] 2015-12-14 15:03
I am working on this on the [idempotent-test-execution branch in the AzureServiceBus repo](https://github.com/Particular/NServiceBus.AzureServiceBus/tree/idempotent-test-execution). When it works there we can decide whether to copy to other repos that need it or generalize it in core.

@SeanFeldman the PR you referenced isn't dupe, that PR is just required for what I described above to work.

**Comment by danielmarbach** [comment] 2015-12-14 15:15
@davidboike ok for me. The above steps should also work specific for ASB.

On Monday, December 14, 2015, David Boike <notifications@github.com> wrote:

> I am working on this on the idempotent-test-execution branch in the
> AzureServiceBus repo
> <https://github.com/Particular/NServiceBus.AzureServiceBus/tree/idempotent-test-execution>.
> When it works there we can decide whether to copy to other repos that need
> it or generalize it in core.
>
> @SeanFeldman <https://github.com/SeanFeldman> the PR you referenced isn't
> dupe, that PR is just required for what I described above to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3223#issuecomment-164459650>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by danielmarbach** [comment] 2015-12-14 15:17
@davidboike I'd suggest to use ScenarioContext for it since it is the
scenario specific data and bound on the container

On Monday, December 14, 2015, David Boike <notifications@github.com> wrote:

> I am working on this on the idempotent-test-execution branch in the
> AzureServiceBus repo
> <https://github.com/Particular/NServiceBus.AzureServiceBus/tree/idempotent-test-execution>.
> When it works there we can decide whether to copy to other repos that need
> it or generalize it in core.
>
> @SeanFeldman <https://github.com/SeanFeldman> the PR you referenced isn't
> dupe, that PR is just required for what I described above to work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/3223#issuecomment-164459650>
> .
>


-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by danielmarbach** [comment] 2016-03-11 14:20
@DavidBoike This is fixed right? Can you reference the PR and close this issue?

**Comment by DavidBoike** [comment] 2016-03-14 14:16
Having trouble finding it specifically in a PR, but the code is here:

* [Outgoing mutator and incoming behavior pair](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/AcceptanceTests/Infrastructure/TestIndependenceBehavior.cs)
* [Configuration of mutator and behavior](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/develop/src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs#L38-L41)

From what I understand, while it's successful on ASB, it's really not necessary on any other transport.

**Closed by DavidBoike** 2016-03-14 14:16 UTC
Labels: Type: Feature
