### ISSUE TITLE
Easing gc pressure

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2049] opened 2014-04-11 01:34 UTC
Because message bodies are just `byte[]`, I wonder if we would be better off with this buffered stream to read the message bodies?
https://github.com/EventStore/EventStore/tree/master/src/EventStore/EventStore.BufferManagement

**Comment by danielmarbach** [comment] 2016-02-15 10:21
Closing as a duplicate of https://github.com/Particular/NServiceBus/issues/1272

**Closed by danielmarbach** 2016-02-15 10:21 UTC
Labels: Type: Feature, Withdrawn: Duplicate
