### ISSUE TITLE
Gracefully handle situation where saga correlation ID in messages is default/null value

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#5094] opened 2017-12-11 10:45 UTC
When a message is processes that has a default value for the saga correlation ID then this situation is not gracefully handled. Immediate and delayed retries are triggered while we this isn't needed.

I tested this with the in memory and learning persister and both do not handle null/default values gracefully.

## Expected behavior

- I would expect that an exception would be raised stating that the incoming message has a null/default value which cannot be used for correlation.
- Having a way to deal with null values
- Maybe not trigger FLR/SLR and treat it as a poison message?

### In Memory persister:

There is no check performed in the In-Memory persister which results in an NRE:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.InMemorySagaPersister.CorrelationId.GetHashCode()
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at NServiceBus.InMemorySagaPersister.Get[TSagaData](String propertyName, Object propertyValue, SynchronizedStorageSession session, ContextBag context)
   at NServiceBus.PropertySagaFinder`1.<Find>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.SagaPersistenceBehavior.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeSagaNotFoundBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__9.MoveNext()
```

### LearningPersistence

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.SagaPersistenceBehavior.CreateNewSagaEntity(SagaMetadata metadata, IInvokeHandlerContext context)
   at NServiceBus.SagaPersistenceBehavior.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeSagaNotFoundBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.LearningTransportMessagePump.<ProcessFile>d__9.MoveNext()
```

**Comment by timbussmann** [comment] 2017-12-15 14:17
> I would expect that an exception would be raised stating that the incoming message has a null/default value which cannot be used for correlation.

I don't think we can throw on default values. `0` and `False` seem to be perfectly valid values?

I'm 👍 for throwing a more meaningful exception when the correlation property is `null`though. What to persistence maintainers think about this? @Particular/ravendb-persistence-maintainers @Particular/sqlpersistence-maintainers @Particular/nhibernate-persistence-maintainers @Particular/azure-maintainers

**Comment by MarcinHoppe** [comment] 2017-12-16 09:59
We do throw on 0 and false. According to @andreasohlund this is by design and documented.

**Comment by timbussmann** [comment] 2017-12-18 08:11
while I think `default` might be a valid value for value types (especially 0) I don't see a huge issue with that right now (arguably, bool doesn't make much sense as a correlation property type), at least there should be a better exception when those constraints are hit. 

@MarcinHoppe what exception do you throw?

**Comment by andreasohlund** [comment] 2017-12-18 08:21
I agree that `0` or `true/false` might be valid in some edge case we haven't heard of yet. I'd say we wait until we get some real use cases reported before we relax this rule?

**Comment by MarcinHoppe** [comment] 2017-12-18 08:22
We == NServiceBus, not the persister. Here is the exception:

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs#L161

**Comment by timbussmann** [comment] 2017-12-18 08:36
so, how does the exception mentioned by @ramonsmits occur if there should be this custom exception?

**Comment by ramonsmits** [comment] 2017-12-20 20:06
The default/null behavior is since V6 AFAIK. I've had issues for example where indeed 0 was a valid value because the index was zero based and I had to +1 this to resolve it.

And maybe the SQL persister is gracefully checking this but here I'm mentioning in memory and learning persistence.

I personally think this is a core concern, the persisters could potentially also validate this but this is a correlation based on a value from the message before it even is passed to the persistence.

**Comment by DavidBoike** [comment] 2017-12-20 20:27
@ramonsmits The check is indeed happening in the core.

**Comment by ramonsmits** [comment] 2017-12-21 12:44
@DavidBoike Well, based on the pasted exception information it seems core is not doing that, or maybe only when the entity is saved, it must be done when the entity is loaded.

**Comment by andreasohlund** [comment] 2017-12-21 13:25
> it must be done when the entity is loaded.

Correct, we only check just before we're about to store/update the saga entity

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs#L145

**Comment by andreasohlund** [comment] 2017-12-21 13:26
So this indeed seems like a thing we should check in the core => to not try to load a saga entity with a null/default value

**Comment by mauroservienti** [comment] 2017-12-22 10:25
In which way can we say that 0 is not a valid value? Or any default value for what it matters.

**Comment by andreasohlund** [comment] 2017-12-22 11:59
Happy to dial it back to a null check only. The original intent was to
prevent situations where the user forgets to assign the correlation id
property but a null check seems to cover enough ground.

**Comment by timbussmann** [comment] 2018-01-23 17:29
* starting saga with a default value as the correlation property: message handler is invoked but then persisting the saga data fails due to 

```
System.Exception: The correlated property 'OrderId' on saga 'OrderSaga' does not have a value.
A correlated property must have a non default (i.e. non null and non-empty) value assigned when a new saga instance is created.
   bei NServiceBus.Sagas.ActiveSagaInstance.ValidateCorrelationPropertyHaveValue(Object currentCorrelationPropertyValue)
   bei NServiceBus.Sagas.ActiveSagaInstance.ValidateChanges()
   bei NServiceBus.SagaPersistenceBehavior.<Invoke>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.InvokeSagaNotFoundBehavior.<Invoke>d__0.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.MutateIncomingMessageBehavior.<InvokeIncomingMessageMutators>d__1.MoveNext()
[...]
```

* starting the saga with a null value as the correlation property causes the message to fail before invoking the handler, with the following exception (as already stated by @ramonsmits ):

```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei NServiceBus.SagaPersistenceBehavior.CreateNewSagaEntity(SagaMetadata metadata, IInvokeHandlerContext context)
   bei NServiceBus.SagaPersistenceBehavior.<Invoke>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei NServiceBus.InvokeSagaNotFoundBehavior.<Invoke>d__0.MoveNext()
```

imho, both versions are not ideal, I'd expect in both cases an exception stating the invalid correlation property value and not invoking the handler.

**Comment by andreasohlund** [comment] 2018-01-24 14:18
Agreed, we need to move the validation to execute before we try to load the saga

**Comment by timbussmann** [comment] 2018-01-25 14:40
we discussed this issue on yesterday's maintainer sync and came to the following conclusions:
* we should ensure to make the null check before invoking the persistence or saga handlers to prevent NRE from downstream/user code. This is something we'd like to address within a minor version although the change in the exception behavior changes the runtime behavior.
* We should allow default values, but not null values. This is a separate issue though.
* We don't consider the FLR/SLR behavior a big issue and don't plan to change the current behavior (retrying messages with incorrect correlation property value). If you feel strongly about it, we suggest to raise a new issue about this as well.

based on this, I'd suggest to close this issue as the mentioned points will be addressed by dedicated issues. Are you happy with that too @ramonsmits ?

**Comment by timbussmann** [comment] 2018-01-29 16:22
closing this now as suggested in the comment before.

**Closed by timbussmann** 2018-01-29 16:22 UTC
